/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDate, NSString;

@interface ABtestCase : XXUnknownSuperclass {
	NSString* caseID;
	NSString* verifyMd5;
	NSDate* startTime;
	NSDate* endTime;
}
@property(retain, nonatomic) NSDate* endTime;
@property(retain, nonatomic) NSDate* startTime;
@property(retain, nonatomic) NSString* verifyMd5;
@property(retain, nonatomic) NSString* caseID;
-(void).cxx_destruct;
-(BOOL)isEffective;
-(BOOL)isSolidified;
-(id)init;
@end

