/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface ActionMusic : XXUnknownSuperclass <NSCoding> {
	NSString* _name;
	NSString* _desc;
	NSString* _wifiUrl;
	NSString* _wapUrl;
	NSString* _webUrl;
}
@property(retain, nonatomic) NSString* webUrl;
@property(retain, nonatomic) NSString* wapUrl;
@property(retain, nonatomic) NSString* wifiUrl;
@property(retain, nonatomic) NSString* desc;
@property(retain, nonatomic) NSString* name;
-(void).cxx_destruct;
-(id)toXml;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)init;
@end

