/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol AMRAudioPlayerDelegate
@optional
-(BOOL)OnAMREndDontNotifyOtherApp;
-(void)OnAMREarTip;
-(void)OnAMREndPlaying:(id)playing isForceStop:(BOOL)stop;
-(void)OnAMRBeginPlaying:(id)playing ErrNo:(int)no;
-(void)OnAMRLevelMeter:(id)meter Peak:(float)peak;
@end

