/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class BackPageInfo, ShowWordsInfo, RegApInfo, NSString, QstrInfo, BaseResponse, FrontPageInfo;

@interface APAuthResponse : WXPBGeneratedMessage {
}
@property(assign, nonatomic) unsigned relativeExpiredSeconds;
@property(retain, nonatomic) NSString* tid;
@property(retain, nonatomic) NSString* openId;
@property(retain, nonatomic) BackPageInfo* backPageInfo;
@property(retain, nonatomic) FrontPageInfo* frontPageInfo;
@property(retain, nonatomic) QstrInfo* qstrInfo;
@property(retain, nonatomic) ShowWordsInfo* checkWords;
@property(retain, nonatomic) RegApInfo* regApInfo;
@property(assign, nonatomic) unsigned opCode;
@property(retain, nonatomic) ShowWordsInfo* showWords;
@property(retain, nonatomic) NSString* showUrl;
@property(assign, nonatomic) unsigned actionCode;
@property(assign, nonatomic) unsigned expiredTime;
@property(retain, nonatomic) NSString* authUrl;
@property(retain, nonatomic) BaseResponse* baseResponse;
+(void)initialize;
@end

