/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSURL, NSString;

@interface AppCommentItem : XXUnknownSuperclass {
	NSString* caption;
	NSString* reportid;
	NSURL* commenturl;
	NSString* itemType;
	int buttonIndex;
}
@property(assign, nonatomic) int buttonIndex;
@property(retain, nonatomic) NSString* itemType;
@property(retain, nonatomic) NSURL* commenturl;
@property(retain, nonatomic) NSString* reportid;
@property(retain, nonatomic) NSString* caption;
-(void).cxx_destruct;
-(BOOL)isCancelButton;
-(id)description;
-(void)dealloc;
@end

