/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class SKBuiltinBuffer_t, NSString;

@interface AppMsg : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* jsAppId;
@property(retain, nonatomic) NSString* shareUrlOpen;
@property(retain, nonatomic) NSString* shareUrlOriginal;
@property(retain, nonatomic) NSString* msgSource;
@property(assign, nonatomic) int remindId;
@property(assign, nonatomic) int source;
@property(retain, nonatomic) SKBuiltinBuffer_t* thumb;
@property(retain, nonatomic) NSString* clientMsgId;
@property(assign, nonatomic) unsigned createTime;
@property(retain, nonatomic) NSString* content;
@property(assign, nonatomic) unsigned type;
@property(retain, nonatomic) NSString* toUserName;
@property(assign, nonatomic) unsigned sdkVersion;
@property(retain, nonatomic) NSString* appId;
@property(retain, nonatomic) NSString* fromUserName;
+(void)initialize;
@end

