/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"


@interface AppStoreControl : WXPBGeneratedMessage {
}
@property(assign, nonatomic) unsigned promptDuration;
@property(assign, nonatomic) unsigned promptCycle;
@property(assign, nonatomic) unsigned downloadInternal;
+(void)initialize;
@end

