/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol AQAudioRecorderDelegate
@optional
-(void)OnAQPart:(id)part Duration:(float)duration EndFlag:(unsigned long)flag ForceDelete:(BOOL)aDelete;
-(void)OnAQEndRecording:(id)recording;
-(void)OnAQBeginRecording:(id)recording ErrNo:(int)no;
@end

