/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSCondition, NSLock;

@interface AsyncTaskQueueEngine : XXUnknownSuperclass {
	NSCondition* _conditon;
	NSMutableArray* _arrHighLevelTask;
	NSMutableArray* _arrMiddleLevelTask;
	NSMutableArray* _arrLowLevelTask;
	BOOL _isForeground;
	BOOL _enableForegroundTask;
	BOOL _enableTimerTask;
	NSLock* _statusLock;
}
-(void).cxx_destruct;
-(void)main;
-(void)asyncSignal;
-(void)setTimerTaskValid:(BOOL)valid;
-(BOOL)excuteBackgroundTask:(int)task;
-(BOOL)excuteTimerTask:(int)task;
-(BOOL)excuteForegroundTask:(int)task;
-(BOOL)excuteInitTask:(int)task;
-(id)getAllTask:(int)task;
-(void)cancel;
-(void)forbidForegroundTask;
-(void)enableForegroundTask;
-(BOOL)hasEnableForegroundTask;
-(void)enterBackground;
-(void)enterForeground;
-(void)waitAllTask;
-(void)signalAllTask;
-(void)unregisterAllTask;
-(void)unregisterTask:(id)task;
-(void)registerTask:(id)task priority:(int)priority;
-(id)init;
@end

