/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCoding.h"

@class NSMutableArray, BakChatMsgItem, NSData, BakChatMsgList;

@interface BakChatUploadPackageHelperStruct : XXUnknownSuperclass <NSCoding> {
	NSMutableArray* m_usrNameArray;
	unsigned m_chatSvrID;
	long long m_n64ChatSvrID;
	unsigned m_curRowIndex;
	unsigned m_mediaIndex;
	unsigned m_appRecordMediaIndex;
	BakChatMsgItem* m_msgItem;
	BakChatMsgList* m_msgList;
	unsigned m_bakChatSvrID;
	unsigned filterCount;
	BOOL m_bGetAnyOneMessage;
	NSData* encryptKeyData;
	unsigned long uploadData_NetworkType;
	unsigned long uploadData_ErrorCount;
	unsigned long uploadData_PauseCount;
	BOOL uploadData_AllSelected;
}
@property(assign, nonatomic) BOOL uploadData_AllSelected;
@property(assign, nonatomic) unsigned long uploadData_PauseCount;
@property(assign, nonatomic) unsigned long uploadData_ErrorCount;
@property(assign, nonatomic) unsigned long uploadData_NetworkType;
@property(assign, nonatomic) BOOL m_bGetAnyOneMessage;
@property(retain, nonatomic) NSData* encryptKeyData;
@property(assign, nonatomic) unsigned filterCount;
@property(assign, nonatomic) unsigned m_bakChatSvrID;
@property(retain, nonatomic) BakChatMsgList* m_msgList;
@property(retain, nonatomic) BakChatMsgItem* m_msgItem;
@property(assign, nonatomic) unsigned m_appRecordMediaIndex;
@property(assign, nonatomic) unsigned m_mediaIndex;
@property(assign, nonatomic) unsigned m_curRowIndex;
@property(assign, nonatomic) long long m_n64ChatSvrID;
@property(retain, nonatomic) NSMutableArray* m_usrNameArray;
+(id)getSameBakChatUploadPackageHelperStruct:(id)aStruct;
-(void).cxx_destruct;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)setEncryptKey:(id)key;
-(void)clear;
-(void)dealloc;
-(id)init;
@end

