/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NSMutableArray, NSString, BaseRequest;

@interface BakChatCreateQRCodeOfflineRequest : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* tickit;
@property(retain, nonatomic) NSString* wifiName;
@property(assign, nonatomic) unsigned long long dataSize;
@property(assign, nonatomic) unsigned scene;
@property(retain, nonatomic) NSString* pcacctName;
@property(retain, nonatomic) NSString* pcname;
@property(retain, nonatomic) NSMutableArray* addrList;
@property(assign, nonatomic) unsigned addrCount;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

