/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"

@protocol TextLayoutDelegate;

@interface BaseParser : XXUnknownSuperclass {
	id<TextLayoutDelegate> _layoutDelegate;
	unsigned _parserType;
}
@property(assign, nonatomic) unsigned parserType;
@property(assign, nonatomic) __weak id<TextLayoutDelegate> layoutDelegate;
+(id)sharedInstance;
+(id)newInstance;
-(void).cxx_destruct;
-(id)attributeStringForContent:(id)content;
-(BOOL)shouldOpenNewLineAtY:(float)y withLineHeight:(float)lineHeight;
-(float)getNextLineOriginWithCurrentY:(float)currentY lineHeight:(float)height withMaxWidth:(float)maxWidth;
-(id)parseTextForStyles:(id)styles withParserPosition:(NSParserPosition*)parserPosition;
-(void)insertString:(id)string stringRange:(NSRange)range styleRect:(CGRect)rect;
-(id)getStylesForString:(id)string withStyleString:(id)styleString;
-(id)styleStringForContent:(id)content withParserPosition:(NSParserPosition)parserPosition outputLastPosition:(NSParserPosition*)position;
-(id)stylesForString:(id)string withRange:(NSRange)range withParserPosition:(NSParserPosition*)parserPosition;
-(NSRange)rangeOfObjectInString:(id)string withRange:(NSRange)range;
@end

