/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BlueAdapterSessionDelegate.h"
#import "BlueProfilePedometerDelegate.h"


@protocol BlueAdapterDelegate <BlueAdapterSessionDelegate, BlueProfilePedometerDelegate>
@end

