/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "TextParser.h"


@interface BoldTextParser : TextParser {
}
+(id)newInstance;
-(id)parseContent:(id)content;
-(id)attributeStringForContent:(id)content;
-(id)stylesForString:(id)string withRange:(NSRange)range withParserPosition:(NSParserPosition*)parserPosition;
-(id)styleStringForContent:(id)content withParserPosition:(NSParserPosition)parserPosition outputLastPosition:(NSParserPosition*)position;
-(id)getStylesForString:(id)string withStyleString:(id)styleString;
-(id)getStyle;
-(NSRange)rangeOfObjectInString:(id)string withRange:(NSRange)range;
@end

