/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMObject.h"
#import "imageViewDelegate.h"

@class UIImageView, MMImageView, MMTimer, UIView, NSString;
@protocol BottleAnimationDelegate;

@interface BottleAnimation : MMObject <imageViewDelegate> {
	unsigned long mAnimationStatus;
	BOOL mIsBalloonAnimationEnabled;
	unsigned long mLightAnimationStatus;
	id<NSObject, BottleAnimationDelegate> delegate;
	UIView* mCanvasView;
	UIImageView* mBalloonImageView;
	MMTimer* mLightTimer;
	UIImageView* mMoonImageView;
	UIImageView* mStarImageView;
	UIImageView* mLightLImageView;
	UIImageView* mLightMImageView;
	UIImageView* mLightRImageView;
	UIImageView* mEmptyBottleImageView;
	UIImageView* mSuckedObjectImageView;
	UIImageView* mWaterImageView;
	UIImageView* mWater2ImageView;
	UIImageView* mWater3ImageView;
	MMImageView* mFishStarImageView;
	MMImageView* mFishBottleImageView;
	UIView* mFishBottleTipView;
	CGPoint mBalloonToPoint;
}
@property(retain, nonatomic) UIView* mFishBottleTipView;
@property(retain, nonatomic) MMImageView* mFishBottleImageView;
@property(retain, nonatomic) MMImageView* mFishStarImageView;
@property(retain, nonatomic) UIImageView* mWater3ImageView;
@property(retain, nonatomic) UIImageView* mWater2ImageView;
@property(retain, nonatomic) UIImageView* mWaterImageView;
@property(retain, nonatomic) UIImageView* mSuckedObjectImageView;
@property(retain, nonatomic) UIImageView* mEmptyBottleImageView;
@property(retain, nonatomic) UIImageView* mLightRImageView;
@property(retain, nonatomic) UIImageView* mLightMImageView;
@property(retain, nonatomic) UIImageView* mLightLImageView;
@property(retain, nonatomic) UIImageView* mStarImageView;
@property(retain, nonatomic) UIImageView* mMoonImageView;
@property(retain, nonatomic) MMTimer* mLightTimer;
@property(retain, nonatomic) UIImageView* mBalloonImageView;
@property(assign, nonatomic) CGPoint mBalloonToPoint;
@property(retain, nonatomic) UIView* mCanvasView;
@property(assign, nonatomic) __weak id<NSObject, BottleAnimationDelegate> delegate;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(BOOL)isFinish;
-(void)fishbranduser_animation;
-(void)fishtext_animation;
-(void)fishaudio_animation;
-(void)fishfail_animation;
-(void)fishing_animation;
-(void)throwtext_animation;
-(void)throwaudio_animation;
-(void)sucktext_animation;
-(void)suckaudio_animation;
-(void)stop_light_animationWithDarkValue:(float)darkValue;
-(void)light_animation;
-(void)stop_balloon_animationWithDarkValue:(float)darkValue forced:(BOOL)forced;
-(void)balloon_animation;
-(void)initStatus;
-(void)hideAllView;
-(void)resetStatus;
-(void)dealloc;
-(id)initWithCanvas:(id)canvas;
-(id)init;
-(void)fishoverAnimation;
-(void)fishfailAnimation;
-(void)fishing3Animation;
-(void)fishing2Animation;
-(void)fishingAnimation;
-(void)throwBottleAnimationToPoint:(CGPoint)point;
-(void)bottleSuckedAnimation;
-(void)curlupAnimation;
-(void)rippleAnimation;
-(void)lightAnimation;
-(void)OnLightTimer;
-(void)balloonAnimationGoToPoint:(CGPoint)point;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(void)showOpenBottleTip;
-(void)stopFishStar;
-(void)initFishBottleViewInFrame:(CGRect)frame imageSize:(CGSize)size;
-(void)initFishStarViewInFrame:(CGRect)frame;
-(void)initWaterViewInFrame:(CGRect)frame;
-(void)initThrowBottleViewAtPoint:(CGPoint)point;
-(void)initLightViewAtPoint:(CGPoint)point;
-(void)initBalloonViewAtPoint:(CGPoint)point;
-(void)touchesEnded_ImageView:(id)view withEvent:(id)event;
@end

