/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FTSJSEventDelegate.h"
#import "BrandArticleSearchPageBaseLogicImplement.h"
#import "WeChat-Structs.h"
#import "BrandArticleSearchPageBaseLogic.h"

@class BrandArticleSearchResultView, NSString;

@interface BrandArticleSearchResultLogic : BrandArticleSearchPageBaseLogic <BrandArticleSearchPageBaseLogicImplement, FTSJSEventDelegate> {
	BrandArticleSearchResultView* m_resultView;
	NSString* _lastInputText;
	timeval _lastInputTime;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(BOOL)isSupportSuggestion;
-(void)notifyPageOfSearchClick:(id)searchClick;
-(void)notifyPageOfQueryChanged:(id)queryChanged;
-(void)onSearchInputChanged:(id)changed;
-(void)onClickRecmdWord:(id)word;
-(void)onLaunchPage:(id)page withParams:(id)params;
-(void)onPreSearch:(id)search;
-(void)onFailReceiveJson;
-(void)onReceiveJson:(id)json;
-(void)onWebViewFinishLoad;
-(void)functionCall:(id)call withParams:(id)params withCallbackID:(id)callbackID;
-(id)currentImplement;
-(BOOL)notifyPreCheckQuery:(id)query;
-(id)urlForResultPage;
-(id)htmlPathForResult;
-(void)configSearchMgrDelegate;
-(void)clearResultPage;
-(void)trySearch:(id)search;
-(void)notifyChanged:(id)changed;
-(void)textChanged:(id)changed;
-(void)loadPage;
-(void)dealloc;
-(id)initWithSearchLogic:(id)searchLogic resultView:(id)view;
@end

