/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "IKFContactMgrExt.h"
#import "IEnterpriseContactMgrExt.h"
#import "WeChat-Structs.h"
#import "UIAlertViewDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "IEnterpriseBrandContactMgrExt.h"
#import "CBaseContactInfoAssist.h"
#import "IWCDeviceBrandMgrExt.h"
#import "ICertInfoMgrExt.h"

@class UIView, MMBrandHeadImageView, NSString, CertInfo, MMTableView, UIButton, NSArray, WCADPageWrap, NSMutableArray;

@interface BrandUserContactInfoAssist : CBaseContactInfoAssist <UITableViewDelegate, UITableViewDataSource, UIAlertViewDelegate, IWCDeviceBrandMgrExt, IKFContactMgrExt, IEnterpriseContactMgrExt, IEnterpriseBrandContactMgrExt, ICertInfoMgrExt> {
	UIButton* _viewMsgBtn;
	UIButton* _followBtn;
	BOOL _isSettingsChanged;
	BOOL _isMuteChanged;
	BOOL _isEnterpriseSessionTopChanged;
	BOOL _needGetWorker;
	NSArray* _bindWorkerList;
	MMBrandHeadImageView* m_brandHeadView;
	NSMutableArray* m_arrData;
	UIView* m_titleView;
	MMTableView* m_tableView;
	CertInfo* m_certInfo;
	WCADPageWrap* _profilePageWrap;
	unsigned long _lastCertificationFlag;
	NSString* _searchKeyword;
	unsigned long _searchFromIndex;
	NSString* _searchExtraParamsString;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* searchExtraParamsString;
@property(assign, nonatomic) unsigned long searchFromIndex;
@property(retain, nonatomic) NSString* searchKeyword;
@property(retain, nonatomic) NSMutableArray* m_arrData;
-(void).cxx_destruct;
-(void)OnUpdateCertInfo;
-(void)onEnterpriseBrandContactSyncToSvrCompleted:(id)svrCompleted extParams:(id)params;
-(void)onUpdateMyEnterpriseContact:(id)contact errCode:(int)code;
-(void)onUpdateMyContactUserFlag:(id)flag bitMask:(unsigned long)mask errCode:(int)code;
-(BOOL)isTempBrandSession;
-(float)getRightLabelWidth;
-(id)hardcodeKFWorker;
-(void)onUpdateKFContactsList:(id)list errCode:(int)code;
-(void)onGetKFContactsDefaultList:(id)list errCode:(int)code;
-(void)onGetKFContactsBindList:(id)list errCode:(int)code;
-(BOOL)isInCustomAlertMode;
-(BOOL)isContactExpired;
-(float)getRegisterBodyRightWidth;
-(float)getVerifySourceRightWidth;
-(float)getTextFieldTopMarginVerifyLogic:(id)logic;
-(id)getAlertMessageForVerifyLogic:(id)verifyLogic;
-(id)getAlertTitleForVerifyLogic:(id)verifyLogic;
-(void)contactVerifyOk:(id)ok opCode:(unsigned long)code;
-(void)onShowDisabledEnterpriseSubBrand;
-(void)switchEnableEnterpriseSubBrand;
-(void)onEnableEnterpriseSubBrandBtnSwitched:(id)switched;
-(void)onSwitchEnableEnterpriseSubBrand;
-(void)onShowMessage;
-(void)opLogToSvr;
-(void)onNotificationSwitchChanged:(id)changed;
-(void)onEnterpriseStickyOnTopSwitchChanged:(id)changed;
-(void)onEnterpriseNotificationSwitchChanged:(id)changed;
-(void)onEnterpriseBlockSwitchChanged:(id)changed;
-(void)onBlockSwitchChanged:(id)changed;
-(void)onShowSwitchChanged:(id)changed;
-(void)onEnterWebView:(id)view;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)onAllowPositionChanged:(id)changed;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)onClearContent;
-(void)onClickNavRightButton;
-(id)getBrandInfoItemAndRemoveIt:(id)it fromArray:(id)array;
-(id)getTitleKey:(id)key;
-(id)getUrlItemUrl:(id)url;
-(id)getUrlItemDescription:(id)description;
-(id)getMatchTitle:(id)title;
-(id)getPrivilegeIcon:(id)icon;
-(id)getMatchDescription:(id)description;
-(void)onWCDeviceUnbindEnd:(id)end Error:(id)error;
-(void)onWCDeviceBindEnd:(id)end Error:(id)error;
-(void)cancelFocus;
-(void)onShowCancelFocusTips:(id)tips;
-(void)onAddToContacts;
-(void)onBindDevice;
-(int)getPrivilegeItemHeight:(id)height;
-(int)calPrivilegesCellHeight;
-(int)calVerifySourceCellHeight;
-(int)calBusinessScopeCellHeight;
-(int)calSignatureCellHeight;
-(int)calRegisterBodyCellHeight;
-(int)calTrademarkBodyHeight;
-(void)onEnterEnterprise;
-(void)onEnterEnterpriseChat;
-(void)onTemplateMsgRecv;
-(void)onCallServicePhone:(id)phone;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)makeCell:(id)cell row:(unsigned)row section:(unsigned long)section;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(id)tableView:(id)view titleForFooterInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)updateTitleView;
-(void)initTitleView;
-(void)markRecentUsedContact;
-(void)handleAddedContact;
-(void)checkUpdateCertInfo;
-(void)reloadTableView;
-(void)onContactUpdated;
-(BOOL)isDeviceBound;
-(BOOL)hasDeviceUserData;
-(void)updateFooterView;
-(void)makeDisableEnterpriseSubBrand:(id)brand;
-(void)makeShowDisabledEnterpriseSubBrand:(id)brand;
-(float)widthForBusinessScopeTitleLabel;
-(void)makeBusinessScopeCell:(id)cell;
-(void)makeMerchantSecurityCell:(id)cell;
-(void)makeMerchantRatings:(id)ratings;
-(void)makeServicePhoneCell:(id)cell withPhone:(id)phone;
-(void)makeEnterEnterpriseCell:(id)cell;
-(void)makeShowMessageCell:(id)cell;
-(void)makeAllowPositionCell:(id)cell;
-(void)makeHideFromProfileCell:(id)profileCell;
-(void)makeTemplateMsgRecvCell:(id)cell;
-(void)makeNewMessageNotificationCell:(id)cell;
-(void)makeEnterpriseChatEntryCell:(id)cell;
-(void)makeEnterpriseBrandStikyOnTopCell:(id)cell;
-(void)makeEnterpriseNewMessageNotificationCell:(id)cell;
-(void)makeEnterpriseBlockMessageCell:(id)cell;
-(void)makeBlockMessageNotifyCell:(id)cell;
-(BOOL)shouldEnterpriseStickyOnTop;
-(BOOL)shouldMuteEnterpriseNotification;
-(BOOL)shouldReceiveEnterpriseMessage;
-(BOOL)shouldReceiveMessage;
-(void)makeUrlCell:(id)cell withData:(id)data;
-(void)makeBindWorkerCell:(id)cell;
-(void)makePrivilegesCell:(id)cell;
-(void)makeTrandemarkBodyCell:(id)cell;
-(void)makeVerifySourceCell:(id)cell;
-(id)getVerifySourceAttributedString;
-(void)makeNearFieldCell:(id)cell;
-(void)makeRegisterBodyCell:(id)cell;
-(void)makeSignatureCell:(id)cell;
-(void)reloadRowData;
-(unsigned long)transToReportScene:(unsigned long)reportScene;
-(void)updateNickNameLabel;
-(void)initFooterView;
-(void)initNickNameLabel;
-(void)initHDHeadImage;
-(void)initHeadImage;
-(void)updateNavigationBarRightButton;
-(void)adjustNickNameAndUserNameLabelVerticalCenter;
-(void)initHeaderView;
-(id)GetTableView;
-(void)initTableView;
-(id)initWithContact:(id)contact delegate:(id)delegate;
-(void)dealloc;
-(void)profileDestory;
-(void)recordProfilePageWrap;
-(BOOL)isFromNotifyMessage;
@end

