/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BSSBaseItemView.h"

@class AttributeLabel, MMMaskHeadImageView, BSBusinessContactItem, NSArray;

@interface BSSBrandContactItemView : BSSBaseItemView {
	BSBusinessContactItem* _dataItem;
	NSArray* _keywordList;
	MMMaskHeadImageView* _headImgView;
	AttributeLabel* _nameLabel;
	AttributeLabel* _descLabel;
}
@property(retain, nonatomic) AttributeLabel* descLabel;
@property(retain, nonatomic) AttributeLabel* nameLabel;
@property(retain, nonatomic) MMMaskHeadImageView* headImgView;
@property(retain, nonatomic) NSArray* keywordList;
@property(retain, nonatomic) BSBusinessContactItem* dataItem;
+(float)heightForItem;
-(void).cxx_destruct;
-(void)initView;
-(id)initWithContactItem:(id)contactItem andKeyWordList:(id)list;
-(void)dealloc;
@end

