/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol CanvasManagerDelegate
@optional
-(id)NavigationController;
-(void)enableTouch;
-(void)disableTouch;
-(void)unSpotLightCanvasAnimated:(BOOL)animated;
-(void)spotLightCanvasAnimated:(BOOL)animated;
-(void)unDarkenCanvasAnimated:(BOOL)animated;
-(void)darkenCanvasAnimated:(BOOL)animated;
-(unsigned long)canvasHeightForDraw;
-(void)showCanvasBottomBarAnimated:(BOOL)animated;
-(void)hideCanvasBottomBarAnimated:(BOOL)animated;
-(void)showCanvasTopBarAnimated:(BOOL)animated;
-(void)hideCanvasTopBarAnimated:(BOOL)animated;
@end

