/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSFileHandle, NSString;

@interface CBaseFile : XXUnknownSuperclass {
	NSFileHandle* m_fhFile;
	NSString* m_nsFilePath;
	unsigned long m_uiMode;
	BOOL m_bOpen;
}
@property(retain, nonatomic) NSFileHandle* m_fhFile;
@property(retain, nonatomic) NSString* m_nsFilePath;
+(id)GetDataMD5:(id)a5;
+(id)GetFileMD5:(id)a5;
+(id)GetFileCreateTime:(id)time;
+(BOOL)SysAppendData:(id)data toPath:(id)path;
+(BOOL)SysOverWriteDataToPath:(id)path Data:(id)data;
+(BOOL)OverWriteDataToPath:(id)path Data:(id)data;
+(BOOL)AppendData:(id)data toPath:(id)path;
+(BOOL)WriteDataToPath:(id)path Offset:(unsigned long)offset Data:(id)data;
+(id)LoadDataFromPathEx:(id)pathEx Offset:(unsigned long)offset MaxLen:(unsigned long)len;
+(id)LoadDataFromPath:(id)path Offset:(unsigned long)offset Len:(unsigned long)len;
+(BOOL)CreateSymbolLink:(id)link LinkName:(id)name;
+(void)ClearPath:(id)path WithOut:(id)anOut;
+(void)SyncClearPath:(id)path;
+(void)ClearPath:(id)path;
+(long long)GetFileSize:(id)size;
+(BOOL)RemoveFile:(id)file;
+(BOOL)LoadSubFolders:(id)folders SubFiles:(id)files fromFolderPath:(const char*)folderPath;
+(id)SubFilesName:(const char*)name;
+(id)SubFoldersName:(const char*)name;
+(long long)FolderSizeAtPath:(const char*)path;
+(long long)GetFiLeSize:(id)size;
+(long)GetFiLeModifyTime:(id)time;
+(BOOL)FileExist:(id)exist;
+(BOOL)CopyFile:(id)file To:(id)to;
+(BOOL)RenameFile:(id)file To:(id)to;
+(void)EnsureCreateParentDir:(id)dir;
+(BOOL)CreatePath:(id)path;
+(BOOL)CreateFile:(id)file;
-(void).cxx_destruct;
-(BOOL)WriteLargeData:(id)data;
-(BOOL)WriteData:(id)data;
-(BOOL)ReadData:(id)data Len:(unsigned long)len;
-(unsigned long long)SeekToEndOfFile;
-(BOOL)Seek:(long long)seek;
-(BOOL)SetFileSize:(long long)size;
-(void)Close;
-(BOOL)Open;
-(BOOL)IsOpen;
-(BOOL)SetFileInfo:(id)info Mode:(unsigned long)mode;
-(void)dealloc;
-(id)init;
@end

