/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface CBottleSetting : XXUnknownSuperclass <NSCoding> {
	unsigned long m_uiSex;
	NSString* m_nsCountry;
	NSString* m_nsProvince;
	NSString* m_nsCity;
	NSString* m_nsSignature;
	NSString* m_nsHeadImageMD5;
	NSString* m_nsHDImgStatus;
	NSString* m_nsImgStatus;
	BOOL m_bFirstIn;
	unsigned long m_uiLastMsgType;
	unsigned long m_uiChatStatus;
	NSString* m_nsHeadImgUrl;
	NSString* m_nsHeadHDImgUrl;
}
@property(retain, nonatomic) NSString* m_nsHeadHDImgUrl;
@property(retain, nonatomic) NSString* m_nsHeadImgUrl;
@property(assign, nonatomic) unsigned long m_uiChatStatus;
@property(assign, nonatomic) unsigned long m_uiLastMsgType;
@property(assign, nonatomic) BOOL m_bFirstIn;
@property(retain, nonatomic) NSString* m_nsImgStatus;
@property(retain, nonatomic) NSString* m_nsHDImgStatus;
@property(retain, nonatomic) NSString* m_nsHeadImageMD5;
@property(retain, nonatomic) NSString* m_nsSignature;
@property(retain, nonatomic) NSString* m_nsCity;
@property(retain, nonatomic) NSString* m_nsProvince;
@property(retain, nonatomic) NSString* m_nsCountry;
@property(assign, nonatomic) unsigned long m_uiSex;
-(void).cxx_destruct;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(id)init;
-(void)preInit;
@end

