/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CMessageWrap, NSString;

@interface CEmoticonUploadInfo : XXUnknownSuperclass {
	NSString* m_nsMD5;
	unsigned long m_uiSendTime;
	unsigned long m_uiStartPos;
	unsigned long m_uiTotalLen;
	BOOL m_bFirst;
	NSString* m_nsUsrExtern;
	CMessageWrap* m_wrapMsg;
}
@property(retain, nonatomic) CMessageWrap* m_wrapMsg;
@property(retain, nonatomic) NSString* m_nsUsrExtern;
@property(assign, nonatomic) BOOL m_bFirst;
@property(assign, nonatomic) unsigned long m_uiTotalLen;
@property(assign, nonatomic) unsigned long m_uiStartPos;
@property(assign, nonatomic) unsigned long m_uiSendTime;
@property(retain, nonatomic) NSString* m_nsMD5;
-(void).cxx_destruct;
-(id)description;
-(id)init;
@end

