/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, NSString;

@interface CertInfo : XXUnknownSuperclass <NSCoding> {
	unsigned long m_uiVersion;
	unsigned long m_uiKey;
	unsigned long m_uiLastUpdateTime;
	NSString* m_nsDesc;
	UIImage* m_imgIcon;
}
@property(retain, nonatomic) UIImage* m_imgIcon;
@property(retain, nonatomic) NSString* m_nsDesc;
@property(assign, nonatomic) unsigned long m_uiLastUpdateTime;
@property(assign, nonatomic) unsigned long m_uiKey;
@property(assign, nonatomic) unsigned long m_uiVersion;
-(void).cxx_destruct;
-(id)description;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(id)init;
-(void)preInit;
@end

