/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSOperationQueue, NSMutableArray, NSMutableSet, NSMutableDictionary, NSRecursiveLock;
@protocol ChatMigrationRecoverChatFileHelperDelegate;

@interface ChatMigrationRecoverChatFileHelper : XXUnknownSuperclass {
	BOOL m_bRecovering;
	NSOperationQueue* m_operationQueue;
	NSRecursiveLock* m_oLock;
	NSMutableArray* m_arrDumpInfo;
	NSMutableDictionary* m_dicMediaIDPath;
	NSMutableSet* m_setChatName;
	NSMutableDictionary* m_dicReportInfo;
	unsigned m_messageItemCount;
	unsigned m_messageNoSvrIdCount;
	unsigned m_messageNotSupportCount;
	unsigned m_bakMessageItemNilCount;
	unsigned m_bakMessageWrapNilCount;
	id<ChatMigrationRecoverChatFileHelperDelegate> m_delegate;
}
@property(assign, nonatomic) __weak id<ChatMigrationRecoverChatFileHelperDelegate> m_delegate;
+(id)GetRecoverMediaFilePath:(id)path;
-(void).cxx_destruct;
-(void)StopRecoverMessage;
-(BOOL)internalRecoverMessage:(id)message;
-(void)StartRecoverThread:(id)thread;
-(void)StartRecoverMessage:(id)message;
-(void)ReImportSessionData;
-(void)HasAnotherMsgForChatName:(id)chatName;
-(BOOL)addMsgAndFormMediaDictionary:(id)dictionary;
-(BOOL)AddContactListChat;
-(BOOL)RenameMediaFiles;
-(id)messageWrapFromBakChatMsgItem:(id)bakChatMsgItem;
-(void)convertStatusVideo:(id)video andBakchatMsgItem:(id)item;
-(BOOL)handleBufferForBakChatMsgItem:(id)bakChatMsgItem messageWrap:(id)wrap;
-(void)ClearDumpInfo;
-(id)GetDicOfMediaIDPath;
-(void)SafeSetObjectForMediaPathDic:(id)mediaPathDic forKey:(id)key;
-(id)onClearVoiceHeadData:(id)data;
-(id)pathForMessageWrap:(id)messageWrap forBakChatMediaType:(unsigned long)bakChatMediaType withMediaID:(id)mediaID;
-(id)getMediaHeadByMessageWrap:(id)wrap;
-(id)getMediaIDByMessageWrap:(id)wrap;
-(id)getPackagePathNameForMediaID:(id)mediaID;
-(void)clearAllOldPackageIfNotStarted;
-(void)clearAllOldPackage:(BOOL)package;
-(BOOL)isBakChatName:(id)name;
-(void)initCacheMediaDataPath;
-(id)GetRecoverDumpFilePath:(id)path;
-(void)dealloc;
-(id)init;
@end

