/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMUIViewController.h"
#import "WCAccountBindPhoneControlLogicDelegate.h"
#import "UIWebViewDelegate.h"
#import "IGroupMgrExt.h"

@class UIWebView, WCAccountBindPhoneControlLogic, CContact, NSString;

@interface ChatRoomConfirmWebViewController : MMUIViewController <WCAccountBindPhoneControlLogicDelegate, IGroupMgrExt, UIWebViewDelegate> {
	UIWebView* m_webView;
	CContact* m_chatRoomContact;
	WCAccountBindPhoneControlLogic* m_bindLogic;
	BOOL m_needBindPhone;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL needBindPhone;
@property(retain, nonatomic) CContact* chatRoomContact;
-(void).cxx_destruct;
-(void)OnChatRoomUpgrade:(id)upgrade rspCode:(int)code restQuota:(unsigned long)quota maxCount:(unsigned long)count;
-(void)bindPhoneReturn;
-(void)onWCAccountBindPhoneControlLogicStop;
-(void)upgradeChatRoom;
-(void)checkBindPhone;
-(BOOL)webView:(id)view shouldStartLoadWithRequest:(id)request navigationType:(int)type;
-(id)dismissWithAnim;
-(void)dealloc;
-(void)viewDidLoad;
@end

