/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ChatRoomMemberGridViewDelegate <NSObject>
@optional
-(void)onLongPressEx:(id)ex;
-(void)showMoreMember;
-(void)setShowRemoveMember;
-(void)onDeleteMember:(id)member;
-(void)addMember;
-(void)openContactInfo:(id)info;
@end

