/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MMTimer;
@protocol ChatMigrationHeartBeatMonitorDelegate;

@interface ChatMigrationHeartBeatMonitor : XXUnknownSuperclass {
	unsigned long long nextAckID;
	MMTimer* m_heartBeatTimer;
	BOOL m_bMonitorEnable;
	BOOL m_bHeartBeatTransfer;
	id<ChatMigrationHeartBeatMonitorDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<ChatMigrationHeartBeatMonitorDelegate> delegate;
-(void).cxx_destruct;
-(void)checkHeartBeat;
-(void)disableHeartBeatMonitor;
-(void)enableHeartBeatMonitor;
-(void)sendHeartBeatRequest;
-(void)getHeartBeatPacketWithAckID:(unsigned long long)ackID;
-(void)p_sendHeartBeatToRemote;
-(id)init;
@end

