/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMLoadSessionExt.h"
#import "UIAlertViewDelegate.h"
#import "MMUIViewController.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class UILabel, UIImageView, NSString, MMTableView, UIButton, UIActivityIndicatorView, NSMutableArray;

@interface ChatMigrationSelectSessionViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, MMLoadSessionExt, UIAlertViewDelegate> {
	unsigned m_curMaxDataCount;
	MMTableView* _sessionTableView;
	UIImageView* _footerImageView;
	UIButton* _selectAllButton;
	UILabel* _sizeLabel;
	UILabel* _emptyTipLabel;
	NSMutableArray* _selectedSessionArray;
	UIActivityIndicatorView* _loadingIndicatorView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIActivityIndicatorView* loadingIndicatorView;
@property(retain, nonatomic) NSMutableArray* selectedSessionArray;
@property(retain, nonatomic) UILabel* emptyTipLabel;
@property(retain, nonatomic) UILabel* sizeLabel;
@property(retain, nonatomic) UIButton* selectAllButton;
@property(retain, nonatomic) UIImageView* footerImageView;
@property(retain, nonatomic) MMTableView* sessionTableView;
-(void).cxx_destruct;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)onLoadSessionDataFinished;
-(void)onReloadDataItem;
-(void)onLoadDataFinished;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)onSelecteAll;
-(void)onDone;
-(void)onReturn;
-(id)getDataSizeShowString:(id)string;
-(id)getSelectButtonTitle;
-(CGRect)getTableViewFrame;
-(BOOL)whetherSessionItemSelected:(id)selected;
-(void)onSelectedDataChange;
-(void)loadMoreData;
-(unsigned long long)getDataSize:(id)size;
-(BOOL)isSessionDataFull;
-(BOOL)isSessionDataEmpty;
-(void)updateDoneButton;
-(void)updateFooterPannelView;
-(void)initFooterPannelView;
-(void)resetEmptyTipLabelWithTip:(id)tip;
-(void)updateTableFooterView;
-(void)updateTableView;
-(void)initView;
-(void)initData;
-(void)onBackBtnDone:(id)done;
-(void)viewDidLayoutSubviews;
-(void)viewDidDisappear:(BOOL)view;
-(void)dealloc;
-(void)viewDidLoad;
@end

