/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"
#import "PBMessageObserverDelegate.h"

@protocol ChatMigrationGetConnectInfoDelegate;

@interface ChatMigrationGetConnectInfo : MMObject <PBMessageObserverDelegate> {
	id<ChatMigrationGetConnectInfoDelegate> m_delegate;
}
@property(assign, nonatomic) __weak id<ChatMigrationGetConnectInfoDelegate> m_delegate;
-(void).cxx_destruct;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(void)GetConnectInfo:(id)info;
-(void)dealloc;
-(id)init;
@end

