/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class BaseResponse, NSString;

@interface CheckPayJsapiResponse : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* token;
@property(retain, nonatomic) NSString* errMsg;
@property(assign, nonatomic) int errCode;
@property(retain, nonatomic) BaseResponse* baseResponse;
+(void)initialize;
@end

