/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MessageObserverDelegate.h"
#import "IRsaCertMgrExt.h"

@class MMTimer, NSData, NSString, NSMutableSet, NSObject;
@protocol OS_dispatch_queue, CheckQRCodeLoginDelegate;

@interface CheckQRCodeLoginCGI : XXUnknownSuperclass <MessageObserverDelegate, IRsaCertMgrExt> {
	unsigned long m_checkTime;
	NSString* m_uuid;
	NSData* m_notifyKey;
	id<CheckQRCodeLoginDelegate> m_delegate;
	NSObject<OS_dispatch_queue>* m_workerThread;
	NSMutableSet* m_setQRCodeEventID;
	MMTimer* _m_timer;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) MMTimer* m_timer;
@property(retain, nonatomic) NSMutableSet* m_setQRCodeEventID;
@property(retain, nonatomic) NSObject<OS_dispatch_queue>* m_workerThread;
@property(retain, nonatomic) NSData* m_notifyKey;
@property(retain, nonatomic) NSString* m_uuid;
@property(assign, nonatomic) unsigned long m_checkTime;
@property(assign, nonatomic) __weak id<CheckQRCodeLoginDelegate> m_delegate;
-(void).cxx_destruct;
-(void)MessageReturn:(unsigned long)aReturn MessageInfo:(id)info Event:(unsigned long)event;
-(void)RSAProtobufMessageReturn:(id)aReturn Event:(unsigned long)event;
-(void)checkCodeLoginCancel_OnMainThread;
-(void)checkCodeLoginExpired_OnMainThread;
-(void)checkCodeLoginConfirmed_OnMainThread:(id)thread pwd:(id)pwd nickName:(id)name headImageURL:(id)url;
-(void)checkCodeLoginScaned_OnMainThread:(id)thread nickName:(id)name;
-(void)checkCodeLoginFail_OnMainThread;
-(void)checkCodeLoginUUIDExpired_OnMainThread;
-(void)handleResponse:(id)response withRequest:(id)request eventID:(unsigned long)anId;
-(void)sendCheckQRCodeRequest;
-(void)handleNotifyStatus:(unsigned long)status userName:(id)name nickName:(id)name3 pwd:(id)pwd headImageURL:(id)url;
-(void)handleNotifyData:(id)data;
-(void)stopRequest;
-(void)removeRequestEventID:(unsigned long)anId;
-(BOOL)isLatestRequestEventID:(unsigned long)anId;
-(void)addRequestEventID:(unsigned long)anId;
-(void)stopCheckTimer;
-(void)resetCheckTimer;
-(BOOL)isDataValid;
-(void)clearData;
-(void)internalStopCheckQRCode;
-(void)StopCheckQRCode;
-(void)StartCheckQRCodeWithTime:(unsigned long)time uuid:(id)uuid notifyKey:(id)key;
-(void)dealloc;
-(id)init;
@end

