/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMService.h"
#import "WeChat-Structs.h"
#import "MMService.h"

@class NSDictionary, NSString;

@interface ClassMethodDispatchCenter : MMService <MMService> {
	NSDictionary* m_dictClsMethodObservers;
	NSDictionary* m_dictClsMethodKeyObservers;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(id)getClsMethodKeyObserver:(id)observer withKey:(id)key;
-(id)getClsMethodObservers:(id)observers selector:(SEL)selector;
-(void)unregisterClsMethodKeyObserver:(Class)observer onProtocol:(id)protocol withKey:(id)key;
-(void)unregisterClsMethodObserver:(Class)observer onProtocol:(id)protocol;
-(void)registerClsMethodKeyObserver:(Class)observer onProtocol:(id)protocol withKey:(id)key;
-(void)registerClsMethodObserver:(Class)observer onProtocol:(id)protocol;
-(void)addObserver:(Class)observer toDict:(id)dict methods:(objc_method_description*)methods methodCnt:(unsigned)cnt;
-(void)dealloc;
-(void)onServiceInit;
@end

