/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface ClickCommandRequestInfo : XXUnknownSuperclass {
	NSString* m_magic;
	NSString* m_id;
	NSString* m_key;
	int m_type;
	int m_actionType;
	NSString* m_status;
	NSString* m_content;
}
@property(assign, nonatomic) int m_actionType;
@property(assign, nonatomic) int m_type;
@property(retain, nonatomic) NSString* m_content;
@property(retain, nonatomic) NSString* m_status;
@property(retain, nonatomic) NSString* m_key;
@property(retain, nonatomic) NSString* m_id;
@property(retain, nonatomic) NSString* m_magic;
-(void).cxx_destruct;
-(id)description;
-(id)init;
-(void)dealloc;
@end

