/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"


@interface CMMVector : XXUnknownSuperclass {
	vector<__unsafe_unretained id, std::__1::allocator<__unsafe_unretained id> > m_vecObject;
}
-(id).cxx_construct;
-(void).cxx_destruct;
-(void)dealloc;
-(id)at:(unsigned long)at;
-(unsigned long)count;
-(void)removeAllObjects;
-(BOOL)containsObject:(id)object;
-(BOOL)removeObject:(id)object;
-(void)addObject:(id)object;
-(id)init;
@end

