/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMService.h"
#import "MMService.h"

@class NSString;
@protocol NetworkStatusDelegate;

@interface CNetworkStatus : MMService <MMService> {
	unsigned long m_uiLastStatus;
	id<NetworkStatusDelegate> m_delNetworkStatus;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(void)GetWifiInfo:(id*)info BSSID:(id*)bssid;
+(BOOL)isSimCard4G;
+(BOOL)isSimCardSupport3GPlus;
+(id)getSimCardType;
+(id)getCarrierName;
+(id)GetCarrier;
+(void)GetCTNetworkInfo;
+(id)descriptionForNetType:(int)netType;
-(BOOL)isOnWifiOrOver2G;
-(BOOL)isReachable;
-(unsigned long)getNewNetType;
-(int)getNetworkType;
-(BOOL)isOnWifi;
-(BOOL)isOnWWan;
-(void)ChangeReach;
-(void)Stop;
-(void)Start:(id)start;
-(void)PingReach;
-(void)dealloc;
-(id)init;
@end

