/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NSMutableArray, NSString;

@interface ConnectInfoAddr : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSMutableArray* port;
@property(retain, nonatomic) NSString* ip;
+(void)initialize;
@end

