/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"
#import "PBMessageObserverDelegate.h"


@interface ContactRemarkLogic : MMObject <PBMessageObserverDelegate> {
}
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(BOOL)deleteCardImg:(id)img;
-(void)onUploadCardImg:(id)img;
-(BOOL)uploadCardImg:(id)img image:(id)image clientId:(id)anId startPos:(unsigned long)pos;
-(BOOL)uploadCardImg:(id)img image:(id)image;
-(void)onDownloadCardImg:(id)img;
-(void)downloadCardImg:(id)img;
-(void)tryDeleteInvalidateCardImg:(id)img;
-(id)getCardImg:(id)img;
-(id)pathForCardImage:(id)cardImage url:(id)url;
-(id)listCardImgFile;
-(void)dealloc;
@end

