/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface COOBData : XXUnknownSuperclass {
	unsigned long m_uiType;
	unsigned long m_uiTime;
	NSString* m_nsIPPort;
}
@property(retain, nonatomic) NSString* m_nsIPPort;
@property(assign, nonatomic) unsigned long m_uiTime;
@property(assign, nonatomic) unsigned long m_uiType;
-(void).cxx_destruct;
-(void)LoadDataFromOOBData:(id)oobdata;
-(id)init;
@end

