/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface CPKeyIncreaseInfo : XXUnknownSuperclass {
	NSString* _cpKey;
	unsigned long _threadId;
}
@property(assign, nonatomic) unsigned long threadId;
@property(retain, nonatomic) NSString* cpKey;
-(void).cxx_destruct;
@end

