/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class CMessageWrap;

@interface CUploadVideoInfo : XXUnknownSuperclass {
	unsigned long m_uiUploadCount;
	unsigned long m_uiCurOffset;
	unsigned long m_uiCurOffsetCount;
	unsigned long m_uiZeroUploadCount;
	CMessageWrap* m_wrapMsg;
	unsigned long long m_ui64StartTime;
	unsigned long m_uiOpType;
	long m_nRetCode;
}
@property(assign, nonatomic) long m_nRetCode;
@property(assign, nonatomic) unsigned long m_uiOpType;
@property(assign, nonatomic) unsigned long long m_ui64StartTime;
@property(retain, nonatomic) CMessageWrap* m_wrapMsg;
@property(assign, nonatomic) unsigned long m_uiZeroUploadCount;
@property(assign, nonatomic) unsigned long m_uiCurOffsetCount;
@property(assign, nonatomic) unsigned long m_uiCurOffset;
@property(assign, nonatomic) unsigned long m_uiUploadCount;
-(void).cxx_destruct;
-(id)GetStatInfo;
-(id)description;
-(id)init;
@end

