/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMService.h"
#import "MMService.h"

@class NSString, NSMutableDictionary;

@interface EmoticonWebDownloadMgr : MMService <MMService> {
	NSMutableDictionary* m_downloadQueue;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableDictionary* m_downloadQueue;
-(void).cxx_destruct;
-(BOOL)cancelDownloadEmoticon:(id)emoticon ThumbUrl:(id)url;
-(BOOL)downloadEmoticon:(id)emoticon withUserData:(id)userData;
-(BOOL)isEmoticonExist:(id)exist;
-(void)connection:(id)connection didFailWithError:(id)error;
-(void)connectionDidFinishLoading:(id)connection;
-(id)thumbForImageData:(id)imageData;
-(void)connection:(id)connection didReceiveData:(id)data;
-(void)connection:(id)connection didReceiveResponse:(id)response;
-(id)infoForUrlConnnection:(id)urlConnnection;
-(id)downloadTempPathForUrl:(id)url;
-(id)cachePathForUrl:(id)url;
-(id)hashForUrl:(id)url;
-(id)cacheRootPath;
-(void)dealloc;
-(id)init;
-(void)onServiceInit;
@end

