/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCActionSheetDelegate.h"
#import "IEmoticonMgrExt.h"
#import "EmoticonCustomManageViewDelegate.h"
#import "CustomEmoticonSynchronizeViewDelegate.h"
#import "WeChat-Structs.h"
#import "CustomEmoticonConflictViewDelegate.h"
#import "MMImagePickerManagerDelegate.h"
#import "MMUIViewController.h"
#import "EmoticonBackUpMgrExt.h"
#import "UITableViewDelegate.h"
#import "EmoticonBackUpMgrViewExt.h"
#import "UITableViewDataSource.h"
#import "EmoticonBackupOperateMgrExt.h"

@class UILabel, UIView, NSString, EmoticonCustomManageDataLogic, MMTableView, UIButton;

@interface EmoticonCustomManageViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, EmoticonCustomManageViewDelegate, IEmoticonMgrExt, MMImagePickerManagerDelegate, EmoticonBackupOperateMgrExt, EmoticonBackUpMgrExt, EmoticonBackUpMgrViewExt, WCActionSheetDelegate, CustomEmoticonSynchronizeViewDelegate, CustomEmoticonConflictViewDelegate> {
	BOOL m_isDeleteMode;
	MMTableView* m_tableView;
	EmoticonCustomManageDataLogic* m_dataLogic;
	UIView* m_bottomBar;
	UIButton* m_deleteButton;
	UIView* m_headerSyncView;
	UILabel* m_bottomLabel;
	UIButton* m_editButton;
	unsigned _m_localEmoticonLimit;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned m_localEmoticonLimit;
@property(assign, nonatomic) BOOL m_isDeleteMode;
@property(retain, nonatomic) UIButton* m_editButton;
@property(retain, nonatomic) UILabel* m_bottomLabel;
@property(retain, nonatomic) UIView* m_headerSyncView;
@property(retain, nonatomic) UIButton* m_deleteButton;
@property(retain, nonatomic) UIView* m_bottomBar;
@property(retain, nonatomic) EmoticonCustomManageDataLogic* m_dataLogic;
@property(retain, nonatomic) MMTableView* m_tableView;
-(void).cxx_destruct;
-(void)checkIfIsOnEmoticonCustomManageViewController:(BOOL*)controller;
-(void)onCustomEmoticonConflictViewClickClose;
-(void)showHeaderViewWithoutWiFi;
-(void)hideHeaderViewOnWiFi;
-(void)onCustomEmoticonSynchronizeViewClickEdit;
-(void)onCustomEmoticonSynchronizeViewClickClose;
-(void)onEmoticonBackUpMgrRecoverAutoPauseOnWWan;
-(void)onEmoticonBackUpMgrRecoverNetworkChangeToUnreachable;
-(void)onEmoticonBackUpMgrRecoverGoon;
-(void)onEmoticonBackUpMgrRecoverPause;
-(void)onEmoticonBackUpMgrRecoverFailed;
-(void)onEmoticonBackUpMgrSyncOperate;
-(void)onEmoticonBackUpMgrRecoverComplete;
-(void)onEmoticonBackUpMgrRecoverOneEmoticon;
-(void)onDeleteBackupEmoticonFailed:(id)failed;
-(void)onDeleteBackupEmoticonOK:(id)ok;
-(void)MMImagePickerManagerDidCancel:(id)mmimagePickerManager;
-(void)MMImagePickerManager:(id)manager didFinishPickingImageWithInfo:(id)info;
-(void)OnUpdateEmoticonList;
-(void)onEmoticonCustomManageViewTaped:(id)taped andView:(id)view;
-(id)tableView:(id)view viewForFooterInSection:(int)section;
-(float)tableView:(id)view heightForFooterInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)deleteEmoticonFromServer;
-(void)deleteEmoticon:(id)emoticon;
-(void)updateBottomDeleteButton;
-(BOOL)hasAnyEmoticonMarked;
-(void)onDeleteEmoticonConfirm:(id)confirm;
-(void)onAddCustomEmoticon;
-(void)changeToRecoveringMode;
-(void)onClickEdit;
-(void)changeToNormalMode;
-(void)changeToDeleteMode;
-(void)closeSyncView:(id)view;
-(void)reloadData;
-(void)initData;
-(void)OnCancelModalView:(id)view;
-(void)BackButtonDown:(id)down;
-(int)getCellContentViewTag;
-(float)BottomBarHeight;
-(float)GridViewItemWidth;
-(void)initTableView;
-(void)initNavigationItem;
-(void)initBottomBarView;
-(void)initBackground;
-(void)initSyncView;
-(void)initView;
-(void)didReceiveMemoryWarning;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(id)init;
-(void)dealloc;
@end

