/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMUIView.h"

@class NSMutableArray;

@interface EmoticonCustomManageCell : MMUIView {
	NSMutableArray* m_wrapArray;
	NSMutableArray* m_viewArray;
}
@property(retain, nonatomic) NSMutableArray* m_viewArray;
@property(retain, nonatomic) NSMutableArray* m_wrapArray;
-(void).cxx_destruct;
-(void)setEmoticonWrapArray:(id)array andWidth:(float)width andDelegate:(id)delegate;
-(void)dealloc;
@end

