/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMService.h"
#import "EmoticonOperateCgiDelegate.h"
#import "EmoticonAddToServerLogicDelegate.h"
#import "MMService.h"

@class EmoticonOperateCgi, NSMutableArray, NSString;

@interface EmoticonBackupOperateMgr : MMService <EmoticonOperateCgiDelegate, EmoticonAddToServerLogicDelegate, MMService> {
	EmoticonOperateCgi* m_deleteCgi;
	NSMutableArray* m_addLogicList;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableArray* m_addLogicList;
@property(retain, nonatomic) EmoticonOperateCgi* m_deleteCgi;
-(void).cxx_destruct;
-(void)onEmoticonAddToServerFailed:(id)serverFailed isOverLimit:(BOOL)limit;
-(void)onEmoticonAddToServerOk:(id)serverOk;
-(void)onEmoticonOperateFailed:(id)failed isDeleteMode:(BOOL)mode isOverLimit:(BOOL)limit;
-(void)onEmoticonOperateOk:(id)ok WithNeedBackupArray:(id)needBackupArray isDeleteMode:(BOOL)mode;
-(void)addBackupEmoticonToServer:(id)server;
-(void)deleteBackupEmoticonFromServer:(id)server;
-(void)dealloc;
@end

