/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMTipsViewControllerDelegate.h"
#import "MMObject.h"
#import "EmoticonBackupOperateMgrExt.h"
#import "StoreEmotionExchangeEmotionPackCgiDelegate.h"

@class AddEmoticonWrap, StoreEmotionExchangeEmotionPackCgi, MMToastViewController, NSString;
@protocol EmoticonCustomManageAddLogicDelegate, MMUIViewControllerDelegate;

@interface EmoticonCustomManageAddLogic : MMObject <MMTipsViewControllerDelegate, StoreEmotionExchangeEmotionPackCgiDelegate, EmoticonBackupOperateMgrExt> {
	BOOL m_isAdding;
	BOOL m_isExchanging;
	AddEmoticonWrap* m_emoticonWrap;
	MMToastViewController* m_toastView;
	StoreEmotionExchangeEmotionPackCgi* m_exchangePackCgi;
	id<EmoticonCustomManageAddLogicDelegate, MMUIViewControllerDelegate> _delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<EmoticonCustomManageAddLogicDelegate, MMUIViewControllerDelegate> delegate;
@property(readonly, assign, nonatomic) BOOL isAdding;
+(id)extInfoForAppid:(id)appid DesignerId:(id)anId thumbImgUrl:(id)url;
+(id)typeNumberForImageData:(id)imageData;
-(void).cxx_destruct;
-(void)onAddBackupEmoticonFailed:(id)failed isOverLimit:(BOOL)limit;
-(void)onAddBackupEmoticonOK:(id)ok;
-(void)onClickTipsBtn:(id)btn Index:(int)index;
-(void)onExchangeEmotionPackCgiFailedWithPid:(id)pid AndRet:(int)ret;
-(void)onExchangeEmotionPackCgiFailedForNoResponseWithPid:(id)pid;
-(void)onExchangeEmotionPackCgiOkWithPid:(id)pid DownloadInfo:(id)info;
-(void)trySaveThumbImage;
-(void)tryDownloadThumbImage;
-(void)showComfirmTipsWithWording:(id)wording;
-(void)showExtendLimitTipsWithWording:(id)wording;
-(void)showSavedTips;
-(BOOL)startAddEmoticonWithWrap:(id)wrap NeedCheckTotalCountLimit:(BOOL)limit;
-(BOOL)startExchangePackAndAddEmoticonWithWrap:(id)wrap;
-(BOOL)startAddEmoticonWithWrap:(id)wrap;
-(BOOL)checkTotalCountLimit;
-(id)init;
-(void)dealloc;
@end

