/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface ExtDeviceLoginConfirmExpiredRet : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* buttonStr;
@property(retain, nonatomic) NSString* contentStr;
@property(assign, nonatomic) unsigned iconType;
+(void)initialize;
@end

