/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMUIViewController.h"
#import "UITableViewDelegate.h"
#import "tableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "IFavoritesExt.h"
#import "FavTagViewDelegate.h"

@class FavDetailTagsView, FavoritesItem, FavDetailUpdateTimeView, NSString, MMTableView;

@interface FavBaseDetailViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, tableViewDelegate, IFavoritesExt, FavTagViewDelegate> {
	MMTableView* m_tableView;
	FavDetailTagsView* m_tagsView;
	FavDetailUpdateTimeView* m_updateTimeView;
	FavoritesItem* m_favItem;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)onFavTagEditOK;
-(void)onFavTagEditBegin:(int)begin;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)genAddTime:(id)time indexPath:(id)path;
-(void)genTagsView:(id)view indexPath:(id)path;
-(void)genHeadCell:(id)cell indexPath:(id)path;
-(void)genContent:(id)content indexPath:(id)path;
-(float)getHeightForRowAtIndexPath:(id)indexPath;
-(int)getRowsInContentSection;
-(void)onAction:(id)action;
-(void)initTableView;
-(void)initNavigationBar;
-(void)didReceiveMemoryWarning;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithFavItem:(id)favItem;
@end

