/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FavFileDetailDelegate <NSObject>
@optional
-(void)OpenVideoFileByFavDataWrap:(id)wrap;
-(void)OpenVideoFile:(id)file;
@end

