/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "IFavoritesExt.h"
#import "MMUIImageView.h"

@class UIView, NSString, UIImageView;
@protocol FavImagePreViewDelegate, RecordNodeDataSource;

@interface FavImagePreView : MMUIImageView <IFavoritesExt> {
	UIView* m_maskView;
	UIImageView* m_imgPreView;
	NSString* m_imageLocalPath;
	unsigned long imageDataSize;
	MMUIImageView* m_imgvBack;
	MMUIImageView* m_imgvFront;
	unsigned long m_progressLength;
	BOOL m_bIsImageExit;
	BOOL m_bIsSourceImg;
	BOOL m_bIsLongPressHandled;
	id<FavImagePreViewDelegate> m_delegate;
	id<RecordNodeDataSource> dataSource;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* m_imageLocalPath;
@property(assign, nonatomic) __weak id<FavImagePreViewDelegate> m_delegate;
@property(retain, nonatomic) id<RecordNodeDataSource> dataSource;
+(CGSize)GetPreSizeByRecordDataSource:(id)source maxWidth:(float)width;
+(CGSize)GetPreSizeByRecordDataSource:(id)source;
-(void).cxx_destruct;
-(void)OnDownloadFavoritesItem:(id)item LocalDataId:(id)anId FinishedLength:(long)length TotalLength:(long)length4;
-(void)OnFavoritesItemDownloadFinished:(id)finished ErrCode:(int)code;
-(void)touchesCancelled:(id)cancelled withEvent:(id)event;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)updateProgressFinishedLength:(long)length TotalLength:(long)length2;
-(void)initProgressView;
-(void)startDownloadFavItem;
-(void)startLoadImageWithGCD;
-(id)compressImage:(id)image;
-(void)hideMaskView;
-(void)showMaskView;
-(void)onClickFavImage;
-(void)windowHide:(id)hide;
-(void)OnLongPressFavImage;
-(void)onTouchCancel;
-(void)onLongTouch;
-(void)onTouchUpInside;
-(void)onTouchDownRepeat;
-(void)onBeginLongPress;
-(void)pressedEvents;
-(void)LongPressEvents;
-(void)initData;
-(void)startLoadImageWithMaxWidth:(float)maxWidth;
-(void)startLoadImage;
-(id)initWithDataSource:(id)dataSource;
-(void)dealloc;
@end

