/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol FavoritesDownloadMgrDelegate <NSObject>
@optional
-(void)onDownloadFavoritesItemFail:(id)fail LocalDataId:(id)anId;
-(void)onDownloadFavoritesItemOK:(id)ok LocalDataId:(id)anId;
-(void)onDownloadFavoritesItem:(id)item LocalDataId:(id)anId FinishedLength:(long)length TotalLength:(long)length4;
-(void)onDownloadFavoritesItemFinished:(id)finished ErrCode:(int)code;
@end

