/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "RichTextLayoutDelegate.h"
#import "WeChat-Structs.h"
#import "FavRecordBaseNodeView.h"
#import "ILinkEventExt.h"

@class RichTextView, NSString;

@interface FavRecordTextNodeView : FavRecordBaseNodeView <RichTextLayoutDelegate, ILinkEventExt> {
	RichTextView* m_textDescLabel;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(BOOL)shouldOpenNewLineAtY:(float)y withLineHeight:(float)lineHeight richTextView:(id)view;
-(void)updateBkgImage:(BOOL)image;
-(void)hideMenu;
-(void)showMenu;
-(void)onCopy:(id)copy;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(BOOL)canBecomeFirstResponder;
-(void)onMenuControllerWillHide:(id)onMenuController;
-(void)onTouchCancel;
-(void)onLongTouch;
-(void)onTouchUpInside;
-(void)addContentSubView;
-(void)layoutSubviews;
-(void)dealloc;
@end

