/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "FavImagePreViewDelegate.h"
#import "FavRecordBaseNodeView.h"

@class FavImagePreView, NSString;

@interface FavRecordImgNodeView : FavRecordBaseNodeView <FavImagePreViewDelegate> {
	FavImagePreView* m_imgPreView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) FavImagePreView* m_imgPreView;
-(void).cxx_destruct;
-(void)onWillLongPressFavPreImage:(id)on;
-(void)onLongPressedFavPreImage:(id)image;
-(void)onClickFavPreImage:(id)image ImageIndex:(unsigned long)index;
-(void)addContentSubView;
@end

