/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCActionSheetDelegate.h"
#import "WeChat-Structs.h"
#import "FavBaseDetailViewController.h"
#import "FavForwardLogicDelegate.h"
#import "FavSightViewDelegate.h"
#import "FavVideoDetailDelegate.h"

@class FavForwardLogicController, NSString, FavSightView;

@interface FavSightDetailViewController : FavBaseDetailViewController <WCActionSheetDelegate, FavForwardLogicDelegate, FavSightViewDelegate, FavVideoDetailDelegate> {
	FavForwardLogicController* m_favForwardController;
	FavSightView* m_sightView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)OnFavoritesItemDownloadFinished:(id)finished ErrCode:(int)code;
-(void)OnDownloadFavoritesItem:(id)item LocalDataId:(id)anId FinishedLength:(long)length TotalLength:(long)length4;
-(void)onJumpToViewDetail:(id)viewDetail;
-(void)jumpToDetail:(id)detail;
-(void)onExitFullScreen;
-(void)OpenVideoFavItem:(id)item;
-(void)openVideoDetail;
-(void)restartDownload;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)onAction:(id)action;
-(id)getFavForawrdViewController;
-(void)initSightView;
-(void)genContent:(id)content indexPath:(id)path;
-(float)getHeightForRowAtIndexPath:(id)indexPath;
-(int)getRowsInContentSection;
@end

