/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"


@interface FBSDKSettings : XXUnknownSuperclass {
}
+(id)graphAPIDebugParamValue;
+(void)updateGraphAPIDebugBehavior;
+(FBSDKAccessTokenCacheV4*)accessTokenCache;
+(id)sdkVersion;
+(id)legacyUserDefaultTokenInformationKeyName;
+(void)setLegacyUserDefaultTokenInformationKeyName:(id)name;
+(void)disableLoggingBehavior:(id)behavior;
+(void)enableLoggingBehavior:(id)behavior;
+(void)setLoggingBehavior:(id)behavior;
+(id)loggingBehavior;
+(void)setLimitEventAndDataUsage:(BOOL)usage;
+(BOOL)limitEventAndDataUsage;
+(void)setJPEGCompressionQuality:(float)quality;
+(float)JPEGCompressionQuality;
+(void)_setJPEGCompressionQualityNumber:(id)number;
+(id)_JPEGCompressionQualityNumber;
+(void)setFacebookDomainPart:(id)part;
+(id)facebookDomainPart;
+(void)setDisplayName:(id)name;
+(id)displayName;
+(void)setClientToken:(id)token;
+(id)clientToken;
+(void)setAppURLSchemeSuffix:(id)suffix;
+(id)appURLSchemeSuffix;
+(void)setAppID:(id)anId;
+(id)appID;
+(void)initialize;
-(void)setAccessTokenCache:(FBSDKAccessTokenCacheV4*)cache;
-(id)init;
@end

