/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"


@interface FBSDKDynamicFrameworkLoader : XXUnknownSuperclass {
}
+(void*)loadkSecClass;
+(void*)loadkSecReturnData;
+(void*)loadkSecMatchLimit;
+(void*)loadkSecMatchLimitOne;
+(void*)loadkSecAttrAccessGroup;
+(void*)loadkSecClassGenericPassword;
+(void*)loadkSecValueData;
+(void*)loadkSecAttrGeneric;
+(void*)loadkSecAttrService;
+(void*)loadkSecAttrAccount;
+(void*)loadkSecAttrAccessibleAfterFirstUnlockThisDeviceOnly;
+(void*)loadkSecAttrAccessible;
+(SecRandom*)loadkSecRandomDefault;
-(id)init;
@end

