/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, UIActivityIndicatorView, StrokeView, UIColor, NSString, UIImageView, UILabel;

@interface FrameTextBtn : XXUnknownSuperclass {
	UILabel* m_label;
	UIImageView* m_imageView;
	StrokeView* m_stroke;
	UIActivityIndicatorView* m_indicator;
	BOOL m_init;
	BOOL _active;
	BOOL _progressing;
	BOOL _trigged;
	UIColor* _frameColor;
	UIColor* _fillColorActive;
	UIColor* _fillColor;
	UIColor* _textColorActive;
	UIColor* _textColor;
	NSString* _title;
	UIImage* _image;
	UIImage* _imageActive;
}
@property(assign, nonatomic) BOOL trigged;
@property(assign, nonatomic) BOOL progressing;
@property(assign, nonatomic) BOOL active;
@property(retain, nonatomic) UIImage* imageActive;
@property(retain, nonatomic) UIImage* image;
@property(assign, nonatomic) NSString* title;
@property(retain, nonatomic) UIColor* textColor;
@property(retain, nonatomic) UIColor* textColorActive;
@property(retain, nonatomic) UIColor* fillColor;
@property(retain, nonatomic) UIColor* fillColorActive;
@property(assign, nonatomic) UIColor* frameColor;
-(void).cxx_destruct;
-(void)calculateWidth;
-(void)initView;
-(void)dealloc;
-(id)init;
@end

