/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "IMMLanguageMgrExt.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "IGameCenterExt.h"
#import "MMKernelExt.h"
#import "MMPackageDownloadMgrExt.h"

@class NSMutableArray, NSArray, NSString, NSMutableDictionary, Package;

@interface FTSMemorySearchMgr : XXUnknownSuperclass <IMMLanguageMgrExt, MMKernelExt, MMPackageDownloadMgrExt, IGameCenterExt> {
	BOOL _hasInited;
	BOOL _isLocalGameCacheUpdating;
	unsigned long long _gameCacheModifyTime;
	NSString* _lastQueryText;
	NSString* _newestQueryText;
	NSMutableArray* _arrLastQueryKeywords;
	NSMutableDictionary* _dicSearchMatchTip;
	NSMutableArray* _arrFeatureResultItem;
	NSMutableDictionary* _dicSourceFeatureSearchItem;
	unsigned long _curFeatureListVersion;
	unsigned long _lastCheckPackageTime;
	Package* _downloadingPackage;
	NSMutableArray* _arrWCGameAllItem;
	NSMutableArray* _arrWCGameResultItem;
	NSMutableArray* _arrDetailPageWCGameResultItem;
	NSString* _newestDetailPageQueryText;
	NSString* _lastDetailPageQueryText;
	NSMutableArray* _arrDetailPageLastQueryKeywords;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableArray* arrDetailPageLastQueryKeywords;
@property(retain, nonatomic) NSString* lastDetailPageQueryText;
@property(retain, nonatomic) NSString* newestDetailPageQueryText;
@property(retain, nonatomic) NSArray* arrLastQueryKeywords;
@property(retain, nonatomic) NSString* newestQueryText;
@property(retain, nonatomic) NSString* lastQueryText;
-(void).cxx_destruct;
-(void)onGetAllGameList:(id)list error:(int)error;
-(unsigned long long)getGameCachedModifiedTime;
-(BOOL)shouldUpdateGameCache;
-(void)tryAsyncUpdateLocalGameCache;
-(void)onPackageDownloadFinish:(id)finish package:(id)package;
-(void)onPackageListUpdated:(id)updated;
-(void)updateVersion:(unsigned long)version;
-(unsigned long)getCurrenPackageVersion;
-(id)getFeatureIcon:(unsigned long)icon;
-(id)getFeatureListFilePath:(id)path;
-(id)getFeatureListVersionFile;
-(id)getFeatureListTempZipPayloadPath;
-(id)getFeatureListZipPayloadPath;
-(id)getFeatureListPackageZipFile;
-(id)getFeatureListPackageRootPath;
-(void)onAuthOK;
-(void)delayCheckUpdate;
-(void)doCheckUpdate;
-(id)getPackageKey;
-(void)onLanguageChange;
-(id)getSearchItemForGameDetailPage:(id)gameDetailPage index:(unsigned)index;
-(id)getSearchItemsForGameDetailPage:(id)gameDetailPage;
-(BOOL)hasSearchDoneForGameDetailPage:(id)gameDetailPage;
-(unsigned long long)getGameDetailSearchItemCount:(id)count;
-(BOOL)hasGameSearchResult:(id)result;
-(void)cancelSearchForGameDetailPage;
-(void)asyncSearchTextForGameDetailPage:(id)gameDetailPage;
-(id)getWCGameItem:(id)item index:(unsigned)index;
-(id)getMatchTip:(id)tip featureID:(unsigned long)anId;
-(id)getFeatureItem:(id)item index:(unsigned)index;
-(unsigned long long)getWCGameSearchItemCount:(id)count;
-(unsigned long long)getFeatureSearchItemCount:(id)count;
-(BOOL)hasWCGameSearchResult:(id)result;
-(BOOL)hasFeatureSearchResult:(id)result;
-(BOOL)hasSearchDone:(id)done;
-(void)cancelSearch;
-(void)asyncSearchText:(id)text;
-(void)doSearch:(id)search;
-(void)sortFeatures:(id)features matchTips:(id)tips;
-(id)getSourceSearchItem;
-(id)createWeSportSearchItem;
-(void)initFeatureItem;
-(void)initSearchItem;
-(void)asyncInitFeatureItem;
-(void)asyncInitSearchItem;
-(id)loadSearchItem:(id)item;
-(id)convertFeatureItem:(id)item;
-(void)doInitWorker;
-(void)dealloc;
-(id)init;
@end

