/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCCommentDetailViewControllerFBDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"
#import "UISearchBarDelegate.h"
#import "WSMusicDelegate.h"
#import "UIScrollViewDelegate.h"
#import "FTSJSEventDelegate.h"
#import "FTSWebSearchDataSource.h"
#import "INewABTestMgrExt.h"
#import "UIWebViewDelegate.h"

@class UIView, WebSearchView, UIImageView, NSString, MMUIViewController, MMUISearchBar, NSMutableArray, WSResultViewLogic, UITextField;
@protocol FTSWebSearchViewDelegate;

@interface FTSWebSearchController : XXUnknownSuperclass <UISearchBarDelegate, UIWebViewDelegate, UIScrollViewDelegate, WCCommentDetailViewControllerFBDelegate, FTSJSEventDelegate, FTSWebSearchDataSource, INewABTestMgrExt, WSMusicDelegate> {
	MMUISearchBar* _searchBar;
	WebSearchView* _mainView;
	WebSearchView* _detailView;
	WSResultViewLogic* _resultViewLogic;
	UIImageView* _searchBarWrap;
	UIImageView* _bottomViewShadow;
	BOOL _hasMoving;
	float _moveStartOffset;
	float _moveCurOffset;
	float _moveContentOffsetY;
	float _searchTextFieldNormalWidth;
	CGSize _searchIconDefaultSize;
	BOOL _isDetailSearch;
	unsigned long long _detailSearchType;
	NSString* _keywordForHomepage;
	NSString* _keywordForDetailPage;
	NSString* _searchID;
	NSString* _browsingTID;
	NSMutableArray* _arrDeletedTID;
	BOOL _bSwizzle;
	int _guideType;
	UIView* _view;
	UIView* _searchBarSuperView;
	UIView* _bottomView;
	MMUIViewController* _viewController;
	id<FTSWebSearchViewDelegate> _delegate;
	int _mode;
	UITextField* _searchTextField;
	UIImageView* _searchLeftView;
	UIView* _searchPromtLabel;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIView* searchPromtLabel;
@property(retain, nonatomic) UIImageView* searchLeftView;
@property(retain, nonatomic) UITextField* searchTextField;
@property(assign, nonatomic) int mode;
@property(assign, nonatomic) __weak id<FTSWebSearchViewDelegate> delegate;
@property(assign, nonatomic) __weak MMUIViewController* viewController;
@property(retain, nonatomic) UIView* bottomView;
@property(retain, nonatomic) UIView* searchBarSuperView;
@property(retain, nonatomic) UIView* view;
-(void).cxx_destruct;
-(void)notifyPageOfMusicStatusChanged:(id)musicStatusChanged;
-(void)keyboardDidHide:(id)keyboard;
-(void)onClickRecmdWord:(id)word;
-(void)onOpenContact:(id)contact;
-(void)onOpenSnsDetail:(id)detail;
-(void)onOpenMsgSession:(id)session;
-(void)onOpenBrandContact:(id)contact withParams:(id)params;
-(void)onLaunchPage:(id)page withParams:(id)params;
-(void)onLaunchDetailPage:(id)page;
-(void)onPreSearch:(id)search;
-(void)onSearchInputChanged:(id)changed;
-(void)onFailReceiveJson;
-(void)onReceiveJson:(id)json;
-(void)onDeleteData;
-(unsigned long long)businessType;
-(id)query;
-(void)searchBarCancelButtonClicked:(id)clicked;
-(void)searchBarSearchButtonClicked:(id)clicked;
-(void)searchBar:(id)bar textDidChange:(id)text;
-(BOOL)searchBar:(id)bar shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
-(void)searchBarTextDidBeginEditing:(id)searchBarText;
-(void)onClickSearchButton:(id)button;
-(void)cancelSearch;
-(void)resetSearch;
-(void)asyncSearch:(id)search;
-(void)setSearchBarText:(id)text;
-(void)notifyPageOfSearchClick:(id)searchClick;
-(void)notifyPageOfQueryChanged:(id)queryChanged;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)enableButton:(id)button;
-(void)willBeginDetailSearch;
-(id)urlParmasForVSPage;
-(id)urlParmasForDetailPage:(id)detailPage;
-(id)urlParmasForMainPage:(id)mainPage;
-(void)loadLocalHtmlForVertSearch;
-(void)loadLocalHtmlForDetailPage:(id)detailPage;
-(void)loadLocalHtml:(id)html;
-(void)resetSearchIconFrame;
-(void)removeAllAnimation:(id)animation;
-(void)show;
-(void)hideKeyboard;
-(void)onBackBtnClick;
-(void)remove;
-(void)popWithAnimation;
-(void)popFromDetailSearch;
-(void)onRemoveDetailView;
-(void)pop:(BOOL)pop;
-(float)getSearchTextFieldWidth;
-(void)updateMovingDetailView;
-(void)updateSearchBarPosition;
-(void)moveDetailViewToRight;
-(void)moveWebViewToRight;
-(void)cancelMoveDetailView;
-(void)cancelMoveSearchBar;
-(void)handlePanGestureForDetailView:(id)detailView;
-(void)handlePanGesture:(id)gesture;
-(BOOL)isSupportRUBrandContact;
-(BOOL)isSupportSuggestion;
-(BOOL)isSubClassSearch;
-(BOOL)isVerticalSearch;
-(void)internalSwizzle;
-(void)clearResource;
-(void)handleRotateEvent;
-(void)unswizzle;
-(void)swizzle;
-(void)initDetailView;
-(void)initResultView;
-(void)initMusicSearchDelegate;
-(void)initView;
-(void)dealloc;
-(id)initWithMode:(int)mode businessType:(unsigned long long)type;
-(id)init;
@end

