/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "GameCenterSearchBaseCell.h"


@interface GameCenterSearchRecommendCell : GameCenterSearchBaseCell {
}
+(void)loadSubviews:(id)subviews recommendItem:(id)item;
+(float)calCellHeight:(id)height;
@end

