/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMTableViewCell.h"
#import "RichTextLayoutDelegate.h"

@class NSString;

@interface GameCenterSearchBaseCell : MMTableViewCell <RichTextLayoutDelegate> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(BOOL)shouldOpenNewLineAtY:(float)y withLineHeight:(float)lineHeight richTextView:(id)view;
+(id)ReplaceTag:(id)tag;
+(id)replaceTag:(id)tag;
@end

