/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class BaseRequest, NSString;

@interface GenPrepayRequest : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* extInfo;
@property(assign, nonatomic) int channel;
@property(retain, nonatomic) NSString* contactAppUsername;
@property(retain, nonatomic) NSString* webViewUrl;
@property(retain, nonatomic) NSString* signType;
@property(retain, nonatomic) NSString* sign;
@property(retain, nonatomic) NSString* package;
@property(retain, nonatomic) NSString* timestamp;
@property(retain, nonatomic) NSString* nonceStr;
@property(retain, nonatomic) NSString* appId;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

