/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class BaseRequest, NSString;

@interface GetCardsLayoutRequest : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* layoutBuff;
@property(assign, nonatomic) unsigned scene;
@property(assign, nonatomic) double longitude;
@property(assign, nonatomic) double latitude;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

