/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"

@class UIToolbar;

@interface GKImageCropOverlayView : XXUnknownSuperclass {
	UIToolbar* toolbar;
	CGSize cropSize;
}
@property(retain, nonatomic) UIToolbar* toolbar;
@property(assign, nonatomic) CGSize cropSize;
-(void).cxx_destruct;
-(void)drawRect:(CGRect)rect;
-(id)initWithFrame:(CGRect)frame;
@end

