/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "PBCoding.h"

@class NSMutableArray, NSString;

@interface GoogleContact : XXUnknownSuperclass <PBCoding> {
	BOOL isInMyContactList;
	BOOL isOnlyInOtherContact;
	NSString* googleId;
	NSString* nickName;
	NSString* gmail;
	unsigned long sex;
	NSString* wxUsrname;
	NSString* wxNickname;
	NSString* headImgUrl;
	NSString* headHDImgUrl;
	NSString* googleImageUrl;
	NSMutableArray* emailList;
	NSString* m_nsAntispamTicket;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* m_nsAntispamTicket;
@property(assign, nonatomic) BOOL isOnlyInOtherContact;
@property(retain, nonatomic) NSMutableArray* emailList;
@property(retain, nonatomic) NSString* googleImageUrl;
@property(retain, nonatomic) NSString* headHDImgUrl;
@property(retain, nonatomic) NSString* headImgUrl;
@property(retain, nonatomic) NSString* wxNickname;
@property(retain, nonatomic) NSString* wxUsrname;
@property(assign, nonatomic) BOOL isInMyContactList;
@property(assign, nonatomic) unsigned long sex;
@property(retain, nonatomic) NSString* gmail;
@property(retain, nonatomic) NSString* nickName;
@property(retain, nonatomic) NSString* googleId;
+(void)initialize;
-(void).cxx_destruct;
-(id)getDisplayContactDataFromGContactAndDB;
-(int)compareGoogleContactsAscending:(id)ascending;
-(void)dealloc;
-(id)init;
-(const map<unsigned long, unsigned long, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, unsigned long> > >*)getValueTagIndexMap;
-(id)getValueTypeTable;
@end

