/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMUIWindow.h"

@class UIWindow, UITextField, UIButton, UIImageView;
@protocol GraphicVerifyWindowDelegate;

@interface GraphicVerifyWindow : MMUIWindow {
	UIImageView* m_codeImageView;
	UIButton* m_changeImgBtn;
	UIButton* m_verifyBtn;
	UIButton* m_cancelBtn;
	UITextField* m_textFieldCode;
	id<GraphicVerifyWindowDelegate> m_delegate;
	UIWindow* oldKeyWindow;
}
@property(retain, nonatomic) UIImageView* m_codeImageView;
@property(retain, nonatomic) UIWindow* oldKeyWindow;
-(void).cxx_destruct;
-(void)resignKeyWindow;
-(void)makeKeyAndVisible;
-(void)textFieldDidEndOnExit:(id)textField;
-(void)setDelegate:(id)delegate;
-(void)onNext;
-(void)onGraphicVerifyBack;
-(void)onGraphicVerifyChangeImage;
-(void)initHeaderView;
-(void)internalInit;
-(id)init;
-(id)initWithFrame:(CGRect)frame;
@end

