/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"

@class NSString;
@protocol GTMHTTPFetcherServiceProtocol;

@protocol GTMFetcherAuthorizationProtocol <NSObject>
@optional
@property(assign) id<GTMHTTPFetcherServiceProtocol> fetcherService;
@property(assign) BOOL shouldAuthorizeAllRequests;
@property(readonly, assign) BOOL canAuthorize;
@required
@property(readonly, retain) NSString* userEmail;
-(BOOL)isAuthorizedRequest:(id)request;
-(BOOL)isAuthorizingRequest:(id)request;
-(void)stopAuthorizationForRequest:(id)request;
-(void)stopAuthorization;
-(void)authorizeRequest:(id)request delegate:(id)delegate didFinishSelector:(SEL)selector;
@optional
-(BOOL)primeForRefresh;
-(void)authorizeRequest:(id)request completionHandler:(id)handler;
@end

