/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMObject.h"
#import "NSCopying.h"

@class NSString;

@interface HardWareItem : MMObject <NSCopying> {
	unsigned long uiHardWareShowType;
	NSString* nsRankID;
	NSString* nsRankTitle;
	NSString* nsRankDisplay;
	NSString* nsScoreTitle;
	NSString* nsScoreDisplay;
	NSString* nsTipDisplay;
	NSString* nsColor;
	NSString* nsHighLightColor;
	NSString* nsLineColor;
	NSString* nsHighLightLineColor;
	NSString* nsFontColor;
	NSString* nsChampionUsername;
	NSString* nsDisplayUserName;
	NSString* nsThumbUrl;
	NSString* nsNotifyTitle;
	unsigned long uiTimeStamp;
}
@property(assign, nonatomic) unsigned long uiTimeStamp;
@property(retain, nonatomic) NSString* nsNotifyTitle;
@property(retain, nonatomic) NSString* nsThumbUrl;
@property(retain, nonatomic) NSString* nsDisplayUserName;
@property(retain, nonatomic) NSString* nsChampionUsername;
@property(retain, nonatomic) NSString* nsFontColor;
@property(retain, nonatomic) NSString* nsHighLightLineColor;
@property(retain, nonatomic) NSString* nsLineColor;
@property(retain, nonatomic) NSString* nsHighLightColor;
@property(retain, nonatomic) NSString* nsColor;
@property(retain, nonatomic) NSString* nsTipDisplay;
@property(retain, nonatomic) NSString* nsScoreDisplay;
@property(retain, nonatomic) NSString* nsScoreTitle;
@property(retain, nonatomic) NSString* nsRankDisplay;
@property(retain, nonatomic) NSString* nsRankTitle;
@property(retain, nonatomic) NSString* nsRankID;
@property(assign, nonatomic) unsigned long uiHardWareShowType;
-(void).cxx_destruct;
-(BOOL)IsExpired;
-(BOOL)fromXML:(XmlReaderNode_t*)xml;
-(id)copyWithZone:(NSZone*)zone;
@end

