/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class SKBuiltinBuffer_t, BaseRequest;

@interface HeartBeatRequest : WXPBGeneratedMessage {
}
@property(assign, nonatomic) unsigned scene;
@property(retain, nonatomic) SKBuiltinBuffer_t* blueToothBroadCastContent;
@property(retain, nonatomic) SKBuiltinBuffer_t* keyBuf;
@property(assign, nonatomic) unsigned timeStamp;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

