/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface IBeaconNotification : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* message;
@property(retain, nonatomic) NSString* tips;
@property(assign, nonatomic) int result;
+(void)initialize;
@end

