/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol IGoogleContactMgrExt <NSObject>
@optional
-(void)onFetchFromGoogleFailed;
-(void)onUnbindGoogleContactNetWorkFailed;
-(void)onUnbindGoogleContactFailedWith:(unsigned long)with;
-(void)onUnbindGoogleContactOK;
-(void)onBindGoogleContactNetWorkFailed;
-(void)onBindGoogleContactHasBeenUsed;
-(void)onBindGoogleContactFailedWith:(unsigned long)with;
-(void)onBindGoogleContactOK;
-(void)onInviteGoogleContacts:(id)contacts;
-(void)onListGoogleContacts:(id)contacts ret:(unsigned long)ret;
@end

