/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol IHeadImageExt
@optional
-(void)onHeadImageDelete:(id)aDelete;
-(void)onHeadImageUploadFail;
-(void)onHeadImageUploadOK;
-(void)onHeadImageChange:(id)change;
@end

