/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol IHttpCacheExt
-(void)OnHttpGetFinish:(id)finish response:(id)response ErrNo:(int)no isWebp:(BOOL)webp;
@end

