/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface ImageFileInfo : XXUnknownSuperclass {
	BOOL isExistInServer;
	NSString* thumbPath;
	NSString* imagePath;
	NSString* attachID;
	unsigned long checkedCount;
	unsigned long startPos;
	unsigned long totalSize;
	NSString* clientID;
	long long n64msgID;
}
@property(assign, nonatomic) BOOL isExistInServer;
@property(retain, nonatomic) NSString* clientID;
@property(assign, nonatomic) unsigned long totalSize;
@property(assign, nonatomic) unsigned long startPos;
@property(assign, nonatomic) unsigned long checkedCount;
@property(retain, nonatomic) NSString* attachID;
@property(assign, nonatomic) long long n64msgID;
@property(retain, nonatomic) NSString* imagePath;
@property(retain, nonatomic) NSString* thumbPath;
-(void).cxx_destruct;
-(id)init;
@end

