/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCActionSheetDelegate.h"
#import "WeChat-Structs.h"
#import "MMObject.h"
#import "ILocationMgrExt.h"
#import "WCSelectorViewDelegate.h"
#import "WCSelectorViewDataSource.h"
#import "WCMultiImageScannerDelegate.h"
#import "MMImagePickerManagerDelegate.h"

@class NSMutableArray, UINavigationController, NSString, WCSelectorView;
@protocol SelectorControllerDelegate;

@interface ImageSelectorController : MMObject <ILocationMgrExt, WCSelectorViewDelegate, WCSelectorViewDataSource, WCActionSheetDelegate, WCMultiImageScannerDelegate, MMImagePickerManagerDelegate> {
	NSMutableArray* _arrImages;
	WCSelectorView* _selectorView;
	UINavigationController* _navigationController;
	id<SelectorControllerDelegate> _delegate;
	BOOL _bChoosed;
	CGSize _imgSize;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) CGSize imgSize;
@property(assign, nonatomic) BOOL bChoosed;
@property(assign, nonatomic) __weak id<SelectorControllerDelegate> delegate;
@property(assign, nonatomic) __weak UINavigationController* navigationController;
@property(retain, nonatomic) WCSelectorView* selectorView;
@property(retain, nonatomic) NSMutableArray* arrImages;
-(void).cxx_destruct;
-(BOOL)shouldShowDeleteView;
-(id)getViewController;
-(void)MMImagePickerManagerDidCancel:(id)mmimagePickerManager;
-(void)MMImagePickerManager:(id)manager didFinishPickingImageWithInfo:(id)info;
-(void)onDeleteItemAtIndex:(unsigned)index;
-(void)onAddViews:(id)views;
-(void)showFBAlbumActionSheet:(id)sheet;
-(void)showActionSheet:(id)sheet;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)showImagePicker:(int)picker;
-(void)onDeleteViewAtIndex:(unsigned)index;
-(void)didSelectViewAtIndex:(unsigned)index;
-(CGSize)sizeForViews;
-(id)viewAtIndex:(unsigned)index;
-(unsigned)numbersOfViews;
-(void)dealloc;
-(id)init;
@end

