/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ImagePreviewDelegate <NSObject>
@optional
-(void)downloadFailInImagePreview;
-(void)returnFromImagePreview:(BOOL)imagePreview andPicker:(id)picker andImage:(id)image;
-(void)selectFromImagePreview:(id)imagePreview andImage:(id)image andData:(id)data;
@end

