/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BaseParser.h"
#import "WeChat-Structs.h"

@class UIFont, NSString;

@interface ImageParser : BaseParser {
	UIFont* _font;
	NSString* _nsImgSrc;
}
@property(retain, nonatomic) UIFont* font;
+(id)newInstance;
-(void).cxx_destruct;
-(id)getImageForText:(id)text;
-(id)stylesForString:(id)string withRange:(NSRange)range withParserPosition:(NSParserPosition*)parserPosition;
-(id)styleStringForContent:(id)content withParserPosition:(NSParserPosition)parserPosition outputLastPosition:(NSParserPosition*)position;
-(id)getImageStylesForString:(id)string withStyleString:(id)styleString;
-(id)getStylesForString:(id)string withStyleString:(id)styleString;
-(NSRange)rangeOfObjectInString:(id)string withRange:(NSRange)range;
-(id)getImage;
-(void)setImageSrc:(id)src;
@end

