/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"
#import "WeChat-Structs.h"

@class NSURL;

@interface ImageInfo : XXUnknownSuperclass <NSCopying> {
	unsigned long m_uiImageSource;
	NSURL* m_nuImageSourceURL;
}
@property(retain, nonatomic) NSURL* m_nuImageSourceURL;
@property(assign, nonatomic) unsigned long m_uiImageSource;
-(void).cxx_destruct;
-(id)copyWithZone:(NSZone*)zone;
-(id)init;
@end

