/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol IRecordDownloadExt <NSObject>
@optional
-(void)OnRecordMessageDownloadOK:(id)ok;
-(void)OnDownloadRecordMessagePart:(id)part DataId:(id)anId PartLen:(unsigned long)len TotalLen:(unsigned long)len4;
-(void)OnDownloadRecordMessageOK:(id)ok DataId:(id)anId bThumb:(BOOL)thumb;
-(void)OnDownloadRecordMessageFail:(id)fail DataId:(id)anId;
-(void)OnDownloadRecordMessageExpired:(id)expired DataId:(id)anId;
@end

