/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol IRemoteControlCheckExt
@optional
-(void)iRemoteControlCheckShouldPrevTrack;
-(void)iRemoteControlCheckShouldNextTrack;
-(void)iRemoteControlCheckShouldStop;
-(void)iRemoteControlCheckShouldPause;
-(void)iRemoteControlCheckShouldPlay;
-(void)iRemoteControlCheckShouldFinishRecord;
-(void)iRemoteControlCheckShouldBeginRecord;
-(void)iRemoteControlCheckPluginOff;
-(void)iRemoteControlCheckPluginOn;
@end

