/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ITranslateMsgMgrExt <NSObject>
@optional
-(void)onTranslateMessageChanged:(id)changed;
-(void)onTranslateMessageFailed:(id)failed errTip:(id)tip;
@end

