/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "BaseReq.h"

@class NSString;

@interface JoinChatRoomReq : BaseReq {
	NSString* groupId;
	NSString* chatRoomNickName;
	NSString* extMsg;
}
@property(retain, nonatomic) NSString* extMsg;
@property(retain, nonatomic) NSString* chatRoomNickName;
@property(retain, nonatomic) NSString* groupId;
-(void).cxx_destruct;
@end

