/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"


@interface JSAPIPermissionBitSet : WXPBGeneratedMessage {
}
@property(assign, nonatomic) unsigned bitValue4;
@property(assign, nonatomic) unsigned bitValue3;
@property(assign, nonatomic) unsigned bitValue2;
@property(assign, nonatomic) unsigned bitValue;
+(void)initialize;
@end

