/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ShareConfirmViewDelegate.h"
#import "PBMessageObserverDelegate.h"
#import "MMObject.h"

@class ShareConfirmView, NSString;
@protocol JSShareFBLogicHelperDelegate;

@interface JSShareFBLogicHelper : MMObject <ShareConfirmViewDelegate, PBMessageObserverDelegate> {
	ShareConfirmView* _confirmView;
	unsigned long fbEventID;
	id<JSShareFBLogicHelperDelegate> _delegate;
	NSString* _link;
	NSString* _thumbImageUrl;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* thumbImageUrl;
@property(retain, nonatomic) NSString* link;
@property(assign, nonatomic) __weak id<JSShareFBLogicHelperDelegate> delegate;
-(void).cxx_destruct;
-(void)rotateToOrientaion:(int)orientaion;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(void)OnError:(id)error;
-(void)OnCancel:(id)cancel;
-(void)OnSend:(id)send;
-(void)showConfirmView;
-(void)initConfirmViewWithTitle:(id)title description:(id)description thumbURL:(id)url;
-(void)dealloc;
-(id)initWithTitle:(id)title link:(id)link description:(id)description thumbURL:(id)url;
@end

