/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NewChatRoomMemberItemViewDelegate.h"
#import "WeChat-Structs.h"
#import "UIAlertViewDelegate.h"
#import "MMUIViewController.h"
#import "PBMessageObserverDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "contactInfoDelegate.h"
#import "tableViewDelegate.h"

@class MMLoadingView, UIView, UIImageView, NSString, MMTableView, CContact, NSMutableArray;

@interface LbsRoomInfoViewController : MMUIViewController <tableViewDelegate, UITableViewDelegate, UITableViewDataSource, NewChatRoomMemberItemViewDelegate, contactInfoDelegate, PBMessageObserverDelegate, UIAlertViewDelegate> {
	unsigned long m_uiEventID;
	unsigned long m_iMemberCount;
	CContact* m_lbsRoomContact;
	NSMutableArray* m_arrMemberList;
	MMLoadingView* m_loadingView;
	MMTableView* m_tableView;
	UIView* m_headerView;
	UIImageView* m_memberBkgView;
	UIImageView* m_memberBorderView;
	NSMutableArray* m_arrMemberView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableArray* m_arrMemberView;
@property(retain, nonatomic) CContact* m_lbsRoomContact;
-(void).cxx_destruct;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)stopLoading;
-(void)startLoading;
-(id)createBackGroundImageWithImage:(id)image scale:(unsigned long)scale;
-(void)updateHeadView;
-(void)loadRoomMember:(id)member;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(BOOL)tryGetRoomMember;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)openContactInfo:(id)info;
-(void)onGetRoomMemberFailed;
-(void)onGetRoomMemberFinished;
-(void)initHeaderView;
-(void)initTableView;
-(void)dealloc;
-(void)viewDidLoad;
-(void)initView;
-(void)initData;
@end

