/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "IMsgExt.h"
#import "MMService.h"
#import "QMapViewDelegate.h"
#import "MMService.h"

@class NSMutableArray, MMTimer, UIView, NSString, QMapView, NSMutableDictionary;

@interface LocationThumbMgr : MMService <QMapViewDelegate, IMsgExt, MMService> {
	QMapView* _mapView;
	UIView* _mapPinView;
	NSMutableDictionary* _taskDic;
	NSMutableArray* _taskQueue;
	MMTimer* _taskTimer;
	BOOL _isUpdating;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(id)getThumbPathWithChatname:(id)chatname MsgLocalID:(unsigned long)anId;
-(void).cxx_destruct;
-(void)OnDelMsg:(id)msg DelAll:(BOOL)all;
-(void)OnDelMsg:(id)msg MsgWrap:(id)wrap;
-(id)mapView:(id)view viewForAnnotation:(id)annotation;
-(void)mapViewDidFailLoadingMap:(id)mapView withError:(id)error;
-(void)deleteThumbImageWithChatname:(id)chatname MsgLocalID:(unsigned long)anId;
-(void)saveThumbImage:(id)image Chatname:(id)chatname MsgLocalID:(unsigned long)anId;
-(void)loadMapView:(id)view;
-(void)initMapView;
-(void)onTaskFailedWithError:(int)error;
-(void)asyncGenThumbImage;
-(void)deleteThumbTask:(id)task;
-(void)addThumbTask:(id)task;
-(void)startNextTask;
-(void)notifyTimeout;
-(void)onTimeout;
-(int)stopUpdate;
-(int)startUpdate;
-(int)deleteLocationThumb:(id)thumb MsgLocalID:(unsigned long)anId;
-(int)updateLocationThumb:(id)thumb;
-(id)getLocationThumb:(id)thumb MsgLocalID:(unsigned long)anId;
-(void)cleanResource;
-(void)enterForeground;
-(void)enterBackground;
-(void)dealloc;
-(BOOL)onServiceMemoryWarning;
-(void)onServiceReloadData;
-(void)onServiceClearData;
-(void)onServiceInit;
@end

