/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol MailContentViewDelegate
-(void)contentLengthChanged:(id)changed;
-(void)contentViewDidFinishEdit;
-(void)contentViewNeedSetContentOffset:(float)offset;
-(void)didStartWriteMailContent;
@end

