/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCDBCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"

@class NSString;

@interface MassSendContact : XXUnknownSuperclass <WCDBCoding> {
	NSString* m_nsUsrName;
	NSString* m_nsDetail;
	unsigned long m_uiToListCount;
	unsigned long ConIntRes2;
	NSString* ConStrRes1;
	NSString* ConStrRes2;
	long long m___rowID;
}
@property(assign, nonatomic) long long __rowID;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* ConStrRes2;
@property(retain, nonatomic) NSString* ConStrRes1;
@property(assign, nonatomic) unsigned long ConIntRes2;
@property(assign, nonatomic) unsigned long m_uiToListCount;
@property(retain, nonatomic) NSString* m_nsDetail;
@property(retain, nonatomic) NSString* m_nsUsrName;
+(id)dummyObject;
-(void).cxx_destruct;
-(void)dealloc;
-(id)init;
-(const basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)getWCDBPrimaryColumnName;
-(const WCDBIndexHelper*)getWCDBIndexArray;
-(unsigned long)getWCDBIndexArrayCount;
-(const map<unsigned long, unsigned long, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, unsigned long> > >*)getValueTagIndexMap;
-(id)getValueTypeTable;
-(const map<unsigned long, unsigned long, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, unsigned long> > >*)getFileValueTagIndexMap;
-(id)getFileValueTypeTable;
-(const map<unsigned long, unsigned long, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, unsigned long> > >*)getPackedValueTagIndexMap;
-(id)getPackedValueTypeTable;
-(const map<std::__1::basic_string<char>, unsigned long, std::__1::less<std::__1::basic_string<char> >, std::__1::allocator<std::__1::pair<const std::__1::basic_string<char>, unsigned long> > >*)getValueNameIndexMap;
-(id)getValueTable;
-(const WCDBCondition<NSString* >*)db_ConStrRes2;
-(const WCDBCondition<NSString* >*)db_ConStrRes1;
-(const WCDBCondition<unsigned long>*)db_ConIntRes2;
-(const WCDBCondition<unsigned long>*)db_m_uiToListCount;
-(const WCDBCondition<NSString* >*)db_m_nsDetail;
-(const WCDBCondition<NSString* >*)db_m_nsUsrName;
@end

