/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"
#import "IPushSystemMsgExt.h"
#import "PushSystemMsgViewDelegate.h"
#import "INetworkStatusMgrExt.h"

@class MMTimer, UIViewController, NSString, PushSystemMsgView;
@protocol MFPushSystemMsgDelegate;

@interface MFPushSystemMsgLogic : MMObject <INetworkStatusMgrExt, IPushSystemMsgExt, PushSystemMsgViewDelegate> {
	PushSystemMsgView* m_banner;
	unsigned long m_uiTipStatus;
	MMTimer* m_OOBTimer;
	id<MFPushSystemMsgDelegate> _delegate;
	UIViewController* _viewController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak UIViewController* viewController;
@property(assign, nonatomic) __weak id<MFPushSystemMsgDelegate> delegate;
@property(readonly, assign, nonatomic) PushSystemMsgView* bannerBtn;
-(void).cxx_destruct;
-(void)showOOBData;
-(void)onOOBTimer;
-(void)stopOOBTimer;
-(void)showNetworkTip:(id)tip;
-(void)updateSystemNetworkNotification:(unsigned long)notification;
-(void)shouldShowSystemMsg:(id)msg;
-(void)OnGetOOBData;
-(void)onNetworkStatusChange:(unsigned long)change;
-(void)dismissSystemMsg;
-(void)dismissSystemMessage;
-(void)updateMessage:(id)message;
-(void)makeNewPushSymtemView:(id)view;
-(void)dealloc;
-(id)init;
@end

