/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "QAnnotation.h"
#import "ILocationMgrExt.h"
#import "MMObject.h"
#import "WeChat-Structs.h"

@class NSString;
@protocol MMAddressAnnotationDelegate;

@interface MMAddressAnnotation : MMObject <QAnnotation, ILocationMgrExt> {
	unsigned long _geoTag;
	NSString* _title;
	NSString* _subtitle;
	id<MMAddressAnnotationDelegate> m_delegate;
	XXStruct_gLbvpC _coordinate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) XXStruct_gLbvpC coordinate;
@property(assign, nonatomic) __weak id<MMAddressAnnotationDelegate> m_delegate;
@property(copy, nonatomic) NSString* subtitle;
@property(copy, nonatomic) NSString* title;
-(void).cxx_destruct;
-(void)onDidFindAddress:(id)on forTag:(unsigned long)tag;
-(void)createNewRequest;
-(void)safeDeleteGeocoder;
-(id)initWithCoordinate:(XXStruct_gLbvpC)coordinate Location:(id)location POIName:(id)name;
-(void)dealloc;
@end

