/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "MMImagePreviewBrowserControllerDataSource.h"

@class NSMutableArray, NSString;

@interface MMAssetPickerControllerProxyObject : XXUnknownSuperclass <MMImagePreviewBrowserControllerDataSource> {
	NSMutableArray* m_selectedInfos;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableArray* m_selectedInfos;
-(void).cxx_destruct;
-(unsigned)previewAssetTotal;
-(id)previewAssetInfoAtIndex:(unsigned)index;
@end

