/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"

@class NSMutableArray, NSString;
@protocol MMAutoSearchLogicDelegate;

@interface MMAutoSearchLogic : MMObject {
	BOOL _blockSignal;
	id<MMAutoSearchLogicDelegate> _delegate;
	NSMutableArray* _autoSearchQueue;
	NSString* _lastResponseKey;
}
@property(retain, nonatomic) NSString* lastResponseKey;
@property(assign, nonatomic) BOOL blockSignal;
@property(retain, nonatomic) NSMutableArray* autoSearchQueue;
@property(assign, nonatomic) id<MMAutoSearchLogicDelegate> delegate;
-(void).cxx_destruct;
-(void)tryNextSearch;
-(BOOL)autoSearchShouldFinishedWithKeyword:(id)autoSearch QueryInterval:(double)interval StartFromFirst:(BOOL)first;
-(void)tryAutoSearchWithKeyword:(id)keyword StartFromFirst:(BOOL)first;
-(void)reset;
-(id)init;
@end

