/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface MMBarButton : XXUnknownSuperclass {
	int iContentWidth;
	int iContentHight;
	int iOriginWidth;
	int iOriginHeight;
	int eBarButtonStyle;
}
@property(assign, nonatomic) int eBarButtonStyle;
@property(assign, nonatomic) int iOriginHeight;
@property(assign, nonatomic) int iOriginWidth;
@property(assign, nonatomic) int iContentHight;
@property(assign, nonatomic) int iContentWidth;
-(void)tintColorDidChange;
-(CGRect)backgroundRectForBounds:(CGRect)bounds;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(id)hitTest:(CGPoint)test withEvent:(id)event;
@end

