/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface MMCostValueIdKey : XXUnknownSuperclass {
	unsigned m_uID;
	unsigned m_uTotalValueTimeKey;
	unsigned m_uTotalCountKey;
	NSString* m_nsDes;
	unsigned m_uTotalCostValueKey;
}
@property(retain, nonatomic) NSString* m_nsDes;
@property(assign, nonatomic) unsigned m_uTotalCountKey;
@property(assign, nonatomic) unsigned m_uTotalCostValueKey;
@property(assign, nonatomic) unsigned m_uID;
+(id)constructOneItemWithId:(unsigned)anId withTotalCostValueKey:(unsigned)totalCostValueKey withTotalCountKey:(unsigned)totalCountKey withDes:(id)des;
-(void).cxx_destruct;
-(id)init;
@end

