/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"

@class MMBizFileMatchNode, MMPathComponent;

@interface MMDiskBizUsageHandler : XXUnknownSuperclass {
	MMBizFileMatchNode* m_rootMatchNode;
	MMPathComponent* m_pathComponent;
	MMBizFileMatchNode* m_nodeUserLibrary;
	MMBizFileMatchNode* m_nodeUserDocument;
}
@property(retain, nonatomic) MMBizFileMatchNode* m_nodeUserDocument;
@property(retain, nonatomic) MMBizFileMatchNode* m_nodeUserLibrary;
@property(retain, nonatomic) MMPathComponent* m_pathComponent;
@property(retain, nonatomic) MMBizFileMatchNode* m_rootMatchNode;
-(void).cxx_destruct;
-(int)validateStoreTimeType:(const MMDiskUsageBizRule*)type;
-(BOOL)isAllSameBizType:(int)type fromNode:(id)node;
-(BOOL)addPathComponent:(id)component withRule:(const MMDiskUsageBizRule*)rule toRootNode:(id)rootNode;
-(id)ruleDescription:(const MMDiskUsageBizRule*)description;
-(BOOL)isRuleValid:(const MMDiskUsageBizRule*)valid;
-(void)configMatchNodeForPathPrefix;
-(void)loadPathMatchRules;
-(id)init;
@end

