/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMComponent.h"
#import "IFavoritesExt.h"
#import "INetworkStatusMgrExt.h"

@class FavoritesItem, MMFavTagComponent, UIView, UIImageView, NSString, MMFavVoiceComponent, MMFavImgComponent, MMFavUrlComponent, MMFavHeadComponent, MMFavThumbComponent, MMUIImageView, MMFavNameComponent;
@protocol MyFavoritesBaseCellDelegate;

@interface MMFavCellComponent : MMComponent <IFavoritesExt, INetworkStatusMgrExt> {
	MMFavHeadComponent* _headCom;
	MMFavTagComponent* _tagCom;
	MMFavNameComponent* _nameCom;
	MMFavThumbComponent* _thumbCom;
	MMFavUrlComponent* _urlCom;
	MMFavVoiceComponent* _voiceCom;
	MMFavImgComponent* _imgCom;
	MMUIImageView* m_selectedView;
	MMUIImageView* m_deselectedView;
	UIImageView* _failIcon;
	UIView* m_contentView;
	BOOL m_editing;
	id<MyFavoritesBaseCellDelegate> _favBaseCellDelegate;
	FavoritesItem* _favItem;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) FavoritesItem* favItem;
@property(assign, nonatomic) __weak id<MyFavoritesBaseCellDelegate> favBaseCellDelegate;
+(BOOL)isUseNewUI;
+(float)calHeightWithComData:(id)comData;
-(void).cxx_destruct;
-(void)OnStartDownloadFavoritesItem:(id)item;
-(void)OnStartUploadFavoritesItem:(id)item;
-(void)OnRestartAllUploadFailItems;
-(void)updateSyncStatus;
-(void)onNetworkStatusChange:(unsigned long)change;
-(void)changeEditingStatus:(BOOL)status animated:(BOOL)animated;
-(void)changeSelectStatu:(BOOL)statu;
-(void)configSelectView;
-(void)OnHeadImgLongPress:(id)press;
-(void)configContentLayout;
-(BOOL)isPadStyle;
-(void)configFavCell;
-(void)configVoiceComponent;
-(void)configImgComponent;
-(void)configThumbAndUrlComponent;
-(void)configTagComponent;
-(void)configHeadAndNameComponent;
-(void)dealloc;
@end

