/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "NSObject.h"


@protocol MMGridViewLayoutStrategy <NSObject>
+(BOOL)requiresEnablingPaging;
-(NSRange)rangeOfPositionsInBoundsFromOffset:(CGPoint)offset;
-(int)itemPositionFromLocation:(CGPoint)location;
-(CGPoint)originForItemAtPosition:(int)position;
-(CGSize)contentSize;
-(void)rebaseWithItemCount:(int)itemCount insideOfBounds:(CGRect)bounds;
-(void)setupItemSize:(CGSize)size andItemSpacingH:(int)h andItemSpacingV:(int)v withMinEdgeInsets:(UIEdgeInsets)minEdgeInsets andCenteredGrid:(BOOL)grid;
-(int)type;
@end

