/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMHttpConnectionDelegate.h"
#import "MMService.h"
#import "IClearDataMgrExt.h"
#import "MMService.h"

@class NSString;

@interface MMHttpCacheMgr : MMService <IClearDataMgrExt, MMService, MMHttpConnectionDelegate> {
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(void)ClearCacheDirByUsrName:(id)name;
+(void)ClearCacheDir:(unsigned long)dir;
+(id)GetFilePath:(id)path Type:(unsigned long)type;
+(id)GetCacheDir:(unsigned long)dir;
+(unsigned long)GetCacheType:(id)type;
-(void)onDiskStorageWarningCleanedSize:(unsigned*)size CacheMask:(unsigned long)mask;
-(void)onDiskStorageWarningCleanedSize:(unsigned*)size subQueue:(id)queue;
-(void)onDiskStorageWarningCleanedSize:(unsigned*)size;
-(void)HttpConnectionFail:(id)fail;
-(void)HttpConnectionFinished:(id)finished cachekey:(id)cachekey response:(id)response ErrNo:(int)no;
-(void)LoadCache:(id*)cache CacheKey:(id)key Type:(unsigned long)type;
-(void)getWithURL:(id)url cacheKey:(id)key Type:(unsigned long)type NotifyKey:(id)key4 RefererHeader:(id)header;
-(void)getWithURL:(id)url cacheKey:(id)key Type:(unsigned long)type NotifyKey:(id)key4;
-(void)dealloc;
-(void)onServiceInit;
-(void)addAutoCleanTask:(unsigned long)task;
@end

