/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"

@protocol MMImageScrollViewHelperDelegate;

@interface MMImageScrollViewHelper : XXUnknownSuperclass {
	BOOL dontCalcPreviewRect;
	BOOL noSingleTaps;
	BOOL noDoubleTaps;
	BOOL dontSupportVerticalLongImage;
	BOOL dontSupportHorizontalLongImage;
	id<MMImageScrollViewHelperDelegate> m_delegate;
}
@property(assign, nonatomic) __weak id<MMImageScrollViewHelperDelegate> m_delegate;
@property(assign, nonatomic) BOOL dontSupportHorizontalLongImage;
@property(assign, nonatomic) BOOL dontSupportVerticalLongImage;
@property(assign, nonatomic) BOOL noDoubleTaps;
@property(assign, nonatomic) BOOL noSingleTaps;
@property(assign, nonatomic) BOOL dontCalcPreviewRect;
-(void).cxx_destruct;
-(void)scrollViewDidZoom:(id)scrollView;
-(void)ZoomForPoint:(CGPoint)point;
-(void)onDoubleTap:(id)tap;
-(CGRect)zoomRectForScale:(float)scale withCenter:(CGPoint)center;
-(void)onSingleTap:(id)tap;
-(void)dealloc;
-(void)initHelper:(CGSize)helper orientation:(int)orientation;
-(void)initHelper:(CGSize)helper orientation:(int)orientation containSize:(CGSize)size;
-(void)initHelper:(CGSize)helper;
-(CGSize)calculateImageFitSizeForPreview:(CGSize)preview maxSize:(CGSize)size;
-(void)InitGestureRecognizer;
-(id)init;
@end

