/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "QAnnotationView.h"

@class UIImageView, UILabel, UIView, UIActivityIndicatorView, ThreeWayExpandImageView;

@interface MMLocationPinView : QAnnotationView {
	UIImageView* m_pinView;
	UIImageView* m_shadowView;
	UIImageView* m_pointView;
	ThreeWayExpandImageView* m_calloutView;
	UIActivityIndicatorView* m_loadingView;
	UILabel* m_labelLocation;
	UILabel* m_labelPOIName;
	BOOL m_bCallOutViewEnable;
	UIView* m_extraContentView;
}
@property(retain, nonatomic) UIView* m_extraContentView;
@property(readonly, assign, nonatomic) BOOL m_bIsCalloutHidden;
@property(assign, nonatomic) BOOL m_bCallOutViewEnable;
-(void).cxx_destruct;
-(BOOL)pointInside:(CGPoint)inside withEvent:(id)event;
-(void)dealloc;
-(id)initWithAnnotation:(id)annotation reuseIdentifier:(id)identifier;
-(id)init;
-(void)initView;
-(void)setPointImage:(id)image;
-(void)hideCallOutViewAnimated:(BOOL)animated Duration:(double)duration;
-(void)showCallOutViewAnimated:(BOOL)animated Duration:(double)duration;
-(void)updatePinView;
-(void)setContainerFrame:(CGRect)frame;
-(void)setLoadingStatus;
-(void)setLocationText:(id)text POIName:(id)name;
-(void)doUpAnimation;
-(void)doDownAnimation;
-(void)onAnimationFinish;
-(void)stopAllAnimation;
-(void)setDownFrame;
-(void)setUpFrame;
@end

