/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"

@class NSMutableArray;

@interface MMLockOverlayView : XXUnknownSuperclass {
	BOOL _errored;
	NSMutableArray* _pointsToDraw;
}
@property(assign, nonatomic) BOOL errored;
@property(retain, nonatomic) NSMutableArray* pointsToDraw;
-(void).cxx_destruct;
-(void)hightlightError;
-(void)resetView;
-(void)drawRect:(CGRect)rect;
-(id)initWithFrame:(CGRect)frame;
@end

