/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"


@interface MMMediaDevice : MMObject {
}
+(void)showMediaAuthorizedAlert:(id)alert content:(id)content;
+(void)deviceHasMediaPrivilege:(id)privilege shouldRequestAccessForMedia:(BOOL)media completion:(id)completion;
+(void)isLocationAvailable:(id)available;
+(void)isMicroPhoneAvailable:(id)available shouldRequestAccessForMedia:(BOOL)media;
+(void)isAlbumAvailable:(id)available;
+(void)isCameraAvailable:(id)available shouldRequestAccessForMedia:(BOOL)media;
+(void)isMediaDeviceAvailable:(int)available shouldRequestAccessForMedia:(BOOL)media completionHandler:(id)handler;
+(void)isMediaDeviceAvailable:(int)available completionHandler:(id)handler;
@end

