/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCFacadeExt.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class SnsMusicStorage, NSMutableArray, NSString;

@interface MMMusicListMgr : XXUnknownSuperclass <WCFacadeExt> {
	SnsMusicStorage* m_snsMusicStorage;
	NSMutableArray* m_musicInfoArr;
	int m_curMusicListSource;
	BOOL m_isSnsMusicDelMatters;
	NSString* m_curUserName;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableArray* m_musicInfoArr;
-(void).cxx_destruct;
-(int)getMusicListSource;
-(void)onHomepageUpdate:(int)update withAdded:(id)added andChanged:(id)changed andDeleted:(id)deleted;
-(void)onDataChangedWithAdded:(id)added andChanged:(id)changed andDeleted:(id)deleted;
-(void)updateMusicListBySource:(int)source;
-(void)deleteSnsMusicItem:(id)item;
-(id)getSnsMusicStorage;
-(void)saveSnsMusicStorage;
-(void)addHomePageMusicItems;
-(void)loadSnsMusicStorage;
-(BOOL)isMusicStorageContainsItem:(id)item;
-(void)removeDuplicateItems;
-(void)addWebSearchMusic2array;
-(void)addSnsMusic2array;
-(void)addShakeMusic2array;
-(void)addFavMusic2array;
-(void)updateMusicInfoArray;
-(void)dealloc;
-(id)init;
@end

