/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"

@class MMResDecryptUrlInfo, NSString;

@interface MMResDecryptInfo : MMObject {
	unsigned long _resType;
	unsigned long _subResType;
	unsigned long _eid;
	unsigned long _scene;
	NSString* _sampleId;
	unsigned long _reportId;
	MMResDecryptUrlInfo* _resDecryptInfo;
}
@property(retain, nonatomic) MMResDecryptUrlInfo* resDecryptInfo;
@property(assign, nonatomic) unsigned long reportId;
@property(retain, nonatomic) NSString* sampleId;
@property(assign, nonatomic) unsigned long scene;
@property(assign, nonatomic) unsigned long eid;
@property(assign, nonatomic) unsigned long subResType;
@property(assign, nonatomic) unsigned long resType;
-(void).cxx_destruct;
-(void)dealloc;
@end

