/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMUIViewController.h"
#import "UITextFieldDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UIAlertViewDelegate.h"
#import "PBMessageObserverDelegate.h"

@class UITextField, CContact, NSString;
@protocol MMSayHelloViewControllerDelegate;

@interface MMSayHelloViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, UITextFieldDelegate, PBMessageObserverDelegate, UIAlertViewDelegate> {
	UITextField* m_sayHelloTextView;
	NSString* m_helloContent;
	CContact* m_helloReceiver;
	unsigned long m_eventID;
	id<MMSayHelloViewControllerDelegate> m_delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<MMSayHelloViewControllerDelegate> delegate;
@property(retain, nonatomic) CContact* helloReceiver;
@property(retain, nonatomic) NSString* helloContent;
@property(retain, nonatomic) UITextField* sayHelloTextView;
-(void).cxx_destruct;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(void)quitSayHello;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldReturn:(id)textField;
-(void)updateWordCount:(id)count;
-(id)tableView:(id)view titleForHeaderInSection:(int)section;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)onCancelSendSayHello;
-(void)onSendSayHello:(id)hello;
-(id)filterString:(id)string;
-(BOOL)doSayHello:(id)hello;
-(void)dealloc;
-(id)init;
@end

