/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UIAlertViewDelegate.h"
#import "MMSafeModeMgrExt.h"

@class UIImageView, UIScrollView, NSArray, NSString, UITableView, UIButton, MMLoadingView;

@interface MMSafeModeViewController : XXUnknownSuperclass <MMSafeModeMgrExt, UIAlertViewDelegate, UITableViewDelegate, UITableViewDataSource> {
	MMLoadingView* m_loadingViewX;
	UIScrollView* m_contentView;
	UIImageView* m_logoView;
	UIButton* m_clearButton;
	UIButton* m_uploadButton;
	UIButton* m_uploadListButton;
	UITableView* m_uploadListTableView;
	BOOL m_isFirstRunning;
	BOOL m_isShowUploadList;
	BOOL m_isShowCheckUpdateBtn;
	NSArray* m_uploadList;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)onUploadFilesFail;
-(void)onUploadFilesFinished;
-(void)onUploadFilesProgress:(float)progress;
-(void)onClearUnnecessaryFilesFinished;
-(void)onCrashReportFinished;
-(void)onServerConfigUpdateFinished:(BOOL)finished;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)onEnterButtonClicked:(id)clicked;
-(void)onCheckUpdateButtonClicked:(id)clicked;
-(void)onUploadListButtonClicked:(id)clicked;
-(void)onUploadButtonClicked:(id)clicked;
-(void)onClearButtonClicked:(id)clicked;
-(void)onRebootButtonClicked:(id)clicked;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)layoutEnterWeChatButton:(int*)button;
-(void)layoutCheckUpdateButtonAndTips:(int*)tips;
-(void)layoutUploadListTableView:(int*)view;
-(void)layoutUploadButtonAndTips:(int*)tips;
-(void)layoutClearButtonAndTips:(int*)tips;
-(void)layoutRebootButtonAndTips:(int*)tips;
-(void)layoutLogoView;
-(float)getContentViewY;
-(void)layoutForScene2Or3;
-(void)layoutForScene1;
-(void)viewDidLoad;
-(void)startupFirstRun;
-(void)stopLoading;
-(void)startLoadingBlockedWithText:(id)text;
-(void)startLoadingBlocked;
-(void)dealloc;
-(id)init;
@end

