/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MMShareActionSheetDelegate <NSObject>
@optional
-(void)actionSheet:(id)sheet didDismissWithItem:(id)item atSection:(id)section;
-(void)actionSheet:(id)sheet willDismissWithItem:(id)item atSection:(id)section;
-(void)actionSheetCancel:(id)cancel;
-(BOOL)actionSheetShouldCancel:(id)actionSheet;
-(void)actionSheet:(id)sheet didSelectWithItem:(id)item atSection:(id)section;
@end

