/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIColor, UIImage, NSString;

@interface MMTabBarButton : XXUnknownSuperclass {
	NSString* _nsNormalTitle;
	NSString* _nsSelectedTitle;
	UIImage* _oNormalBackgroundImage;
	UIImage* _oSelectedBackgroundImage;
	UIImage* _oNormalImage;
	UIImage* _oSelectedImage;
	UIColor* _oNormalShadowColor;
	UIColor* _oSelectedShadowColor;
	UIColor* _oNormalTitleColor;
	UIColor* _oSelectedTitleColor;
}
@property(retain, nonatomic) UIColor* oSelectedTitleColor;
@property(retain, nonatomic) UIColor* oNormalShadowColor;
@property(retain, nonatomic) UIColor* oSelectedShadowColor;
@property(retain, nonatomic) UIColor* oNormalTitleColor;
@property(retain, nonatomic) UIImage* oSelectedImage;
@property(retain, nonatomic) UIImage* oNormalImage;
@property(retain, nonatomic) UIImage* oSelectedBackgroundImage;
@property(retain, nonatomic) UIImage* oNormalBackgroundImage;
@property(retain, nonatomic) NSString* nsSelectedTitle;
@property(retain, nonatomic) NSString* nsNormalTitle;
-(void).cxx_destruct;
-(void)setTitleColor:(id)color forState:(unsigned)state;
-(void)setTitle:(id)title forState:(unsigned)state;
-(void)setBackgroundImage:(id)image forState:(unsigned)state;
-(void)setImage:(id)image forState:(unsigned)state;
-(void)setSelected:(BOOL)selected;
@end

