/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UITapGestureRecognizer, NSMutableArray;
@protocol MMTabBarControllerDelegate;

@interface MMTabBarController : XXUnknownSuperclass {
	unsigned _viewControllersCount;
	NSMutableArray* _tabBarBtns;
	NSMutableArray* _badgeViews;
	UITapGestureRecognizer* _doubleTapGesture;
	BOOL _hasDoubleTapGesture;
	float _lastScreenWidth;
}
@property(assign, nonatomic) __weak id<MMTabBarControllerDelegate> delegate;
-(void).cxx_destruct;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(unsigned)supportedInterfaceOrientations;
-(BOOL)shouldAutorotateToInterfaceOrientation:(int)interfaceOrientation;
-(void)setTabBarBadgeImage:(id)image forIndex:(unsigned)index;
-(void)setTabBarBadgeString:(id)string forIndex:(int)index;
-(void)setTabBarBadgeValue:(int)value forIndex:(int)index;
-(id)getViewControllerAtIndex:(unsigned long)index;
-(id)currentViewController;
-(id)getTabBarBtnForIndex:(int)index;
-(id)getTabBarBtnViews;
-(void)bringBadgeViewsToFront;
-(id)getBadgeViewForIndex:(int)index;
-(id)getBadgeViews;
-(void)handleDoubleTapGesture:(id)gesture;
-(void)removeDoubleTapGesture;
-(void)addDoubleTapGesture;
-(void)showTabBarWithNoViewHeightUpdateForIndex:(int)index;
-(void)hideTabBarWithNoViewHeightUpdateForIndex:(int)index;
-(void)showTabBarForIndex:(int)index;
-(void)hideTabBarForIndex:(int)index;
-(void)showTabBar;
-(void)hideTabBar;
-(void)setAllTabBarItemEnabled:(BOOL)enabled;
-(int)getBadgeViewRightMarginPortrait;
-(void)observeValueForKeyPath:(id)keyPath ofObject:(id)object change:(id)change context:(void*)context;
-(void)relayoutBadgeViewForIpadIOS8;
-(void)reLayoutTabbarToOrientation:(int)orientation;
-(void)setViewControllers:(id)controllers animated:(BOOL)animated;
-(void)setViewControllers:(id)controllers;
-(void)setSelectedViewController:(id)controller;
-(void)setSelectedIndex:(unsigned)index;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)viewDidLayoutSubviews;
-(void)viewWillLayoutSubviews;
-(void)makeSureFrame;
-(void)viewWillAppear:(BOOL)view;
-(id)init;
@end

