/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MMWCResFileData, NSString, NSArray, MMResBatchDownloadTask;
@protocol MMResBatchSaveHandlerDelegate;

@interface MMWCResBatchSaveHandler : XXUnknownSuperclass {
	MMWCResFileData* _fileData;
	unsigned long _handlerId;
	BOOL _needCleanWebviewCacheAfterBatchSave;
	unsigned long _resType;
	unsigned long _resSubType;
	NSString* _mainDocumentUrl;
	NSString* _configUrl;
	NSString* _appId;
	NSString* _domain;
	NSString* _fileSubPath;
	NSArray* _resUrlInfoList;
	NSString* _packageId;
	unsigned long _configCrc32;
	MMResBatchDownloadTask* _downloadTask;
	id<MMResBatchSaveHandlerDelegate> _handlerDelegate;
}
@property(assign, nonatomic) __weak id<MMResBatchSaveHandlerDelegate> handlerDelegate;
@property(retain, nonatomic) MMResBatchDownloadTask* downloadTask;
@property(assign, nonatomic) BOOL needCleanWebviewCacheAfterBatchSave;
@property(assign, nonatomic) unsigned long configCrc32;
@property(retain, nonatomic) NSString* packageId;
@property(readonly, assign, nonatomic) unsigned long handlerId;
@property(retain, nonatomic) NSArray* resUrlInfoList;
@property(retain, nonatomic) NSString* fileSubPath;
@property(retain, nonatomic) NSString* domain;
@property(retain, nonatomic) NSString* appId;
@property(retain, nonatomic) NSString* configUrl;
@property(retain, nonatomic) NSString* mainDocumentUrl;
@property(assign, nonatomic) unsigned long resSubType;
@property(assign, nonatomic) unsigned long resType;
-(void).cxx_destruct;
-(unsigned long)genHandlerId;
-(id)updateConfigInfo;
-(void)updateConfigInfoWithoutNewRes;
-(void)startBatchSave;
-(void)dealloc;
-(id)initWithFileData:(id)fileData;
@end

