/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMService.h"
#import "MMService.h"

@class NSMutableArray, MMTimer, NSString, MMWebViewController, NSMutableDictionary;

@interface MMWebViewKeepHolderMgr : MMService <MMService> {
	MMWebViewController* _webViewVCForNewMainFrameBanner;
	NSMutableArray* _dpArrOpenedWebview;
	NSMutableDictionary* _dicBackgroundWebviewTask;
	NSMutableArray* _arrTaskOrder;
	MMTimer* _checkTimer;
	BOOL _bIsDelayLoading;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(BOOL)onServiceMemoryWarning;
-(void)dealloc;
-(id)init;
-(void)cancelHoldWebViewVC:(id)vc;
-(id)getKeepHoldWebViewVCForNewMainFrameBanner;
-(id)getKeepHoldWebViewVCTitleForNewMainFrameBanner;
-(void)keepHoldWebViewVCForNewMainFrameBanner:(id)newMainFrameBanner;
-(void)dp_sendJSEventToAllWebView:(id)allWebView Param:(id)param AppID:(id)anId Host:(id)host;
-(void)dp_deleteWebView:(id)view;
-(void)dp_addWebViewAsWeak:(id)weak;
-(void)onCheckBackgroundTaskTimeOut;
-(void)cleanAllBackgroundTask;
-(id)getCurrentAllPresentingBackgroundVC;
-(void)deleteBackgroundTaskForKey:(id)key;
-(id)getBackgroundTaskForKey:(id)key;
-(BOOL)addBackgroundTask:(id)task forKey:(id)key IsPresented:(BOOL)presented;
-(void)setDelayLoading:(BOOL)loading;
-(BOOL)hasDelayLoadingTask;
@end

