/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PBMessageObserverDelegate.h"
#import "MMUIView.h"

@class JSEvent, CContact, UIButton, NSString, UIImageView, MMLoadingView;
@protocol WebAddContactDelegate;

@interface MMWebAddContactView : MMUIView <PBMessageObserverDelegate> {
	NSString* m_nsUsrName;
	JSEvent* m_nsCallBack;
	id<WebAddContactDelegate> m_delegate;
	int m_scene;
	MMLoadingView* m_loadingView;
	UIButton* m_btnConfirm;
	UIButton* m_btnCancel;
	UIButton* m_btnRetry;
	UIButton* m_btnAdd;
	UIImageView* m_backgroundView;
	CContact* m_oContact;
}
@property(assign, nonatomic) int m_scene;
@property(assign, nonatomic) __weak id<WebAddContactDelegate> m_delegate;
-(void).cxx_destruct;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(void)HandleContact:(id)contact;
-(void)CreateVerify;
-(void)CreateSearch;
-(void)OnAddOk;
-(void)OnConfirm;
-(void)OnAdd;
-(void)OnCancel;
-(void)layoutSubviewToOrientation:(int)orientation;
-(void)UpdateView:(unsigned long)view;
-(void)initView;
-(void)dealloc;
-(id)initWithUsrName:(id)usrName CallBack:(id)back;
@end

