/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class MMWebViewController, NSMutableDictionary;

@interface MMWebViewPluginScheduler : XXUnknownSuperclass {
	MMWebViewController* _ownerWebViewController;
	NSMutableDictionary* _pluginName2InstanceDic;
}
@property(readonly, assign, nonatomic) NSMutableDictionary* pluginName2InstanceDic;
@property(readonly, assign, nonatomic) __weak MMWebViewController* ownerWebViewController;
-(void).cxx_destruct;
-(void)handleEvent:(unsigned)event userInfo:(id)info;
-(id)GetPluginInstanceByName:(id)name;
-(void)loadingInitPluginArray;
-(void)dealloc;
-(id)initWithOwnerWebViewController:(id)ownerWebViewController;
@end

