/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableDictionary;

@interface MonoServiceMsgHistory : XXUnknownSuperclass {
	NSMutableDictionary* m_msgHistoryDic;
}
@property(retain, nonatomic) NSMutableDictionary* m_msgHistoryDic;
-(void).cxx_destruct;
-(void)addHistoryWithMsg:(id)msg;
-(id)getHistoryMsg:(id)msg;
-(BOOL)hasHistoryMsg:(id)msg;
-(id)init;
@end

