/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol MsgImgFullScreenViewControllerDelegate <NSObject>
@optional
-(void)onImgMsgLocate:(id)locate;
-(void)onPlayAttachVideo:(id)video;
-(void)onNeedPushViewController:(id)controller animated:(BOOL)animated;
-(void)onCurrentPageMsgReMoved:(id)moved;
-(void)onHideStatusBar;
-(void)onShowStatusBar;
-(void)onDidHideToMsg:(id)on;
-(void)onDidShowFromMsg:(id)on;
-(void)onSingleTap:(id)tap;
@end

