/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "WCActionSheetDelegate.h"
#import "UIScrollViewDelegate.h"
#import "MMUIScrollView.h"
#import "ImageScrollViewDelegate.h"

@class MMUIViewController, NSString, MMAnimationTipView, NSMutableDictionary;
@protocol MsgImgFullScreenContainerDelegate;

@interface MsgImgFullScreenContainer : MMUIScrollView <UIScrollViewDelegate, ImageScrollViewDelegate, WCActionSheetDelegate> {
	NSMutableDictionary* dicVisiblePageIndex;
	int m_iNumberOfPages;
	int m_iCurrentPage;
	MMAnimationTipView* m_tipView;
	BOOL m_bFromPicker;
	CGRect _originImageRectInScreen;
	id<MsgImgFullScreenContainerDelegate> m_delegate;
	MMUIViewController* m_viewController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL m_bFromPicker;
@property(assign, nonatomic) int m_iCurrentPage;
@property(assign, nonatomic) int m_iNumberOfPages;
@property(assign, nonatomic) __weak id<MsgImgFullScreenContainerDelegate> m_delegate;
@property(assign, nonatomic) __weak MMUIViewController* m_viewController;
-(void).cxx_destruct;
-(void)willAnimateRotationToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(id)getPhotoatIndex:(unsigned)index;
-(void)updatePhotoatIndex:(unsigned)index;
-(void)setPage:(unsigned long)page atIndex:(unsigned)index;
-(void)clearView;
-(void)updatePageCount:(unsigned long)count;
-(unsigned)imageCount;
-(id)viewAtPage:(unsigned)page frame:(CGRect)frame;
-(id)imageAtPage:(unsigned)page;
-(CGPoint)contentOffsetForPagingScrollView;
-(CGSize)contentSizeForPagingScrollView;
-(CGRect)frameForPageAtIndex:(unsigned)index;
-(CGRect)frameForPagingScrollView:(int)pagingScrollView;
-(void)ImageScrollViewWillBeginZooming:(id)imageScrollView withView:(id)view;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(void)scrollViewDidEndScrollingAnimation:(id)scrollView;
-(void)scrollViewDidScroll:(id)scrollView;
-(BOOL)isDisplayingPageForIndex:(unsigned)index;
-(void)tilePages;
-(void)animateShowWithOriginRectInScreen:(CGRect)screen;
-(id)initWithFrame:(CGRect)frame;
-(void)initScrollView;
-(void)OnLongPressBegin:(id)begin;
-(void)OnLongPress:(id)press;
-(void)onDoubleTap:(id)tap;
-(void)onSingleTap:(id)tap;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)addToFavorites;
-(void)forwardMessage;
-(void)onOperate;
-(void)onSavedPhotosAlbum;
-(void)setFrame:(CGRect)frame;
@end

