/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "UITextFieldDelegate.h"
#import "MMUIViewController.h"
#import "WeChat-Structs.h"

@class MMTableViewInfo, NSString, MMTableViewCellInfo;

@interface NameEditorViewController : MMUIViewController <UITextFieldDelegate> {
	MMTableViewInfo* m_tableViewInfo;
	MMTableViewCellInfo* m_editInfo;
	NSString* m_nsOldText;
	NSString* m_nsFooterTip;
	NSString* m_nsHeaderTip;
	id m_targetOnSave;
	SEL m_selOnSave;
	BOOL m_bEnableEmpty;
	BOOL m_bAutoDismis;
	id m_userData;
	unsigned long m_uiScene;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned long m_uiScene;
@property(retain, nonatomic) MMTableViewCellInfo* m_editInfo;
@property(retain, nonatomic) id m_userData;
@property(assign, nonatomic) BOOL m_bAutoDismis;
@property(assign, nonatomic) BOOL m_bEnableEmpty;
@property(retain, nonatomic) NSString* m_nsOldText;
-(void).cxx_destruct;
-(void)enableAutoCorrect:(BOOL)correct;
-(void)dealloc;
-(id)initWithSaveTarget:(id)saveTarget sel:(SEL)sel headerTip:(id)tip footerTip:(id)tip4 textTip:(id)tip5;
-(id)initWithSaveTarget:(id)saveTarget sel:(SEL)sel footerTip:(id)tip textTip:(id)tip4;
-(void)updateWordCount:(id)count;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(void)onSaveText;
-(void)disMissThisViewAnimated;
-(void)viewDidLoad;
-(void)viewDidLayoutSubviews;
@end

