/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"
#import "WeChat-Structs.h"

@class NSString;

@interface NavigateItem : MMObject {
	XXStruct_gLbvpC _coordinate;
	NSString* _name;
}
@property(retain, nonatomic) NSString* name;
@property(assign, nonatomic) XXStruct_gLbvpC coordinate;
-(void).cxx_destruct;
-(void)dealloc;
@end

