/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMUIViewController.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"
#import "MMStepSliderDelegate.h"

@class UIImageView, MMStepSlider, NSArray, UIView, NSString, UITableView, UIPageControl, MMTableView;

@interface NewSettingFontSizeViewController : MMUIViewController <MMStepSliderDelegate, UITableViewDataSource, UITableViewDelegate> {
	unsigned long m_curLevel;
	float m_uiCurSize;
	NSArray* m_allLevel;
	UITableView* _tableView1;
	MMTableView* _tableView2;
	MMStepSlider* _sliderView;
	UIView* _bottomView;
	UIImageView* _pageBgView;
	UIPageControl* _pageControl;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)scrollViewDidEndDecelerating:(id)scrollView;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(float)getDynamicValue:(float)value;
-(id)genMsgLabel:(id)label;
-(void)makeNormalCell:(id)cell withImgNaem:(id)imgNaem andText:(id)text;
-(void)makeCell:(id)cell isSender:(BOOL)sender andText:(id)text;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)mmSliderViewChange:(unsigned long)change;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)gestureRecognizerShouldBegin:(id)gestureRecognizer;
-(void)configBottomView;
-(void)viewWillLayoutSubviews;
-(void)configPageControl;
-(void)configTableView2;
-(void)configTableView1;
-(void)configData;
-(void)saveFontChange;
-(void)onBackButtonClicked;
-(void)viewWillAppear:(BOOL)view;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)viewDidLoad;
@end

