/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMUIViewController.h"

@class MMTableViewInfo;

@interface NSStringSelectViewController : MMUIViewController {
	MMTableViewInfo* m_tableViewInfo;
	id m_targetOnSelect;
	SEL m_selOnSelect;
}
-(void).cxx_destruct;
-(void)OnSelectCell:(id)cell;
-(void)viewDidLoad;
-(void)viewDidLayoutSubviews;
-(void)setOnSelectTarget:(id)target sel:(SEL)sel;
-(id)initWithArray:(id)array selected:(id)selected;
-(void)updateTableViewWithArray:(id)array selected:(id)selected;
-(void)initView;
@end

