/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface OpenApiMgrHelper : XXUnknownSuperclass {
}
+(id)parseURLParams:(id)params;
+(id)checkAppMsgThumbData:(id)data;
+(id)getNetWorkErrorHtml;
+(void)checkShowTabbar;
+(void)hideChatViewKeyborad;
+(id)makeURLMessageForShareTo3rdApp:(id)a3rdApp withTitle:(id)title;
+(id)makeTextMessageForShareTo3rdApp:(id)a3rdApp;
+(id)makeLocationMessageForShareTo3rdAppWithLatitude:(double)latitude andLongitude:(double)longitude title:(id)title;
+(id)makeMediaMessageForShareTo3rdApp:(id)a3rdApp withType:(int)type;
+(void)makeFileInternalMessage:(id)message;
+(BOOL)isNeedInit;
+(BOOL)isLogin;
+(id)createConfirmLogicHelper:(id)helper withAppData:(id)appData withAppId:(id)appId showTextView:(BOOL)view appScene:(unsigned long)scene;
+(id)createConfirmLogicHelper:(id)helper withAppData:(id)appData withAppId:(id)appId showTextView:(BOOL)view appScene:(unsigned long)scene redirectUrl:(id)url;
+(id)FormAppMessage:(id)message withAppMessage:(id)appMessage appID:(id)anId;
+(id)FormTextMsg:(id)msg withText:(id)text appID:(id)anId;
@end

