/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCoding.h"

@class CMessageWrap, NSString, NSMutableDictionary;

@interface OpenInfo : XXUnknownSuperclass <NSCoding> {
	unsigned long m_uiLocalID;
	NSString* m_nsUsrName;
	unsigned long m_uiCreateTime;
	unsigned long m_uiScene;
	CMessageWrap* m_wrapMsg;
	unsigned long m_uiStartPos;
	unsigned long m_uiAddQueueTime;
	BOOL m_bCheckMd5;
	NSString* m_nsAttachId;
	NSString* m_nsAttachFileExt;
	unsigned long m_uiAttachDataSize;
	unsigned long long m_ui64StartTime;
	BOOL m_bUpload;
	long m_nRetCode;
	NSString* m_nsShareOriginUrl;
	NSString* m_nsShareOpenUrl;
	NSString* m_nsJsAppId;
	NSMutableDictionary* m_dicStatParas;
}
@property(retain, nonatomic) NSMutableDictionary* m_dicStatParas;
@property(retain, nonatomic) NSString* m_nsJsAppId;
@property(retain, nonatomic) NSString* m_nsShareOpenUrl;
@property(retain, nonatomic) NSString* m_nsShareOriginUrl;
@property(assign, nonatomic) long m_nRetCode;
@property(assign, nonatomic) BOOL m_bUpload;
@property(assign, nonatomic) unsigned long m_uiAttachDataSize;
@property(retain, nonatomic) NSString* m_nsAttachFileExt;
@property(retain, nonatomic) NSString* m_nsAttachId;
@property(assign, nonatomic) BOOL m_bCheckMd5;
@property(assign, nonatomic) unsigned long m_uiAddQueueTime;
@property(assign, nonatomic) unsigned long m_uiStartPos;
@property(retain, nonatomic) CMessageWrap* m_wrapMsg;
@property(assign, nonatomic) unsigned long m_uiScene;
@property(assign, nonatomic) unsigned long m_uiCreateTime;
@property(retain, nonatomic) NSString* m_nsUsrName;
@property(assign, nonatomic) unsigned long m_uiLocalID;
-(void).cxx_destruct;
-(id)GetStatInfo;
-(void)SetStartTime;
-(void)SetStatus;
-(BOOL)IsCanDownload;
-(BOOL)IsCanUpload;
-(void)GetMsg;
-(id)description;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)init;
@end

