/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "PBCoding.h"

@class NSString;

@interface PBCMessageWrap : XXUnknownSuperclass <PBCoding> {
	unsigned mesSvrId;
	unsigned mesLocalId;
	unsigned messageType;
	unsigned status;
	unsigned imgStatus;
	unsigned downloadStatus;
	unsigned createTime;
	NSString* fromUser;
	NSString* toUser;
	NSString* realChatUser;
	NSString* content;
	NSString* msgSource;
	long long n64MesSvrId;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* msgSource;
@property(assign, nonatomic) long long n64MesSvrId;
@property(retain, nonatomic) NSString* content;
@property(retain, nonatomic) NSString* realChatUser;
@property(retain, nonatomic) NSString* toUser;
@property(retain, nonatomic) NSString* fromUser;
@property(assign, nonatomic) unsigned createTime;
@property(assign, nonatomic) unsigned downloadStatus;
@property(assign, nonatomic) unsigned imgStatus;
@property(assign, nonatomic) unsigned status;
@property(assign, nonatomic) unsigned messageType;
@property(assign, nonatomic) unsigned mesLocalId;
@property(assign, nonatomic) unsigned mesSvrId;
+(void)initialize;
-(void).cxx_destruct;
-(const map<unsigned long, unsigned long, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, unsigned long> > >*)getValueTagIndexMap;
-(id)getValueTypeTable;
-(void)setFromCMessageWrap:(id)cmessageWrap;
-(id)toCMessageWrap;
@end

