/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface PLCrashReportApplicationInfo : XXUnknownSuperclass {
	NSString* _applicationIdentifier;
	NSString* _applicationVersion;
}
@property(readonly, assign, nonatomic) NSString* applicationVersion;
@property(readonly, assign, nonatomic) NSString* applicationIdentifier;
-(void)dealloc;
-(id)initWithApplicationIdentifier:(id)applicationIdentifier applicationVersion:(id)version;
@end

