/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "CBaseContactInfoAssist.h"

@class UIView, MMTableViewInfo, UIButton, UIImageView, UILabel, DelaySwitchSettingLogic;

@interface PluginContactInfoAssist : CBaseContactInfoAssist {
	MMTableViewInfo* m_tableViewInfo;
	int m_pluginType;
	unsigned long m_uOpType;
	UIView* m_switchView;
	DelaySwitchSettingLogic* m_delaySwitchLogic;
	UIButton* m_installBtn;
	UIButton* m_uninstallBtn;
	UILabel* m_statusLabel;
	UIImageView* m_statusView;
}
-(void).cxx_destruct;
-(void)goToBindQQ;
-(id)getLoadingText;
-(void)onSwitchValueChange:(id)change;
-(void)onClickClearMessage:(id)message;
-(void)clearPluginMessage;
-(void)onNewMsg;
-(void)initHeaderView;
-(void)initHeadImage;
-(void)initInstallView;
-(void)uninstallPlugin;
-(void)installPlugin;
-(void)onSwitchViewOff;
-(void)onSwitchViewOn;
-(void)setDelaySettingType:(int)type andValue:(BOOL)value;
-(void)updateInstallStateAndReloadTableView;
-(void)initFooterView;
-(void)updateInstallView;
-(void)promptUninstall:(id)uninstall;
-(void)doUninstall;
-(void)clearPluginData;
-(id)getUnInstallBtnTitle;
-(id)getUnInstallTip;
-(id)getPluginIntro;
-(void)makeContactIntroCell:(id)cell CellInfo:(id)info;
-(void)reloadTableViewData;
-(void)reloadTableView;
-(void)reloadInstalledTableViewData;
-(void)initTableView;
-(id)GetTableView;
-(void)dealloc;
-(id)initWithContact:(id)contact delegate:(id)delegate;
@end

