/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "POPAnimatableProperty.h"

@class NSString;

@interface POPConcreteAnimatableProperty : POPAnimatableProperty {
	NSString* name;
	id readBlock;
	id writeBlock;
	float threshold;
}
-(float)threshold;
-(id)writeBlock;
-(id)readBlock;
-(id)name;
-(void).cxx_destruct;
-(id)initWithName:(id)name readBlock:(id)block writeBlock:(id)block3 threshold:(float)threshold;
@end

