/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "POPAnimatableProperty.h"

@class NSString;

@interface POPMutableAnimatableProperty : POPAnimatableProperty {
	NSString* name;
	id readBlock;
	id writeBlock;
	float threshold;
}
@property(assign, nonatomic) float threshold;
@property(copy, nonatomic) id writeBlock;
@property(copy, nonatomic) id readBlock;
@property(copy, nonatomic) NSString* name;
-(void).cxx_destruct;
@end

