/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class CMMDB, NSRecursiveLock;
@protocol NotifyFromPrtlDelegate;

@interface PrtlBase : XXUnknownSuperclass {
	unsigned long m_uiUin;
	unsigned long m_uiScene;
	unsigned long m_uiCgi;
	NSRecursiveLock* m_oLock;
	CMMDB* m_oMMDB;
	id<NotifyFromPrtlDelegate> m_delNotifyFromPrtl;
}
@property(assign, nonatomic) __weak id<NotifyFromPrtlDelegate> m_delNotifyFromPrtl;
@property(retain, nonatomic) NSRecursiveLock* m_oLock;
@property(retain, nonatomic) CMMDB* m_oMMDB;
@property(assign, nonatomic) unsigned long m_uiCgi;
@property(assign, nonatomic) unsigned long m_uiScene;
@property(assign, nonatomic) unsigned long m_uiUin;
-(void).cxx_destruct;
-(BOOL)CustomEncryptPack:(void*)pack outbuf:(AutoBuffer*)outbuf;
-(BOOL)HasCustomEncryptPack;
-(void)GetRespKey:(AutoBuffer*)key;
-(void)GetReqKey:(AutoBuffer*)key;
-(BOOL)HandleResp:(void*)resp;
-(void)InitReq:(void*)req;
-(void)InitPrtl:(unsigned long)prtl Delegate:(id)delegate DB:(id)db Lock:(id)lock Scene:(unsigned long)scene;
-(void)dealloc;
-(id)init;
@end

