/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMService.h"
#import "GetA8KeyLogicDelegate.h"
#import "IMsgExt.h"
#import "MMKernelExt.h"
#import "MMService.h"

@class GetA8KeyLogic, NSString;

@interface PushLoginURLMgr : MMService <IMsgExt, GetA8KeyLogicDelegate, MMKernelExt, MMService> {
	GetA8KeyLogic* _getA8KeyLogic;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
+(void)clearOneClickLoginInfo;
+(BOOL)shouldShowOneClickLogin;
-(void).cxx_destruct;
-(void)onManulLogOut;
-(void)onGetA8KeyOneClickLoginWithURL:(id)url extraInfo:(id)info;
-(void)OnGetNewXmlMsg:(id)msg Type:(id)type MsgWrap:(id)wrap;
-(id)getGetA8KeyLogic;
-(void)dealloc;
-(id)init;
@end

