/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


__attribute__((visibility("hidden")))
@interface QBaseView : XXUnknownSuperclass {
}
-(id)initWithFrame:(CGRect)frame;
-(void)drawRect:(CGRect)rect;
@end

