/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "QShape.h"


__attribute__((visibility("hidden")))
@interface QMultiPoint : QShape {
	XXStruct_gLbvpC* _points;
	unsigned _pointCount;
	XXStruct_Yvvv9D _boundingRect;
}
@property(readonly, assign, nonatomic) unsigned pointCount;
@property(readonly, assign, nonatomic) XXStruct_gLbvpC* points;
-(void)dealloc;
-(id)initWithCoordinates:(XXStruct_gLbvpC*)coordinates count:(unsigned)count;
-(id)initWithPoints:(XXStruct_gLbvpC*)points count:(unsigned)count;
-(void)getCoordinates:(XXStruct_gLbvpC*)coordinates range:(NSRange)range;
-(void)calculateBoundingMapRect;
@end

