/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMUIView.h"

@class NSMutableArray;
@protocol QQEmojiGridViewDelegate;

@interface QQEmojiGridView : MMUIView {
	NSMutableArray* m_emoticonWrapArray;
	int m_column;
	int m_row;
	NSMutableArray* m_emoticonViewArray;
	float m_itemWidth;
	float m_itemHeight;
	float m_edgeTop;
	float m_edgeLeft;
	float m_intervalX;
	float m_intervalY;
	id<QQEmojiGridViewDelegate> m_delegate;
}
@property(assign, nonatomic) __weak id<QQEmojiGridViewDelegate> m_delegate;
@property(retain, nonatomic) NSMutableArray* m_emoticonViewArray;
@property(assign, nonatomic) float m_intervalY;
@property(assign, nonatomic) float m_intervalX;
@property(assign, nonatomic) float m_edgeLeft;
@property(assign, nonatomic) float m_edgeTop;
@property(assign, nonatomic) float m_itemHeight;
@property(assign, nonatomic) float m_itemWidth;
@property(assign, nonatomic) int m_row;
@property(assign, nonatomic) int m_column;
@property(retain, nonatomic) NSMutableArray* m_emoticonWrapArray;
-(void).cxx_destruct;
-(void)touchesEnded:(id)ended withEvent:(id)event;
-(int)getRealIndexFromPoint:(CGPoint)point;
-(void)onLongPressOnEmoticon:(id)emoticon;
-(void)reloadData;
-(void)calculateLayout;
-(id)cellKey;
-(void)setGridViewDelegate:(id)delegate;
-(id)initWithFrame:(CGRect)frame;
-(void)dealloc;
@end

