/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class SKBuiltinString_t;

@interface RcptInfoNode : WXPBGeneratedMessage {
}
@property(retain, nonatomic) SKBuiltinString_t* nationalcodeGbt2260;
@property(retain, nonatomic) SKBuiltinString_t* phone;
@property(retain, nonatomic) SKBuiltinString_t* name;
@property(retain, nonatomic) SKBuiltinString_t* detail;
@property(retain, nonatomic) SKBuiltinString_t* zipcode;
@property(retain, nonatomic) SKBuiltinString_t* district;
@property(retain, nonatomic) SKBuiltinString_t* city;
@property(retain, nonatomic) SKBuiltinString_t* province;
@property(retain, nonatomic) SKBuiltinString_t* country;
@property(assign, nonatomic) unsigned id;
+(void)initialize;
@end

