/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class SKBuiltinBuffer_t, BaseRequest;

@interface RcptInfoImportYiXunRequest : WXPBGeneratedMessage {
}
@property(retain, nonatomic) SKBuiltinBuffer_t* newA2Key;
@property(retain, nonatomic) SKBuiltinBuffer_t* a2Key;
@property(assign, nonatomic) unsigned qq;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

