/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIFont, UIColor;

@interface ReaderStyleWrap : XXUnknownSuperclass {
	UIColor* m_color;
	UIFont* m_font;
	BOOL m_bUnderline;
	NSRange m_range;
}
@property(assign, nonatomic) NSRange m_range;
@property(assign, nonatomic) BOOL m_bUnderline;
@property(retain, nonatomic) UIFont* m_font;
@property(retain, nonatomic) UIColor* m_color;
-(void).cxx_destruct;
-(int)compare:(id)compare;
@end

