/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PBMessageObserverDelegate.h"
#import "MMObject.h"

@class NSMutableArray, NSArray, NSMutableDictionary;

@interface RecommendAppsLogicImpl : MMObject <PBMessageObserverDelegate> {
	NSArray* _recommendAppsList;
	NSMutableArray* _tempList;
	BOOL _isUpdating;
	BOOL _isGettingIcon;
	NSMutableDictionary* _updateIconDic;
	unsigned long _lastUpdateTime;
}
-(void).cxx_destruct;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(BOOL)handleGetAppIconRsp:(id)rsp;
-(void)handleNotShowNewLogic;
-(void)handleUpdateRecommendAppsListWithOffsetResp:(id)offsetResp;
-(void)addNewItemToUpdateIconDicAndStartUpdate;
-(BOOL)makeUrlRequest:(id)request userData:(id)data;
-(void)getAppIcon:(id)icon appID:(id)anId;
-(void)checkAndUpdateAppIcon;
-(void)clearRcmApps;
-(void)setRecommendAppNotShowNew:(id)aNew;
-(id)GetPathOfRecommendAppIcon:(id)recommendAppIcon IconUrl:(id)url;
-(void)saveRecommendAppsList;
-(void)loadRecommendAppsListFromFile;
-(id)getAppInfoDataRootDir;
-(BOOL)updateRecommendAppsListWithOffset:(unsigned long)offset;
-(BOOL)updateRecommendAppsList;
-(id)getRecommendAppsList;
-(void)dealloc;
-(id)init;
@end

