/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface RecoverDataItem : XXUnknownSuperclass {
	NSString* m_nsDescription;
	unsigned long m_dataType;
	unsigned long m_operationType;
	NSString* m_nsPath;
}
@property(retain, nonatomic) NSString* m_nsPath;
@property(assign, nonatomic) unsigned long m_operationType;
@property(assign, nonatomic) unsigned long m_dataType;
@property(retain, nonatomic) NSString* m_nsDescription;
-(void).cxx_destruct;
-(id)description;
-(id)init;
@end

