/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCActionSheetDelegate.h"
#import "UITextFieldDelegate.h"
#import "UITextViewDelegate.h"
#import "WeChat-Structs.h"
#import "MMImagePickerManagerDelegate.h"
#import "UIAlertViewDelegate.h"
#import "ContactRemarkImgExt.h"
#import "CommonImageBrowserDelegate.h"
#import "MMUIViewController.h"
#import "MMTableViewInfoDelegate.h"

@class UILabel, UIView, UIImageView, NSString, ContactRemarkLogic, MMTableViewSectionInfo, CContact, NSMutableDictionary, UIImage, UITextView, MMTableViewInfo, NSMutableArray, UITextField;

@interface RemarkViewController : MMUIViewController <ContactRemarkImgExt, UITextViewDelegate, UITextFieldDelegate, WCActionSheetDelegate, MMImagePickerManagerDelegate, CommonImageBrowserDelegate, UIAlertViewDelegate, MMTableViewInfoDelegate> {
	MMTableViewInfo* m_tableViewInfo;
	MMTableViewSectionInfo* m_phoneSection;
	MMTableViewSectionInfo* m_descSection;
	NSMutableArray* m_arrPhoneItem;
	ContactRemarkLogic* m_logic;
	CContact* m_contact;
	UIImage* m_cardImg;
	UITextField* m_nameView;
	UITextView* m_descView;
	UILabel* m_descHint;
	UIView* m_tagView;
	UIImageView* m_imageView;
	NSMutableDictionary* m_phoneEdit;
	int m_firstResponderIndex;
	BOOL m_downloadingImg;
	BOOL m_isDownloadFail;
	BOOL m_hasEditImg;
	BOOL m_needEditState;
	BOOL m_deleteHashPhone;
	NSString* m_recommandRemark;
	BOOL m_bNeedReloadSubviews;
	BOOL m_bIsRemarkEdit;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* recommandRemark;
@property(retain, nonatomic) CContact* m_contact;
@property(assign, nonatomic) BOOL needEditState;
-(void).cxx_destruct;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)scrollRectToVisibleForView:(id)view;
-(void)textViewDidBeginEditing:(id)textView;
-(void)adjustDescTextView;
-(void)textViewDidChange:(id)textView;
-(BOOL)textView:(id)view shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(BOOL)textFieldShouldClear:(id)textField;
-(void)executeOpLog;
-(void)onDownloadCardImg:(id)img;
-(void)onUploadCardImgFinish:(id)finish returnUrl:(id)url;
-(void)uploadCardImg;
-(void)onPerformEdit;
-(BOOL)checkEdit;
-(id)checkEditPhone;
-(void)MMImagePickerManagerDidCancel:(id)mmimagePickerManager;
-(void)MMImagePickerManager:(id)manager didFinishPickingImageWithInfo:(id)info;
-(void)showImagePicker:(int)picker;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)deleteImage;
-(void)onDeleteItemAtIndex:(unsigned)index;
-(void)onDeleteImage;
-(void)showImg:(id)img;
-(void)showTagEdit;
-(void)useRecommandRemark;
-(void)hideKeyboard;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)textFieldTextDidChange:(id)textFieldText;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)onDismissRemarkView:(id)view;
-(void)dealloc;
-(void)reflashImageCell;
-(id)makeRecommBtnView;
-(BOOL)needRecommBtn;
-(void)onModifyContact:(id)contact;
-(id)getRemarkText;
-(void)viewDidAppear:(BOOL)view;
-(void)viewDidLayoutSubviews;
-(void)makeRemarkCell:(id)cell CellInfo:(id)info;
-(void)makeTagsCell:(id)cell CellInfo:(id)info;
-(void)makeDescriptionCell:(id)cell CellInfo:(id)info;
-(void)makeDescView;
-(void)fixDescViewHeight:(float)height;
-(void)makeImageCell:(id)cell CellInfo:(id)info;
-(void)makeImageView;
-(void)dottedLine:(id)line;
-(void)makePhoneCell:(id)cell CellInfo:(id)info;
-(void)showPhoneTip;
-(void)onAddPhone;
-(void)commitEditingForRowAtIndexPath:(id)indexPath Cell:(id)cell;
-(id)getPhoneTextFieldAt:(int)at;
-(id)getPhoneItemInfoAt:(unsigned)at;
-(void)reloadTableView;
-(void)viewDidLoad;
-(void)startDownCardImg;
-(id)init;
@end

