/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"

@class NSThread, NSRecursiveLock;
@protocol ResourceMonitorDelegate;

@interface ResourceMonitor : MMObject {
	id<ResourceMonitorDelegate> _delegate;
	NSThread* _monitorThread;
	NSRecursiveLock* _lock;
	BOOL _monitoring;
	int m_nCnt;
}
@property(assign, nonatomic) __weak id<ResourceMonitorDelegate> delegate;
-(void).cxx_destruct;
-(void)dealloc;
-(id)init;
-(void)startService;
-(void)threadFunc;
-(void)updateResourceInfo:(id)info;
-(void)stopService;
@end

