/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMUIViewController.h"

@class UITextField;

@interface ResourcePathViewController : MMUIViewController {
	UITextField* typeTextFiled;
	UITextField* subTypeTextFiled;
}
-(void).cxx_destruct;
-(void)OnButtondone;
-(void)didReceiveMemoryWarning;
-(void)viewDidLoad;
@end

