/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"

@class NSString;

@interface RightTopMenuItemBtnData : MMObject {
	NSString* m_nsID;
	NSString* m_nsTitleID;
	NSString* m_nsImageName;
	unsigned m_actionType;
	NSString* m_nsActionName;
	NSString* m_nsPluginUserName;
}
@property(retain, nonatomic) NSString* m_nsPluginUserName;
@property(retain, nonatomic) NSString* m_nsActionName;
@property(assign, nonatomic) unsigned m_actionType;
@property(retain, nonatomic) NSString* m_nsImageName;
@property(retain, nonatomic) NSString* m_nsTitleID;
@property(retain, nonatomic) NSString* m_nsID;
+(id)genItemWithID:(id)anId title:(id)title imageName:(id)name actionType:(unsigned)type actionName:(id)name5 pluginUserName:(id)name6;
-(void).cxx_destruct;
-(id)init;
@end

