/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSMutableDictionary;

@interface ScanHistoryLogicHelper : XXUnknownSuperclass {
	NSMutableDictionary* _dicItems;
	NSMutableArray* _arrSortedKeyByTime;
	NSMutableArray* _arrSortedItems;
}
+(id)GetCachePath;
+(BOOL)isExistScanHistory;
-(void).cxx_destruct;
-(id)arrHistoryItems;
-(unsigned)historyCount;
-(void)cleanAllData;
-(void)removeItem:(unsigned)item;
-(id)itemCreateTime:(unsigned)time;
-(void)addItem:(id)item withDataID:(id)dataID andType:(unsigned)type;
-(void)SaveDataToFile;
-(void)LoadDataFromFile;
-(id)init;
@end

