/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "BaseScanLogicController.h"
#import "ShakeLogicProxyDelegate.h"

@class ShakeTvLogicController, NSString;

@interface ScanTVLogicController : BaseScanLogicController <ShakeLogicProxyDelegate> {
	BOOL _shouldShowScanAnimation;
	ShakeTvLogicController* _logicController;
	NSString* _alertText;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* alertText;
-(void).cxx_destruct;
-(void)onShakeTvReportFail:(int)fail ErrMsg:(id)msg;
-(void)onShakeTvReportEndWithTvItem:(id)tvItem;
-(void)showShakeTvResult:(id)result andModal:(BOOL)modal;
-(void)showTvDetail:(id)detail;
-(BOOL)shouldStartScanAnimation;
-(id)getInfoText;
-(id)getAlertText;
-(CGRect)getDrawCropRect;
-(void)stopScan;
-(void)startScan;
-(id)init;
@end

