/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class LbsLocationNew;

@interface SearchGuideRequest : WXPBGeneratedMessage {
}
@property(assign, nonatomic) unsigned long long businessType;
@property(retain, nonatomic) LbsLocationNew* location;
@property(assign, nonatomic) unsigned h5Version;
@property(assign, nonatomic) unsigned scene;
+(void)initialize;
@end

