/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ContactSelectViewDelegate.h"
#import "MMSearchBarDisplayController.h"
#import "SelectContactsViewControllerDelegate.h"

@class UIView, ContactSelectView, NSString;

@interface SelectContactsViewController : MMSearchBarDisplayController <SelectContactsViewControllerDelegate, ContactSelectViewDelegate> {
	id<SelectContactsViewControllerDelegate> m_delegate;
	UIView* m_titleView;
	unsigned long m_uiScene;
	ContactSelectView* m_selectView;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned long m_uiScene;
@property(assign, nonatomic) __weak id<SelectContactsViewControllerDelegate> m_delegate;
-(void).cxx_destruct;
-(BOOL)onFilterContactCandidate:(id)candidate;
-(void)onSelectContact:(id)contact;
-(void)onSelectBrandContact;
-(void)onSelectContactReturn:(id)aReturn atScene:(unsigned long)scene;
-(void)dealloc;
-(void)viewDidUnload;
-(void)viewDidLoad;
-(void)initView;
-(void)initTitleArea;
-(void)onCancelBack:(id)back;
-(id)init;
@end

