/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NSString, BaseRequest, AppMsg;

@interface SendAppMsgRequest : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* md5;
@property(assign, nonatomic) unsigned reqTime;
@property(retain, nonatomic) NSString* commentUrl;
@property(retain, nonatomic) AppMsg* msg;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

