/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface SendSightRequest_ToUser : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* username;
+(void)initialize;
@end

