/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray;

@interface SequenceAnimationObject : XXUnknownSuperclass {
	BOOL _m_isAnimating;
	NSMutableArray* _m_animations;
}
@property(retain, nonatomic) NSMutableArray* m_animations;
@property(assign, nonatomic) BOOL m_isAnimating;
-(void).cxx_destruct;
-(void)doNextAnimation;
-(void)addAnimationWithDuration:(double)duration delay:(double)delay options:(unsigned)options animations:(id)animations completion:(id)completion;
-(id)init;
@end

