/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PasswordLogicDelegate.h"
#import "VerifyPhoneDelegate.h"
#import "WeChat-Structs.h"
#import "IMMFacebookMgrExt.h"
#import "MMUIViewController.h"
#import "IQQAccountMgrExt.h"
#import "IUpdateProfileMgrExt.h"
#import "VoicePrintSwitchOpDelegate.h"
#import "settingModifyEmailDelegate.h"
#import "settingModifyAliasDelegate.h"
#import "WCAccountSetPasswordViewControllerDelegate.h"
#import "ICertInfoMgrExt.h"

@class PasswordLogic, NSString, CertInfo, VPSwitchOpCgi, MMTableViewInfo;

@interface SettingMyAccountInfoViewController : MMUIViewController <VoicePrintSwitchOpDelegate, VerifyPhoneDelegate, ICertInfoMgrExt, IMMFacebookMgrExt, WCAccountSetPasswordViewControllerDelegate, PasswordLogicDelegate, settingModifyEmailDelegate, IQQAccountMgrExt, settingModifyAliasDelegate, IUpdateProfileMgrExt> {
	map<unsigned int, unsigned int, std::__1::less<unsigned int>, std::__1::allocator<std::__1::pair<const unsigned int, unsigned int> > > m_mapCellToCellType;
	CertInfo* m_certInfo;
	PasswordLogic* m_passwdLogic;
	MMTableViewInfo* m_tableViewInfo;
	VPSwitchOpCgi* m_switchOpCgiHandle;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(id).cxx_construct;
-(void).cxx_destruct;
-(void)initDeepLinkConfig;
-(void)OnSwitchOpErrorWithScene:(unsigned long)scene andErrorCode:(int)code;
-(void)OnSwitchOp:(int)op andSwitch:(int)aSwitch withScene:(unsigned long)scene;
-(void)saveNewAlias;
-(void)willShow;
-(void)onProfileChange;
-(void)OnUnBindQQOK;
-(void)onUnBindFacebookFinish:(unsigned long)finish;
-(void)onBindFacebookFinish:(unsigned long)finish;
-(void)ReloadData;
-(void)onSetPasswordOK;
-(void)onSetPasswordBack;
-(void)unknownFail;
-(void)checkHaveNotSetPassword;
-(void)checkHaveSetPassword;
-(void)setPasswordOK;
-(void)passwordLogicPause;
-(void)passwordLogicStart;
-(void)passwordLogicCancel;
-(void)verifyPasswordOK:(id)ok;
-(void)verifyPasswordFail;
-(void)openSecurityCenter;
-(void)setSaveDevice;
-(void)setVoicePrint;
-(void)setPassword;
-(void)modifyEmail;
-(void)showSetPassword:(id)password;
-(void)showModifyEmailView:(BOOL)view;
-(void)showFacebook;
-(void)showWhatsVView;
-(void)bindPhoneReturn;
-(void)showBindPhone;
-(void)showModifyQQView;
-(void)saveNewEmail;
-(void)makeVInfoCell:(id)cell;
-(void)makeSafeDeviceCell:(id)cell cellInfo:(id)info;
-(void)OnUpdateCertInfo;
-(void)dealloc;
-(void)viewDidLoad;
-(void)viewDidLayoutSubviews;
-(void)undoRegester;
-(void)doRegester;
-(void)reloadTableData;
-(void)initDeleteAccountCellData;
-(void)initVerifyCellData;
-(void)initSecurityCellData;
-(void)initAccountCellData;
-(void)initWeChatIDView;
-(void)showModifyUserName;
-(int)getLinesForV:(id)v;
@end

