/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCoding.h"

@class WCLocationInfo, SnsObject, MyWCDB, NSDate, NSMutableArray, NSString;

@interface SEWCUploadTask : XXUnknownSuperclass <NSCoding> {
	NSString* serverID;
	NSString* clientID;
	BOOL isPrivate;
	NSMutableArray* sharedGroupIDS;
	int type;
	NSString* title;
	NSString* desc;
	NSString* contentDesc;
	int contentDescShowType;
	int contentDescScene;
	NSMutableArray* withUserList;
	NSMutableArray* blackUserList;
	NSMutableArray* mediaList;
	SnsObject* snsObj;
	BOOL isSyncToWeibo;
	BOOL isSyncToFacebook;
	BOOL isSyncToTwitter;
	BOOL isSyncToQZone;
	NSString* linkUrl;
	NSString* statisticsData;
	NSString* sourceUserName;
	NSString* sourceNickName;
	NSDate* createTime;
	int uploadResult;
	int BGImgSetType;
	BOOL isUploadFailed;
	int postSource;
	NSString* twitterOAuthToken;
	NSString* twitterOAuthTokenSecret;
	BOOL isDeleted;
	WCLocationInfo* locationInfo;
	NSMutableArray* sharedGroupIDs;
	MyWCDB* wcdb;
}
@property(retain, nonatomic) MyWCDB* wcdb;
@property(retain, nonatomic) WCLocationInfo* locationInfo;
@property(assign, nonatomic) BOOL isDeleted;
@property(retain, nonatomic) NSString* sourceNickName;
@property(retain, nonatomic) NSString* sourceUserName;
@property(retain, nonatomic) NSString* statisticsData;
@property(retain, nonatomic) NSString* twitterOAuthTokenSecret;
@property(retain, nonatomic) NSString* twitterOAuthToken;
@property(assign, nonatomic) int postSource;
@property(assign, nonatomic) BOOL isUploadFailed;
@property(assign, nonatomic) int BGImgSetType;
@property(assign, nonatomic) int uploadResult;
@property(retain, nonatomic) NSDate* createTime;
@property(retain, nonatomic) NSString* linkUrl;
@property(assign, nonatomic) BOOL isSyncToQZone;
@property(assign, nonatomic) BOOL isSyncToTwitter;
@property(assign, nonatomic) BOOL isSyncToFacebook;
@property(assign, nonatomic) BOOL isSyncToWeibo;
@property(assign, nonatomic) int contentDescScene;
@property(assign, nonatomic) int contentDescShowType;
@property(retain, nonatomic) NSString* contentDesc;
@property(retain, nonatomic) SnsObject* snsObj;
@property(retain, nonatomic) NSMutableArray* mediaList;
@property(retain, nonatomic) NSMutableArray* withUserList;
@property(retain, nonatomic) NSMutableArray* blackUserList;
@property(retain, nonatomic) NSString* desc;
@property(retain, nonatomic) NSString* title;
@property(retain, nonatomic) NSMutableArray* sharedGroupIDs;
@property(assign, nonatomic) int type;
@property(assign, nonatomic) BOOL isPrivate;
@property(retain, nonatomic) NSString* clientID;
@property(retain, nonatomic) NSString* serverID;
-(void).cxx_destruct;
-(id)convert2WCUploadTask;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(void)dealloc;
-(id)init;
@end

