/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMUIView.h"

@class MMUIButton;
@protocol ShakeTypeBarDelegate;

@interface ShakeTypeBar : MMUIView {
	MMUIButton* m_shakeCardBtn;
	MMUIButton* m_shakeBeaconBtn;
	MMUIButton* m_shakePeopleBtn;
	MMUIButton* m_shakeMusicBtn;
	MMUIButton* m_shakeTVBtn;
	unsigned long m_curSelectTag;
	id<ShakeTypeBarDelegate> m_delegate;
	BOOL isShowBeacon;
	BOOL isShowPeople;
	BOOL isShowShakeTV;
	BOOL isShowShakeCard;
	BOOL isShowShakeMusic;
	unsigned long uiBtnCount;
	BOOL _isUserClickedBtn;
}
@property(assign, nonatomic) BOOL isUserClickedBtn;
@property(assign, nonatomic) __weak id<ShakeTypeBarDelegate> m_delegate;
-(void).cxx_destruct;
-(void)layoutAllShakeBtnWithAnimation:(BOOL)animation;
-(void)showShakeCardBtn;
-(void)showBeaconBtnWithSelected:(BOOL)selected withAnimation:(BOOL)animation;
-(void)updateSelfState;
-(void)setShakeCardBtnWhetherShowRedDot:(BOOL)dot;
-(void)processBtnClicked:(id)clicked;
-(void)onBtnClicked:(id)clicked;
-(void)layoutBtnSubview:(id)subview;
-(id)createBtnWithTitle:(id)title Icon:(id)icon HighlightIcon:(id)icon3 Frame:(CGRect)frame Action:(SEL)action Tag:(int)tag;
-(void)setShakeType:(int)type;
-(void)initView;
-(unsigned long)getXOffset:(unsigned long)offset;
-(unsigned long)getBtnWidth:(unsigned long)width;
-(void)updateData;
-(BOOL)shouldAlwaysShowBeaconTab;
-(id)init;
@end

