/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol ShakeMainFrameDelegate
-(void)OnOpenUnreadMsgList;
-(int)getShakeLogicType;
-(id)getMsgForState:(unsigned long)state;
-(void)OnOpenSayHello;
-(void)OnAnimationEnd:(BOOL)end;
@end

