/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol ShakeMgrExt
@optional
-(void)onShakeMsgUnreadCountChanged;
-(void)onShakeTvStorageChanged;
-(void)onShakeBeaconStorageChanged;
-(void)onShakeMusicStorageChanged;
-(void)OnShakeShareCountChanged;
-(void)onShakePageStorageChanged;
-(void)onShakePeopleStorageChanged;
-(void)onShakeStatusChanged;
@end

