/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMConfigMgrExt.h"
#import "MMService.h"
#import "CLLocationManagerDelegate.h"
#import "MMService.h"
#import "CBCentralManagerDelegate.h"

@class NSMutableArray, NSArray, NSString, CLLocationManager, NSMutableDictionary, CBCentralManager;

@interface ShakeRangingBeaconsMgr : MMService <CLLocationManagerDelegate, CBCentralManagerDelegate, MMConfigMgrExt, MMService> {
	BOOL _isHaveShowed;
	CLLocationManager* _locationManager;
	CBCentralManager* _manager;
	NSMutableDictionary* _beaconsDict;
	NSArray* _uuidsArr;
	double _startRangingTime;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) double startRangingTime;
@property(retain, nonatomic) NSArray* uuidsArr;
@property(retain) NSMutableDictionary* beaconsDict;
@property(retain, nonatomic) CBCentralManager* manager;
@property(retain) CLLocationManager* locationManager;
@property(assign) BOOL isHaveShowed;
@property(readonly, assign) NSMutableArray* beacons;
-(void).cxx_destruct;
-(void)onMMConfigUpdated;
-(void)centralManagerDidUpdateState:(id)centralManager;
-(BOOL)haveStartRangingRegion:(id)region;
-(void)registerRangingRegions;
-(void)detectBluetoothAvailable;
-(id)keyForBeacon:(id)beacon;
-(void)locationManager:(id)manager didFailWithError:(id)error;
-(void)locationManager:(id)manager rangingBeaconsDidFailForRegion:(id)rangingBeacons withError:(id)error;
-(void)locationManager:(id)manager didRangeBeacons:(id)beacons inRegion:(id)region;
-(BOOL)isDeviceBLEPowerOn;
-(void)stopRanging;
-(void)startRanging;
-(void)setupUUIDs;
-(id)init;
-(void)dealloc;
-(id)loadGatedLaunchOptionsFromFile;
-(BOOL)saveGatedLaunchOptions:(id)options;
-(id)gatedLaunchOptionFilePath;
@end

