/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol ShakeLogicProxyDelegate <NSObject>
@optional
-(void)onShakeStop;
-(void)onShakeCardReportEndWithResponse:(id)response errType:(unsigned)type errMsg:(id)msg;
-(void)onBeaconGuideModeReportFailed:(unsigned long)failed;
-(void)onBeaconGuideModeReportEndWithResponse:(id)response;
-(void)onShakeBeaconReportFailed:(int)failed ErrMsg:(id)msg;
-(void)onShakeBeaconReportEndWithResponse:(id)response;
-(void)onShakeTvReportFail:(int)fail ErrMsg:(id)msg;
-(void)onShakeTvReportEndWithTvItem:(id)tvItem;
-(void)onShakeMusicReportFail:(int)fail ErrMsg:(id)msg;
-(void)onShakeMusicReportEndWithMusicItem:(id)musicItem Offset:(float)offset;
-(void)onShakeGetFail:(id)fail;
-(void)onShakeReportFail:(id)fail;
-(void)onShakeGetEndWithResult:(id)result;
-(void)onShakeReportEndWithResult:(id)result;
@end

