/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ShakeCheckerDelegate.h"
#import "MMObject.h"

@class MMUIWindow, NSString, CShakeChecker;
@protocol ShakeControllerDelegate;

@interface ShakeController : MMObject <ShakeCheckerDelegate> {
	CShakeChecker* _shakeChecker;
	BOOL _bIsShakeViewShow;
	MMUIWindow* _shakeWindow;
	id<ShakeControllerDelegate> _shakeControllerDelegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<ShakeControllerDelegate> shakeControllerDelegate;
-(void).cxx_destruct;
-(void)setForceEarpieceMode:(BOOL)mode;
-(void)OnShake;
-(void)onCancel:(id)cancel;
-(void)onConfirm:(id)confirm;
-(void)onTouchBackground:(id)background;
-(void)hideWindowAnimated:(BOOL)animated;
-(void)showWindowAnimated:(BOOL)animated;
-(void)StopShakeCheck;
-(void)StartShakeCheck;
-(void)Reset;
-(void)UnRegister;
-(void)Register;
-(id)init;
-(BOOL)isEarEnabled;
@end

