/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ShareConfirmViewDelegate.h"
#import "MMObject.h"

@class NSDictionary, ShareConfirmView, NSData, NSString, FavoritesItem;
@protocol ShareFavoritesConfirmLogicHelperDelegate;

@interface ShareFavoritesConfirmLogicHelper : MMObject <ShareConfirmViewDelegate> {
	ShareConfirmView* _confirmView;
	FavoritesItem* _favItem;
	id<ShareFavoritesConfirmLogicHelperDelegate> _delegate;
	NSString* _thumbImageUrl;
	BOOL _hasBeenHidden;
	NSDictionary* _userData;
	NSData* _thumbData;
	NSData* _fileData;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSData* fileData;
@property(retain, nonatomic) NSData* thumbData;
@property(retain, nonatomic) NSDictionary* userData;
@property(retain, nonatomic) NSString* thumbImageUrl;
@property(retain, nonatomic) FavoritesItem* favItem;
@property(assign, nonatomic) __weak id<ShareFavoritesConfirmLogicHelperDelegate> delegate;
-(void).cxx_destruct;
-(void)OnBackToApp:(id)app;
-(void)OnError:(id)error;
-(void)OnCancel:(id)cancel;
-(void)OnSend:(id)send;
-(void)layoutSubviewToOrientation:(int)orientation;
-(void)rotateToOrientaion:(int)orientaion;
-(void)rotateToCurrentOrietation;
-(void)hideConfirmView;
-(void)showConfirmView;
-(void)dealloc;
-(id)initWithFavoritesItem:(id)favoritesItem;
@end

