/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class ShareTag, NSMutableArray, NSString, BaseRequest;

@interface ShareCardItemRequest : WXPBGeneratedMessage {
}
@property(assign, nonatomic) unsigned fromScene;
@property(retain, nonatomic) ShareTag* shareTag;
@property(retain, nonatomic) NSString* consumedboxCardId;
@property(retain, nonatomic) NSString* appUserName;
@property(retain, nonatomic) NSMutableArray* items;
@property(assign, nonatomic) unsigned isShareOwncard;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

