/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library


@interface SightGradientView : XXUnknownSuperclass {
}
-(id)initWithFrame:(CGRect)frame color:(id)color alphaTop:(float)top alphaBottom:(float)bottom;
@end

