/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDataSource.h"
#import "MMUIView.h"

@class NSMutableArray, UICollectionView, SightPlayerView, UIView, NSString;
@protocol SightDraftBoxDelegate;

@interface SightDraftBoxView : MMUIView <UICollectionViewDataSource, UICollectionViewDelegate> {
	UICollectionView* m_container;
	NSMutableArray* m_dataAry;
	NSMutableArray* m_selectedAry;
	NSMutableArray* m_itemViewAry;
	int m_selectedItem;
	SightPlayerView* m_selectedPlayer;
	UIView* m_previewContent;
	BOOL m_editMode;
	BOOL m_leaveEditMode;
	float m_itemWidth;
	id<SightDraftBoxDelegate> _delegate;
	NSString* _selectTag;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* selectTag;
@property(assign, nonatomic) __weak id<SightDraftBoxDelegate> delegate;
-(void).cxx_destruct;
-(void)reflashState;
-(void)scrollToBottom:(BOOL)bottom;
-(void)reloadContent;
-(void)confirmDeleted;
-(void)undoDeleted;
-(void)leaveEditMode;
-(void)enterEditMode;
-(BOOL)isInEditMode;
-(id)getPreviewClickAnimation;
-(id)getClickAnimation;
-(void)switchItemSelected:(int)selected withView:(id)view;
-(void)onDeleteButton:(id)button;
-(void)onItemLongClick:(id)click;
-(void)setItemSelected:(int)selected;
-(void)onSelectItem:(id)item;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)reloadContainer;
-(void)clearPlayer;
-(id)makeCell:(int)cell;
-(id)collectionView:(id)view cellForItemAtIndexPath:(id)indexPath;
-(int)collectionView:(id)view numberOfItemsInSection:(int)section;
-(int)numberOfSectionsInCollectionView:(id)collectionView;
-(void)setTopInset:(float)inset;
-(id)collectionView:(id)view viewForSupplementaryElementOfKind:(id)kind atIndexPath:(id)indexPath;
-(CGSize)collectionView:(id)view layout:(id)layout referenceSizeForFooterInSection:(int)section;
-(void)makeContainer;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

