/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMUIView.h"

@class CAGradientLayer, UIImageView;

@interface SightFileMaskView : MMUIView {
	UIImageView* _iconView;
	CAGradientLayer* _overlayLayer;
}
@property(retain, nonatomic) CAGradientLayer* overlayLayer;
@property(retain, nonatomic) UIImageView* iconView;
+(id)getIconView;
-(void).cxx_destruct;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

