/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class SKBuiltinBuffer_t, NSString;

@interface SnsAction : WXPBGeneratedMessage {
}
@property(retain, nonatomic) SKBuiltinBuffer_t* hbbuffer;
@property(assign, nonatomic) unsigned long long commentId2;
@property(assign, nonatomic) unsigned long long replyCommentId2;
@property(assign, nonatomic) unsigned isNotRichText;
@property(assign, nonatomic) int commentId;
@property(assign, nonatomic) int replyCommentId;
@property(retain, nonatomic) NSString* content;
@property(assign, nonatomic) unsigned createTime;
@property(assign, nonatomic) unsigned source;
@property(assign, nonatomic) unsigned type;
@property(retain, nonatomic) NSString* toNickname;
@property(retain, nonatomic) NSString* fromNickname;
@property(retain, nonatomic) NSString* toUsername;
@property(retain, nonatomic) NSString* fromUsername;
+(void)initialize;
@end

