/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class SKBuiltinString_t, NSString, SnsActionGroup, BaseRequest;

@interface SnsADCommentRequest : WXPBGeneratedMessage {
}
@property(retain, nonatomic) SKBuiltinString_t* snsAduxInfo;
@property(retain, nonatomic) NSString* clientId;
@property(retain, nonatomic) SnsActionGroup* action;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

