/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class SKBuiltinBuffer_t, NSString;

@interface SnsHBUserInfo : WXPBGeneratedMessage {
}
@property(retain, nonatomic) SKBuiltinBuffer_t* hbbuffer;
@property(assign, nonatomic) unsigned createTime;
@property(retain, nonatomic) NSString* username;
+(void)initialize;
@end

