/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NSString;

@interface SortItem : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* name;
@property(assign, nonatomic) unsigned sortId;
+(void)initialize;
@end

