/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol SPXAudioPlayerDelegate
@optional
-(BOOL)OnSPXEndDontNotifyOtherApp;
-(void)OnSPXEarTip;
-(void)OnSPXEndPlaying:(id)playing isForceStop:(BOOL)stop;
-(void)OnSPXBeginPlaying:(id)playing ErrNo:(int)no;
-(void)OnSPXLevelMeter:(id)meter Peak:(float)peak;
@end

