/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface StoreEmotionUtil : XXUnknownSuperclass {
}
+(unsigned)GetSearchTemplateVesionFromConfigFileInDir:(id)dir;
+(id)GetPathOfRewardTipsStatisticsDataFile;
+(id)getEmotionRewardInfoCacheForPid:(id)pid;
+(id)getEmotionRewardInfoCacheDir;
+(id)getUserEmotionCommonDataDir;
+(id)GetDownloadPathOfEmotionSearchDir;
+(id)GetDownloadPathOfEmotionSearchTempDir;
+(id)GetDefaultPathOfEmotionSearchDir;
+(id)GetDownloadingPathOfEmoticonInTempDirForMd5:(id)md5;
+(id)GetPathOfEmoticonInTempDirForMd5:(id)md5;
+(id)GetPathOfTempEmoticonDir;
+(id)getEmotionDesignerIdDecodeFilePath;
+(id)getEmotionPersonalDesignerFilePathForUin:(unsigned long)uin;
+(id)getEmotionPersonalDesignerDir;
+(id)getEmotionCommonCacheDir;
@end

