/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol StoreEmotionRewardGetRewardCgiDelegate <NSObject>
@optional
-(void)onGetRewardCgiFailedForUnrewardableWithPid:(id)pid;
-(void)onGetRewardCgiFailedWithPid:(id)pid;
-(void)onGetRewardCgiOkWithPid:(id)pid Prices:(id)prices EmotionReward:(id)reward;
-(void)onGetRewardCgiOkWithPid:(id)pid Prices:(id)prices DonorNum:(unsigned)num Donors:(id)donors EmotionReward:(id)reward;
@end

