/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "StoreEmotionNotifyTask.h"

@class NSString;
@protocol StoreEmotionAddTaskDelegate;

@interface StoreEmotionAddTask : StoreEmotionNotifyTask {
	NSString* _productID;
	id<StoreEmotionAddTaskDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<StoreEmotionAddTaskDelegate> delegate;
@property(retain, nonatomic) NSString* productID;
-(void).cxx_destruct;
-(BOOL)resumeLogic;
-(id)initWithProductID:(id)productID andDelegate:(id)delegate;
@end

