/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"
#import "StoreEmotionRecoverMyPanelListCgiDelegate.h"

@class StoreEmotionRecoverMyPanelListCgi, NSString;
@protocol StoreEmotionRecoverLogicObjectDelegate;

@interface StoreEmotionRecoverLogicObject : MMObject <StoreEmotionRecoverMyPanelListCgiDelegate> {
	BOOL _m_isActive;
	BOOL _m_hasStartLogic;
	int _scene;
	StoreEmotionRecoverMyPanelListCgi* _downloadCgi;
	id<StoreEmotionRecoverLogicObjectDelegate> _delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL m_hasStartLogic;
@property(assign, nonatomic) BOOL m_isActive;
@property(assign, nonatomic) __weak id<StoreEmotionRecoverLogicObjectDelegate> delegate;
@property(retain, nonatomic) StoreEmotionRecoverMyPanelListCgi* downloadCgi;
@property(assign, nonatomic) int scene;
-(void).cxx_destruct;
-(void)onStoreEmotionRecoverMyPanelListCgiFailed;
-(void)onStoreEmotionRecoverMyPanelListCgiOKWithPids:(id)pids;
-(BOOL)canStartCgiNow;
-(void)startInternalRequest;
-(BOOL)isActive;
-(void)startRequest;
-(id)initWithDelegate:(id)delegate;
@end

