/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PBMessageObserverDelegate.h"
#import "MMObject.h"

@class NSString;
@protocol StoreEmotionRewardGetRewardCgiDelegate;

@interface StoreEmotionRewardGetRewardCgi : MMObject <PBMessageObserverDelegate> {
	BOOL m_hasStartRequestOnce;
	NSString* m_pid;
	unsigned long m_eventID;
	id<StoreEmotionRewardGetRewardCgiDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<StoreEmotionRewardGetRewardCgiDelegate> delegate;
-(void).cxx_destruct;
-(void)callFailedDelegateForUnrewardable;
-(void)callFailedDelegate;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(BOOL)startRequestWithNeedAllData:(BOOL)needAllData;
-(id)initWithPid:(id)pid;
@end

