/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol StoreEmotionGetDesignerEmojiListCgiDelegate <NSObject>
@optional
-(void)onGetDesignerEmojiListFailedWithTagId:(unsigned)tagId;
-(void)onGetDesignerEmojiListSuccessedWithTagId:(unsigned)tagId DesignerEmojiList:(id)list hasMore:(BOOL)more;
-(void)onGetDesignerEmojiListFailedWithKeyword:(id)keyword;
-(void)onGetDesignerEmojiListSuccessedWithKeyword:(id)keyword Tags:(id)tags DesignerEmojiList:(id)list hasMore:(BOOL)more;
-(void)onGetDesignerEmojiListFailedWithDesignerUin:(unsigned long)designerUin;
-(void)onGetDesignerEmojiListSuccessedWithDesignerUin:(unsigned long)designerUin Tags:(id)tags DesignerEmojiList:(id)list hasMore:(BOOL)more;
-(void)onGetDesignerEmojiListFailed;
-(void)onGetDesignerEmojiListSuccessedWithTags:(id)tags DesignerEmojiList:(id)list hasMore:(BOOL)more;
@end

