/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "NSObject.h"


@protocol textViewDelegate <NSObject>
@optional
-(void)onAccessoryViewFrameChanged:(CGRect)changed;
-(void)textview:(id)textview pasteImage:(id)image;
-(BOOL)textview:(id)textview shouldPasteImage:(id)image;
-(void)touchesCancelled_TextView:(id)view withEvent:(id)event;
-(void)touchesEnded_TextView:(id)view withEvent:(id)event;
-(void)touchesMoved_TextView:(id)view withEvent:(id)event;
-(void)touchesBegan_TextView:(id)view withEvent:(id)event;
@end

