/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ITrackRoomMgrExt.h"
#import "IWXTalkieExt.h"
#import "ILocationMgrExt.h"
#import "UIAlertViewDelegate.h"
#import "QMapViewDelegate.h"
#import "WCActionSheetDelegate.h"
#import "WeChat-Structs.h"
#import "UIGestureRecognizerDelegate.h"
#import "NavigateLogicControllerDelegate.h"
#import "IAUAudioDeviceExt.h"
#import "MMHeadImageAnnotationViewDelegate.h"
#import "TrackRoomTopBarViewDelegate.h"
#import "MMUIWindow.h"

@class NavigateLogicController, AnnotationLogicController, HeadClusterView, MMTimer, TrackRoomTopBarView, UIButton, UIAlertView, NSString, QMapView, POIInfo, CAShapeLayer, MMLoadingView, UIView;
@protocol TrackRoomViewDelegate;

@interface TrackRoomView : MMUIWindow <UIAlertViewDelegate, MMHeadImageAnnotationViewDelegate, ITrackRoomMgrExt, TrackRoomTopBarViewDelegate, QMapViewDelegate, UIAlertViewDelegate, WCActionSheetDelegate, ILocationMgrExt, IWXTalkieExt, WCActionSheetDelegate, IAUAudioDeviceExt, UIGestureRecognizerDelegate, NavigateLogicControllerDelegate> {
	id<TrackRoomViewDelegate> _trackRoomViewDelegate;
	BOOL _isInit;
	BOOL _getMicSucc;
	BOOL _showAllHead;
	BOOL _isMapRegionChanging;
	BOOL _shouldIgnoreAccuracy;
	BOOL _intermediateAnimation;
	BOOL _shouldHideAllAnnotation;
	BOOL _shouldZoomToSeeAll;
	BOOL _isLoadFinish;
	BOOL _drivingMode;
	BOOL _refreshOK;
	unsigned long _gpsTag;
	timeval _startLocatingTime;
	timeval _startShowTime;
	UIView* _micMeterCircleView;
	POIInfo* _poiInfo;
	unsigned _scene;
	UIButton* _micButton;
	UIButton* _myLocationButton;
	NSString* _chatname;
	QMapView* _mapView;
	UIAlertView* _trackErrorAlertView;
	CAShapeLayer* _micMeterCircle;
	MMTimer* _updateUserLocationTimer;
	MMLoadingView* _loadingView;
	XXStruct_Yvvv9D _destinationRegion;
	TrackRoomTopBarView* _topbarView;
	HeadClusterView* _headClusterView;
	NavigateLogicController* _navigateLogicController;
	AnnotationLogicController* _annotationLogicController;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<TrackRoomViewDelegate> trackRoomViewDelegate;
-(void).cxx_destruct;
-(void)onPresentViewControlelr:(id)controlelr Animated:(BOOL)animated;
-(void)onStopLoading;
-(void)onStartLoading;
-(void)onCenterMapAt:(id)at;
-(void)onClickCallout:(id)callout AtPoint:(CGPoint)point;
-(void)onClickDot:(id)dot AtPoint:(CGPoint)point;
-(void)navigateTo:(id)to Name:(id)name Sender:(id)sender;
-(id)getDisplayNameByUsername:(id)username;
-(void)setAnnotation:(id)annotation Coordinate:(XXStruct_gLbvpC)coordinate Animated:(BOOL)animated Duration:(float)duration;
-(void)updateHeadAnnotation:(id)annotation;
-(void)onRemoteControlCheckShouldStop;
-(void)onRemoteControlCheckShouldPlay;
-(void)OnRestart;
-(void)OnPause;
-(void)OnReConnecting;
-(void)onKickOutFromWXTalkRoom:(id)wxtalkRoom;
-(void)OnNobodyTalking;
-(void)OnForceStopRecord;
-(void)OnError:(id)error ErrNo:(int)no;
-(void)OnSomeoneTalking:(id)talking;
-(void)OnGetMicrophoneResult:(int)result;
-(void)OnOpenWXTalkModeOK:(id)ok;
-(void)audioDeviceInputMeterLevel:(id)level Peak:(float)peak;
-(void)doMeterAnimationOnMainThread:(id)thread;
-(void)closeTalk;
-(BOOL)openTalk:(id)talk;
-(void)OnHeadingChanged:(double)changed;
-(void)OnTrackRoomError:(int)error Message:(id)message;
-(void)trySeeAll;
-(void)OnRefreshTrackRoom:(id)room Type:(int)type;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)initTrack;
-(void)onGPSLocationChanged:(id)changed withTag:(unsigned long)tag;
-(void)mapView:(id)view didDeselectAnnotationView:(id)view2;
-(void)mapView:(id)view didSelectAnnotationView:(id)view2;
-(void)mapView:(id)view didUpdateUserLocation:(id)location;
-(void)mapView:(id)view didAddAnnotationViews:(id)views;
-(id)mapView:(id)view viewForOverlay:(id)overlay;
-(id)mapView:(id)view viewForAnnotation:(id)annotation;
-(void)mapView:(id)view regionDidChangeAnimated:(BOOL)region;
-(void)mapView:(id)view regionWillChangeAnimated:(BOOL)region;
-(void)didDragMap:(id)map;
-(BOOL)gestureRecognizer:(id)recognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)gestureRecognizer;
-(void)bringFriendToFront:(id)front;
-(void)bringMyselfToFront;
-(id)getUserLocation;
-(void)setRegion:(XXStruct_Yvvv9D)region AlwaysAnimated:(BOOL)animated;
-(void)onSetIgnoreAccuracy;
-(BOOL)isLocationOK:(id)ok;
-(void)stopUpdateUserLocation;
-(void)startUpdateUserLocation;
-(void)stopTimerCheckUserLocation;
-(void)startTimerCheckUserLocation;
-(void)onTimerUpdateLocation;
-(void)resizeMapToShowAllHeadAnimated:(id)showAllHeadAnimated;
-(void)onNavigateToPOI:(id)poi;
-(void)setAllHeadAnnotationShowCallout:(BOOL)callout Animated:(BOOL)animated;
-(void)showLocationCalloutViewAnimated:(BOOL)animated;
-(BOOL)showClusterViewOnPoint:(CGPoint)point;
-(void)onMapTapped:(id)tapped;
-(void)onMicButtonReleased;
-(void)onMicButtonPressed;
-(void)onMyLocationButtonClick;
-(void)onMinimizeButtonClick;
-(void)onCloseButtonClick:(id)click;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)closeTrackRoom:(unsigned)room;
-(void)stopLoading;
-(void)startLoadingNonBlock;
-(id)getLocationText:(XXStruct_gLbvpC)text;
-(void)enterForeground;
-(void)enterBackground;
-(void)hideTrackRoomView;
-(void)showTrackRoomView;
-(void)exitTracking:(unsigned)tracking;
-(void)doStartTrack;
-(BOOL)startTrackWithChatname:(id)chatname POIInfo:(id)info Scene:(unsigned)scene;
-(void)initMapView;
-(void)initView;
-(void)dealloc;
-(void)internalInit;
-(id)init;
-(id)initWithFrame:(CGRect)frame;
@end

