/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class TranslateLinkReq_iOSInfo, NSMutableArray, NSString, BaseRequest;

@interface TranslateLinkReq : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSMutableArray* androidInfo;
@property(retain, nonatomic) TranslateLinkReq_iOSInfo* iosInfo;
@property(assign, nonatomic) unsigned scene;
@property(retain, nonatomic) NSString* link;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

