/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class BaseRequest, NSString;

@interface TransIdRequest : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSString* openid;
@property(retain, nonatomic) NSString* username;
@property(retain, nonatomic) NSString* appid;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

