/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface TwitterArchiveData : XXUnknownSuperclass <NSCoding> {
	NSString* m_nsAccessToken;
	NSString* m_nsAccessTokenSecret;
}
@property(retain, nonatomic) NSString* m_nsAccessTokenSecret;
@property(retain, nonatomic) NSString* m_nsAccessToken;
-(void).cxx_destruct;
-(void)dealloc;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
@end

