/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "NSCopying.h"

@class NSString, NSArray;

@interface TwoDDecoderResult : XXUnknownSuperclass <NSCopying> {
	NSString* text;
	NSArray* points;
}
@property(retain, nonatomic) NSArray* points;
@property(retain, nonatomic) NSString* text;
+(id)resultWithText:(id)text points:(id)points;
-(void).cxx_destruct;
-(id)description;
-(id)copy;
-(id)copyWithZone:(NSZone*)zone;
-(id)initWithText:(id)text points:(id)points;
@end

