/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NetworkSectResp, AuthSectResp, AcctSectResp, BaseResponse;

@interface UnifyAuthResponse : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NetworkSectResp* networkSectResp;
@property(retain, nonatomic) AcctSectResp* acctSectResp;
@property(retain, nonatomic) AuthSectResp* authSectResp;
@property(assign, nonatomic) unsigned unifyAuthSectFlag;
@property(retain, nonatomic) BaseResponse* baseResponse;
+(void)initialize;
@end

