/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class SKBuiltinBuffer_t, BaseResponse;

@interface UploadInputVoiceResponse : WXPBGeneratedMessage {
}
@property(retain, nonatomic) SKBuiltinBuffer_t* text;
@property(assign, nonatomic) unsigned endFlag;
@property(retain, nonatomic) BaseResponse* baseResponse;
+(void)initialize;
@end

