/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class SKBuiltinBuffer_t, UploadVoiceCtx, NSString, BaseRequest, VoiceAttr;

@interface UploadVoiceForTransRequest : WXPBGeneratedMessage {
}
@property(retain, nonatomic) SKBuiltinBuffer_t* data;
@property(retain, nonatomic) UploadVoiceCtx* uploadCtx;
@property(retain, nonatomic) VoiceAttr* voiceAttr;
@property(retain, nonatomic) NSString* voiceId;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

