/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"


@interface UploadVoiceCtx : WXPBGeneratedMessage {
}
@property(assign, nonatomic) unsigned dataLen;
@property(assign, nonatomic) unsigned startPos;
@property(assign, nonatomic) unsigned totalLen;
+(void)initialize;
@end

