/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class UploadVoiceCtx, BaseResponse;

@interface UploadVoiceForTransResponse : WXPBGeneratedMessage {
}
@property(retain, nonatomic) UploadVoiceCtx* uploadCtx;
@property(retain, nonatomic) BaseResponse* baseResponse;
+(void)initialize;
@end

