/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class SKBuiltinBuffer_t;

@interface VoicePieceCtx : WXPBGeneratedMessage {
}
@property(retain, nonatomic) SKBuiltinBuffer_t* pieceData;
@property(assign, nonatomic) unsigned pieceFlag;
@property(assign, nonatomic) unsigned pieceLen;
@property(assign, nonatomic) unsigned startPos;
+(void)initialize;
@end

