/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NSMutableArray;

@interface VoipAddrSet : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSMutableArray* addrs;
@property(assign, nonatomic) int cnt;
+(void)initialize;
@end

