/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class SKBuiltinBuffer_t, BaseRequest;

@interface VoipDoubleLinkSwitchReq : WXPBGeneratedMessage {
}
@property(retain, nonatomic) SKBuiltinBuffer_t* buffer;
@property(assign, nonatomic) int bufferVersion;
@property(assign, nonatomic) int curStrategy;
@property(assign, nonatomic) int isDirectConnReady;
@property(assign, nonatomic) int isRelayConnReady;
@property(assign, nonatomic) int curLinkType;
@property(assign, nonatomic) int roomMemberId;
@property(assign, nonatomic) long long roomKey;
@property(assign, nonatomic) int roomId;
@property(retain, nonatomic) BaseRequest* baseRequest;
+(void)initialize;
@end

