/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "PBMessageObserverDelegate.h"

@class VoipMonoMsg;
@protocol VoipGetRoomInfoCgiDelegate;

@interface VoipGetRoomInfoCgi : XXUnknownSuperclass <PBMessageObserverDelegate> {
	VoipMonoMsg* m_voipMonoMsg;
	id<VoipGetRoomInfoCgiDelegate> _m_delegate;
}
@property(assign, nonatomic) __weak id<VoipGetRoomInfoCgiDelegate> m_delegate;
@property(retain, nonatomic) VoipMonoMsg* m_voipMonoMsg;
-(void).cxx_destruct;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(void)startRequest;
-(id)init;
@end

