/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NSMutableArray, VoipMultiRelayData, BaseResponse;

@interface VoipInviteResp : WXPBGeneratedMessage {
}
@property(assign, nonatomic) unsigned switchInterval;
@property(assign, nonatomic) unsigned tcpCnt;
@property(assign, nonatomic) int audioDtx;
@property(assign, nonatomic) int newP2S;
@property(assign, nonatomic) int voipSyncInterval;
@property(assign, nonatomic) int fastPlayRepair;
@property(assign, nonatomic) int passthroughQosAlgorithm;
@property(assign, nonatomic) int audioTsdfEdge;
@property(assign, nonatomic) int audioTsdfBeyond3G;
@property(retain, nonatomic) NSMutableArray* netQualityList;
@property(assign, nonatomic) int netQualityCnt;
@property(retain, nonatomic) VoipMultiRelayData* relayData;
@property(assign, nonatomic) int roomMemberId;
@property(assign, nonatomic) long long roomKey;
@property(retain, nonatomic) NSMutableArray* addrList;
@property(assign, nonatomic) int addrCount;
@property(assign, nonatomic) int roomId;
@property(retain, nonatomic) BaseResponse* baseResponse;
+(void)initialize;
@end

