/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WCAccountBindPhoneForRegCGIDelegate <NSObject>
@optional
-(void)onCheckForgetPwdVerifyCode:(id)code userName:(id)name password:(id)password StyleKeyValue:(id)value;
-(void)onCheckSafeDeviceVerifyCode:(id)code;
-(void)onCheckLoginVerifyCode:(id)code ticket:(id)ticket controlShowFlag:(unsigned long)flag userName:(id)name password:(id)password StyleKeyValue:(id)value;
-(void)onCheckRegVerifyCode:(id)code ticket:(id)ticket controlShowFlag:(unsigned long)flag userName:(id)name password:(id)password StyleKeyValue:(id)value;
-(void)onGetForgetPwdVoiceVerifyCode:(id)code StyleKeyValue:(id)value;
-(void)onGetSafeDeviceVoiceVerifyCode:(id)code authTicket:(id)ticket StyleKeyValue:(id)value;
-(void)onGetLoginVoiceVerifyCode:(id)code StyleKeyValue:(id)value;
-(void)onGetRegVoiceVerifyCode:(id)code StyleKeyValue:(id)value;
-(void)onGetForgetPwdVerifyCode:(id)code StyleKeyValue:(id)value;
-(void)onGetSafeDeviceVerifyCode:(id)code authTicket:(id)ticket StyleKeyValue:(id)value;
-(void)onGetLoginVerifyCode:(id)code StyleKeyValue:(id)value;
-(void)onGetRegVerifyCode:(id)code StyleKeyValue:(id)value;
-(void)onCheckLoginPhoneNumberStatus:(id)status countryCode:(id)code phoneNumber:(id)number formatedPhoneNumber:(id)number4 StyleKeyValue:(id)value;
-(void)onCheckRegPhoneNumberStatus:(id)status countryCode:(id)code phoneNumber:(id)number formatedPhoneNumber:(id)number4 StyleKeyValue:(id)value;
@end

