/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMUIViewController.h"
#import "MMTableViewInfoDelegate.h"
#import "WCBaseInfoItemDelegate.h"

@class WCAccountControlData, MMTableViewInfo, NSString;

@interface WCAccountBaseViewController : MMUIViewController <MMTableViewInfoDelegate, WCBaseInfoItemDelegate> {
	MMTableViewInfo* m_tableViewInfo;
	WCAccountControlData* m_data;
	unsigned long m_uiReportStatus;
	NSString* m_nsStyleID;
	timeval m_tvStart;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned long m_uiReportStatus;
@property(retain, nonatomic) NSString* m_nsStyleID;
-(void).cxx_destruct;
-(void)viewDidTransitionToNewSize;
-(BOOL)useIpadSytle;
-(BOOL)recoverFromArchive:(id)archive;
-(id)getArchive;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)WCBaseInfoItemPressReturnKey:(id)key;
-(void)onNext;
-(id)getInputLineView;
-(id)getHeaderTipLabel:(id)label;
-(id)makeHeaderView:(id)view;
-(id)getHeaderView:(id)view;
-(void)hideKeyBoard;
-(void)initNavigationBar;
-(unsigned long)getStayTime;
-(void)setStartTime;
-(void)viewDidLoad;
-(void)setTableFooterView:(id)view;
-(void)setTableHeaderView:(id)view;
-(void)viewWillDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLayoutSubviews;
-(void)initView;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)callViewDidLoad;
-(BOOL)useCustomNavibar;
-(void)initData;
-(void)refreshViewWithData:(id)data;
-(void)setupWithData:(id)data;
-(id)init;
@end

