/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCBaseControlMgrExt.h"
#import "WCBizControlLogic.h"
#import "WCAddressLogicMgrExt.h"

@class WCAddressControlData, NSString, WCAddressControlLogic;

@interface WCAddressGetAddressControlLogic : WCBizControlLogic <WCAddressLogicMgrExt, WCBaseControlMgrExt> {
	WCAddressControlData* m_data;
	WCAddressControlLogic* m_oWCAddressControlLogic;
	int m_eWCAddressGetAddressControlLogicSituation;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)OnPreFinishedWCAddressLogic:(id)logic waitUntilDone:(BOOL*)done;
-(void)OnGetLatestAddress:(id)address UserName:(id)name NickName:(id)name3 Error:(id)error;
-(void)onWCBaseLogicDidStop:(unsigned long)onWCBaseLogic;
-(void)stopLogic;
-(void)startLogic;
-(void)EndWCAddressGetAddressControlLogic;
-(void)dealloc;
-(id)initWithData:(id)data Situation:(int)situation;
-(id)initWithData:(id)data;
@end

