/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCBizBaseViewController.h"

@class WCAddressControlData;

@interface WCAddressBaseViewController : WCBizBaseViewController {
	WCAddressControlData* m_data;
}
-(void).cxx_destruct;
-(void)refreshViewWithData:(id)data;
-(void)setupWithData:(id)data;
-(void)dealloc;
@end

