/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMUIViewController.h"
#import "UITextFieldDelegate.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class UITextField, NSMutableArray, WCSettingWatchContactsViewController, NSArray, NSString, UIButton, MMTableView;

@interface WCAddWatchContactsViewController : MMUIViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate> {
	NSArray* _recentContactsArr;
	WCSettingWatchContactsViewController* _vc;
	NSMutableArray* _searchedContactsArr;
	UITextField* _searchField;
	MMTableView* _contactTableView;
	UIButton* _cancelButton;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) UIButton* cancelButton;
@property(retain, nonatomic) MMTableView* contactTableView;
@property(retain, nonatomic) UITextField* searchField;
@property(retain, nonatomic) NSMutableArray* searchedContactsArr;
@property(assign, nonatomic) __weak WCSettingWatchContactsViewController* vc;
@property(retain, nonatomic) NSArray* recentContactsArr;
-(void).cxx_destruct;
-(void)doSearch:(id)search;
-(void)delaySearch:(id)search;
-(void)cancelChooseContacts;
-(void)touchesBegan:(id)began withEvent:(id)event;
-(void)textFieldDidChanged:(id)textField;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(void)refreshTableFooterView;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)initUI;
-(void)setNavItemWithTitle:(id)title action:(SEL)action;
-(void)viewDidLoad;
-(void)didReceiveMemoryWarning;
-(id)init;
@end

