/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "UITextViewDelegate.h"
#import "WCBaseInfoItem.h"

@class UILabel, UITextView, NSString;

@interface WCBaseTextViewItem : WCBaseInfoItem <UITextViewDelegate> {
	UITextView* m_textView;
	UILabel* placeHolderLabel;
	int m_iMaxInputLen;
	BOOL m_bRealLen;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)textViewDidChange:(id)textView;
-(BOOL)textView:(id)view shouldChangeTextInRange:(NSRange)range replacementText:(id)text;
-(void)textViewDidEndEditing:(id)textView;
-(void)textViewDidBeginEditing:(id)textView;
-(void)setMaxRealStringLen:(int)len;
-(void)setMaxInputLen:(int)len;
-(void)setColor:(id)color;
-(void)setFont:(id)font;
-(void)setText:(id)text;
-(id)getTextView;
-(void)resignFirstResponder;
-(void)becomeFirstResponder;
-(void)dealloc;
-(id)initWithTitle:(id)title tip:(id)tip key:(id)key;
-(id)getValue;
-(void)initView:(CGRect)view;
@end

