/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIImage, NSData, NSString;

@interface WCBizImageBrowseItem : XXUnknownSuperclass {
	NSString* m_nsImgUrl;
	UIImage* m_nsThumbImage;
	NSData* m_ndImgData;
}
@property(retain, nonatomic) NSData* m_ndImgData;
@property(retain, nonatomic) UIImage* m_nsThumbImage;
@property(retain, nonatomic) NSString* m_nsImgUrl;
-(void).cxx_destruct;
-(void)dealloc;
@end

