/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "UIPopoverPresentationControllerDelegate.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class UIViewController, UIView, NSString, UIPickerView, UIPopoverController;
@protocol WCBizPickerViewDelegate;

@interface WCBizPickerView : XXUnknownSuperclass <UIPopoverPresentationControllerDelegate> {
	UIPickerView* m_pickerView;
	id<WCBizPickerViewDelegate> _m_delegate;
	UIView* _contentView;
	UIView* _transparentView;
	UIViewController* _contentVC;
	UIPopoverController* _popoverController;
	int _lastOri;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) int lastOri;
@property(retain, nonatomic) UIPopoverController* popoverController;
@property(retain, nonatomic) UIViewController* contentVC;
@property(retain, nonatomic) UIView* transparentView;
@property(retain, nonatomic) UIView* contentView;
@property(assign, nonatomic) __weak id<WCBizPickerViewDelegate> m_delegate;
+(CGSize)getPickerViewSize;
-(void).cxx_destruct;
-(void)dismissWithAnimated:(BOOL)animated;
-(void)handleTap:(id)tap;
-(void)reloadComponent:(int)component;
-(void)setSelectedRow:(int)row Component:(int)component;
-(void)UIPickerViewDidFinish;
-(void)UIPickerViewDidCancel;
-(int)adaptivePresentationStyleForPresentationController:(id)presentationController;
-(void)showInView:(id)view;
-(void)didRotate:(id)rotate;
-(void)dealloc;
-(void)removeAllPickerViewDelegate;
-(id)initWithDelegate:(id)delegate;
@end

