/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"
#import "PBCoding.h"

@class NSArray, NSString;

@interface WCCardDetailTable : MMObject <PBCoding> {
	NSString* _title;
	NSString* _subtitle;
	unsigned long _showNum;
	NSArray* _rows;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSArray* rows;
@property(assign, nonatomic) unsigned long showNum;
@property(retain, nonatomic) NSString* subtitle;
@property(retain, nonatomic) NSString* title;
-(void).cxx_destruct;
@end

