/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WCCardBulkImportMgrDelegate <NSObject>
@optional
-(void)onImportBulkCard:(id)card errCode:(int)code;
-(void)onGetBulkCard:(id)card errCode:(int)code;
@end

