/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"

@class NSString;

@interface WCCardActionSheet : MMObject {
	NSString* _text;
	NSString* _url;
}
@property(retain, nonatomic) NSString* url;
@property(retain, nonatomic) NSString* text;
-(void).cxx_destruct;
-(void)dealloc;
@end

