/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WCCardListViewControllerDelegate <NSObject>
-(void)onWCCardListViewControllerDidSelected:(id)onWCCardListViewController listViewController:(id)controller;
-(void)onWCCardListViewControllerCancel:(id)cancel;
@end

