/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMObject.h"
#import "PBCoding.h"

@class NSString;

@interface WCCardMsgTips : MMObject <PBCoding> {
	unsigned long newCount;
	unsigned long lastUpdateTime;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) unsigned long lastUpdateTime;
@property(assign, nonatomic) unsigned long newCount;
+(void)initialize;
-(id)pathForCardMsgTips;
-(void)loadCardMsgTipsFromCache;
-(void)saveCardMsgTipsToCache;
-(const map<unsigned long, unsigned long, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, unsigned long> > >*)getValueTagIndexMap;
-(id)getValueTypeTable;
@end

