/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface WCCardPkgMsgButton : XXUnknownSuperclass {
	unsigned long actionType;
	NSString* actionText;
	NSString* actionUrl;
}
@property(retain, nonatomic) NSString* actionUrl;
@property(retain, nonatomic) NSString* actionText;
@property(assign, nonatomic) unsigned long actionType;
-(void).cxx_destruct;
-(BOOL)IsActionValid;
-(void)dealloc;
@end

