/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WCCommitViewAnimationDelegate <NSObject>
@optional
-(void)onFinishSendWithoutAnim;
-(void)commitAnimationWillStart:(id)commitAnimation;
-(void)animationDidEndRemainView:(id)animation hintDataItem:(id)item;
@end

