/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString, WCDataBase;

@interface WCDataBaseTable : XXUnknownSuperclass {
	WCDataBase* m_db;
	NSString* m_tableName;
	Class m_tableClass;
}
-(void).cxx_destruct;
-(Class)tableClass;
-(id)database;
-(id)tableName;
-(BOOL)deleteObjectsWhere:(const WCDBConditionBase*)where;
-(BOOL)deleteObject:(id)object;
-(BOOL)updateObject:(id)object onProperties:(const vector<WCDBConditionBase, std::__1::allocator<WCDBConditionBase> >*)properties where:(const WCDBConditionBase*)where;
-(BOOL)updateObject:(id)object onProperties:(const vector<WCDBConditionBase, std::__1::allocator<WCDBConditionBase> >*)properties;
-(BOOL)updateProperty:(const WCDBConditionBase*)property withValue:(id)value where:(const WCDBConditionBase*)where;
-(BOOL)insertOrUpdateObjects:(id)objects onConflict:(id)conflict;
-(BOOL)insertOrUpdateObject:(id)object onConflict:(id)conflict;
-(BOOL)insertOrUpdateObjects:(id)objects;
-(BOOL)insertOrUpdateObject:(id)object onProperties:(const vector<WCDBConditionBase, std::__1::allocator<WCDBConditionBase> >*)properties;
-(BOOL)insertOrUpdateObject:(id)object;
-(BOOL)insertObject:(id)object onProperties:(const vector<WCDBConditionBase, std::__1::allocator<WCDBConditionBase> >*)properties autoIncrement:(BOOL)increment;
-(BOOL)insertObject:(id)object autoIncrement:(BOOL)increment;
-(id)getSumProperty:(const WCDBConditionBase*)property where:(const WCDBConditionBase*)where;
-(id)getMaxProperty:(const WCDBConditionBase*)property where:(const WCDBConditionBase*)where;
-(id)getMaxProperty:(const WCDBConditionBase*)property;
-(id)getOnePropertyValue:(const WCDBConditionBase*)value where:(const WCDBConditionBase*)where orderBy:(const WCDBConditionBase*)by;
-(id)getPropertyWithDistinct:(const WCDBConditionBase*)distinct where:(const WCDBConditionBase*)where;
-(id)getProperty:(const WCDBConditionBase*)property where:(const WCDBConditionBase*)where orderBy:(const WCDBConditionBase*)by limit:(unsigned long)limit;
-(id)getProperty:(const WCDBConditionBase*)property where:(const WCDBConditionBase*)where limit:(unsigned long)limit;
-(id)getProperty:(const WCDBConditionBase*)property where:(const WCDBConditionBase*)where;
-(id)getProperty:(const WCDBConditionBase*)property;
-(unsigned long)getCountOfDistinctProperty:(const WCDBConditionBase*)distinctProperty Where:(const WCDBConditionBase*)where;
-(unsigned long)getCountOfObjectsWhere:(const WCDBConditionBase*)objectsWhere;
-(unsigned long)getCountOfObjects;
-(id)getObjectsWhere:(const WCDBConditionBase*)where onProperties:(const vector<WCDBConditionBase, std::__1::allocator<WCDBConditionBase> >*)properties orderBy:(const WCDBConditionBase*)by limit:(unsigned long)limit getError:(id*)error;
-(id)getObjectsWhere:(const WCDBConditionBase*)where onProperties:(const vector<WCDBConditionBase, std::__1::allocator<WCDBConditionBase> >*)properties orderBy:(const WCDBConditionBase*)by limit:(unsigned long)limit;
-(id)getObjectsWhere:(const WCDBConditionBase*)where orderBy:(const WCDBConditionBase*)by limit:(unsigned long)limit;
-(id)getObjectsWhere:(const WCDBConditionBase*)where limit:(unsigned long)limit;
-(id)getObjectsWhere:(const WCDBConditionBase*)where;
-(id)getAllObjects;
-(id)getOneObjectWhere:(const WCDBConditionBase*)where onProperties:(const vector<WCDBConditionBase, std::__1::allocator<WCDBConditionBase> >*)properties orderBy:(const WCDBConditionBase*)by;
-(id)getOneObjectWhere:(const WCDBConditionBase*)where;
-(id)getLastObject;
-(id)initWithDataBase:(id)dataBase tableName:(id)name objectClass:(Class)aClass;
@end

