/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface WCDBPerformanceWrap : XXUnknownSuperclass {
	NSString* tableClass;
	unsigned opType;
	NSString* sql;
	NSString* callStack;
	unsigned threadId;
	unsigned timeStamp;
	unsigned long long costTime;
}
@property(assign, nonatomic) unsigned timeStamp;
@property(assign, nonatomic) unsigned threadId;
@property(retain, nonatomic) NSString* callStack;
@property(retain, nonatomic) NSString* sql;
@property(assign, nonatomic) unsigned opType;
@property(retain, nonatomic) NSString* tableClass;
@property(assign, nonatomic) unsigned long long costTime;
-(void).cxx_destruct;
-(id)description;
@end

