/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class WCDataBase;

@interface WCDBContext : XXUnknownSuperclass {
	WCDataBase* m_db;
}
-(void).cxx_destruct;
-(id)db;
-(void)setDB:(id)db;
@end

