/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"


@interface WCDBTableQueryInfo : XXUnknownSuperclass {
	vector<WCDBConditionBase, std::__1::allocator<WCDBConditionBase> > m_vecProperty;
	basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > m_tableName;
	BOOL m_hasFileProperty;
	Class m_tableClass;
}
@property(assign, nonatomic) BOOL m_hasFileProperty;
@property(assign, nonatomic) Class m_tableClass;
-(id).cxx_construct;
-(void).cxx_destruct;
-(const basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*)tableName;
-(const vector<WCDBConditionBase, std::__1::allocator<WCDBConditionBase> >*)selectProperty;
-(void)setSelectProperty:(const vector<WCDBConditionBase, std::__1::allocator<WCDBConditionBase> >*)property;
-(void)setTableInfo:(id)info;
@end

