/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "PBMessageObserverDelegate.h"
#import "MMObject.h"

@class NSMutableArray;
@protocol WCDeviceAuthLogicDelegate;

@interface WCDeviceAuthLogic : MMObject <PBMessageObserverDelegate> {
	NSMutableArray* m_deviceInfos;
	int m_appState;
	id<WCDeviceAuthLogicDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<WCDeviceAuthLogicDelegate> delegate;
-(void).cxx_destruct;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(void)handleWCDeviceAuthResopnse:(id)resopnse;
-(id)__findDeviceInfoByDeviceID:(id)anId;
-(id)__findDeviceInfoByDid:(long long)__findDeviceInfoBy;
-(void)__clearDeviceInfoByDeviceId:(long long)anId;
-(void)__callbackEnd:(int)end DID:(unsigned long long)did RespTask:(id)task SessionKey:(id)key;
-(void)handleWCDeviceChannelStateChanged:(long long)changed OldState:(int)state NewState:(int)state3;
-(void)handleDeviceAuthReq:(long long)req :(unsigned short)arg2 :(unsigned short)arg3 :(MmBp__AuthRequest**)arg4;
-(id)genAuthRespTask:(int)task DeviceID:(long long)anId Seq:(unsigned short)seq AESSessionKey:(id)key;
-(id)__toNSString:(void*)nsstring :(int)arg2;
-(void)handleDeivceLost:(long long)lost;
-(BOOL)isDeviceAuthed:(long long)authed;
-(BOOL)setNeedAuth:(long long)auth;
-(id)getSessionBuffer:(long long)buffer;
-(void)sendAuthReqToSvr:(id)svr AuthBuffer:(id)buffer;
-(void)willSuspend;
-(void)willEnterForeground;
-(void)dealloc;
-(id)init;
@end

