/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "UIScrollViewDelegate.h"
#import "MMImageScrollViewHelperDelegate.h"
#import "MMUIScrollView.h"

@class NSArray, UIView, NSString, UIActivityIndicatorView, MMImageScrollViewHelper;
@protocol WCImageScrollViewDelegate;

@interface WCImageScrollView : MMUIScrollView <UIScrollViewDelegate, MMImageScrollViewHelperDelegate> {
	UIView* imageView;
	unsigned index;
	UIActivityIndicatorView* mActivityIndicator;
	MMImageScrollViewHelper* m_scrollViewHelper;
	BOOL supportOrientation;
	id<WCImageScrollViewDelegate> m_delegate;
}
@property(copy, nonatomic) NSArray* gestureRecognizers;
@property(assign, nonatomic) float maximumZoomScale;
@property(assign, nonatomic) float minimumZoomScale;
@property(assign, nonatomic) float zoomScale;
@property(assign, nonatomic) CGRect frame;
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<WCImageScrollViewDelegate> m_delegate;
@property(readonly, assign, nonatomic) UIActivityIndicatorView* mActivityIndicator;
@property(assign, nonatomic) BOOL supportOrientation;
@property(assign, nonatomic) unsigned index;
-(void).cxx_destruct;
-(void)rotateImageWithImage:(id)image;
-(void)setImageTransform:(CGAffineTransform)transform;
-(void)stopLoading;
-(void)displayView:(id)view;
-(void)displayImage:(id)image withFrame:(CGRect)frame;
-(void)internalDisplayImage:(id)image withFrame:(CGRect)frame animate:(BOOL)animate;
-(float)angelFromOldOrientation:(int)oldOrientation newOrientation:(int)orientation;
-(int)orientationToInt:(int)int;
-(void)onDoubleTap:(id)tap;
-(void)onSingleTap:(id)tap;
-(id)getScrollView;
-(id)viewForZooming;
-(void)scrollViewDidZoom:(id)scrollView;
-(id)viewForZoomingInScrollView:(id)scrollView;
-(void)dealloc;
-(id)initWithFrame:(CGRect)frame;
@end

