/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WCImageFullScreenViewControllerDelegateV4 <NSObject>
-(void)onAnimateFadeOut;
-(void)windowNeed2Show;
-(void)windowNeed2Hide;
-(void)onViewControllerAnimationHideWillStop;
-(void)onViewControllerAnimationHideStop;
-(void)onViewControllerAnimationShowWillStart;
@end

