/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "ICdnComMgrExt.h"
#import "WCLanDeviceBaseKissLogic.h"
#import "PBMessageObserverDelegate.h"

@class NSMutableArray, WCLanDeviceData, NSString, NSMutableDictionary, CdnUploadTaskInfo;

@interface WCLanDeviceFileKissLogic : WCLanDeviceBaseKissLogic <ICdnComMgrExt, PBMessageObserverDelegate> {
	NSMutableDictionary* m_sendTaskMap;
	WCLanDeviceData* m_deviceData;
	NSMutableArray* m_deviceWaitingUploadArray;
	CdnUploadTaskInfo* m_uploadInfo;
	BOOL m_isUploading;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(BOOL)cancelTaskWithDevice:(id)device;
-(void)onKissDeviceProgressResponeWithProgressInfo:(id)progressInfo;
-(void)onKissDeviceResponseWithErrorCode:(unsigned)errorCode;
-(void)OnCdnUploadProgress:(id)progress;
-(void)OnCdnUpload:(id)upload;
-(BOOL)stopUploadWithDevice:(id)device;
-(void)uploadDeviceData;
-(void)onSendFileToWCLanDevice:(long long)wclanDevice Progress:(float)progress isFinish:(BOOL)finish ErrCode:(int)code;
-(void)kissDeviceWithJsonStr:(id)jsonStr filePath:(id)path device:(id)device;
-(void)handleDeviceMsgTransferAppMsg:(id)msg;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(void)sendFileRequestWithDevice:(id)device isTroughSever:(BOOL)sever fileInfo:(id)info uploadInfo:(id)info4;
-(void)dealloc;
-(void)forwardData:(id)data toDevice:(id)device isThrouSever:(BOOL)sever;
-(id)initWithDelegate:(id)delegate deviceScene:(unsigned)scene;
@end

