/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol WCLogicMgrDelegate
@optional
-(void)onChangeHBFeedBrowseStatus:(BOOL)status bOpen:(BOOL)open;
-(void)onSetHBDataItemFreeFinished:(int)finished dataItemID:(id)anId;
-(void)onAdvertiseItemDeleted:(id)deleted;
-(void)onDataItemExposeFinisehd:(int)finisehd dataItem:(id)item;
-(void)onUpdateDataItemDetailFinisehd:(int)finisehd dataItem:(id)item;
-(void)onSetDataItemPublicFinished:(int)finished dataItemID:(id)anId;
-(void)onSetDataItemPrivateFinished:(int)finished dataItemID:(id)anId;
-(void)onCommentItemDeleteFinished:(int)finished commentItemID:(id)anId dataItemID:(id)anId3;
-(void)onDataItemDeleteFinished:(int)finished dataItemID:(id)anId;
@end

