/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSMutableArray, NSString;

@interface WCMallPayProductInfo : XXUnknownSuperclass {
	unsigned long m_uiProductId;
	NSString* m_nsAppId;
	NSString* m_nsProductName;
	NSString* m_nsProductDescrible;
	unsigned long m_uiProductMinPrice;
	unsigned long m_uiProductMaxPrice;
	unsigned long m_uiDiscount;
	BOOL m_bIsInfinite;
	unsigned long m_uiLeftCount;
	BOOL m_bIsShelved;
	BOOL m_bIsDefaultChoose;
	BOOL m_bNeedGetLatestInfo;
	BOOL m_bNeedGetAttribute;
	NSMutableArray* m_arrAttributeList;
	unsigned m_uiProductType;
}
@property(assign, nonatomic) unsigned m_uiProductType;
@property(retain, nonatomic) NSMutableArray* m_arrAttributeList;
@property(assign, nonatomic) BOOL m_bNeedGetAttribute;
@property(assign, nonatomic) BOOL m_bNeedGetLatestInfo;
@property(assign, nonatomic) BOOL m_bIsDefaultChoose;
@property(assign, nonatomic) BOOL m_bIsShelved;
@property(assign, nonatomic) unsigned long m_uiLeftCount;
@property(assign, nonatomic) BOOL m_bIsInfinite;
@property(assign, nonatomic) unsigned long m_uiDiscount;
@property(assign, nonatomic) unsigned long m_uiProductMaxPrice;
@property(assign, nonatomic) unsigned long m_uiProductMinPrice;
@property(retain, nonatomic) NSString* m_nsProductDescrible;
@property(retain, nonatomic) NSString* m_nsProductName;
@property(retain, nonatomic) NSString* m_nsAppId;
@property(assign, nonatomic) unsigned long m_uiProductId;
-(void).cxx_destruct;
@end

