/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCActionSheetDelegate.h"
#import "WCNewCardDetailViewControllerDelegate.h"
#import "WeChat-Structs.h"
#import "MMTipsViewControllerDelegate.h"
#import "WCShareCardMyCardEntryViewDelegate.h"
#import "MMUIViewController.h"
#import "EGORefreshTableHeaderDelegate.h"
#import "WCCardPackageViewControllerDelegate.h"
#import "UITableViewDelegate.h"
#import "WCNewShareCardListLogicDelegate.h"
#import "UITableViewDataSource.h"

@class NSString, MMUIView, MMTableView, UIActivityIndicatorView, WCNewShareCardListLogicController, MMUIScrollView, WCShareCardListLoadingHeaderView;

@interface WCNewShareCardListViewController : MMUIViewController <WCNewShareCardListLogicDelegate, UITableViewDelegate, UITableViewDataSource, EGORefreshTableHeaderDelegate, WCCardPackageViewControllerDelegate, WCNewCardDetailViewControllerDelegate, WCActionSheetDelegate, WCShareCardMyCardEntryViewDelegate, MMTipsViewControllerDelegate> {
	BOOL _bIsOtherCityListShow;
	BOOL _bIsBackFromMyCardPkgViewController;
	BOOL _bIsShowUnReadMsgSection;
	BOOL _isHeadRefreshing;
	BOOL _isNoDragging;
	BOOL _isLoadMoreDuringOneDrag;
	WCNewShareCardListLogicController* _logicController;
	MMUIView* _navHeaderView;
	MMTableView* _tableView;
	MMUIView* _unReadTipsView;
	MMUIView* _shareCardEmptyTipsView;
	MMUIView* _otherCityEntryContentView;
	MMUIScrollView* _emptyDataTipsView;
	WCShareCardListLoadingHeaderView* _headerRefreshView;
	MMUIView* _tableFooterView;
	UIActivityIndicatorView* _footerActivityView;
	float _lastRefreshStartOffsetY;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL isLoadMoreDuringOneDrag;
@property(assign, nonatomic) BOOL isNoDragging;
@property(assign, nonatomic) float lastRefreshStartOffsetY;
@property(assign, nonatomic) BOOL isHeadRefreshing;
@property(retain, nonatomic) UIActivityIndicatorView* footerActivityView;
@property(retain, nonatomic) MMUIView* tableFooterView;
@property(retain, nonatomic) WCShareCardListLoadingHeaderView* headerRefreshView;
@property(assign, nonatomic) BOOL bIsShowUnReadMsgSection;
@property(assign, nonatomic) BOOL bIsBackFromMyCardPkgViewController;
@property(assign, nonatomic) BOOL bIsOtherCityListShow;
@property(retain, nonatomic) MMUIScrollView* emptyDataTipsView;
@property(retain, nonatomic) MMUIView* otherCityEntryContentView;
@property(retain, nonatomic) MMUIView* shareCardEmptyTipsView;
@property(retain, nonatomic) MMUIView* unReadTipsView;
@property(retain, nonatomic) MMTableView* tableView;
@property(retain, nonatomic) MMUIView* navHeaderView;
@property(retain, nonatomic) WCNewShareCardListLogicController* logicController;
-(void).cxx_destruct;
-(void)onClickTipsBtn:(id)btn Index:(int)index;
-(void)showFirstUseShareCardTip;
-(void)tryShowShareCardTips;
-(void)setHasEnterShareCardListBefore;
-(BOOL)hasEnterShareCardListBefore;
-(void)onDeleteShareCard:(id)card;
-(void)onShareCardConsumed:(id)consumed isGetReward:(BOOL)reward;
-(void)onCardShareComplete;
-(void)onLoadMoreLayoutDataEnd;
-(void)onGetHomePageLayoutFail;
-(void)onTableViewNeedReloadWithAnimation:(BOOL)animation;
-(void)otherCityEntryBtnPress:(id)press;
-(void)tryAnimationToNewCard;
-(void)setTableFooterNoData;
-(void)updateTableFooterHasMore:(BOOL)more;
-(void)loadMoreLayoutData;
-(void)onShowAllMessage;
-(void)reloadData;
-(BOOL)egoRefreshTableHeaderDataSourceIsLoading:(id)loading;
-(void)egoRefreshTableHeaderDidTriggerRefresh:(id)egoRefreshTableHeader;
-(void)stopRefreshHeaderView;
-(void)refreshHead;
-(void)scrollViewDidEndScrollingAnimation:(id)scrollView;
-(void)scrollViewDidScroll:(id)scrollView;
-(void)scrollViewWillBeginDecelerating:(id)scrollView;
-(void)scrollViewDidEndDragging:(id)scrollView willDecelerate:(BOOL)decelerate;
-(void)scrollViewWillBeginDragging:(id)scrollView;
-(void)openCardDetailViewControllerWithShareCardList:(id)shareCardList;
-(void)handleSelectOtherCityCardInRow:(unsigned)row;
-(void)handleSelectLocalCityCardInRow:(unsigned)row;
-(void)openMyCard;
-(void)showMessageListByNewMsg;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didUnhighlightRowAtIndexPath:(id)indexPath;
-(void)tableView:(id)view didHighlightRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(id)tableView:(id)view viewForHeaderInSection:(int)section;
-(float)tableView:(id)view heightForHeaderInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)createOtherCityItemCellContentViewAtIndexPath:(id)indexPath withCell:(id)cell;
-(void)createLocalCityItemCellContentViewAtIndexPath:(id)indexPath withCell:(id)cell;
-(void)crateMyCardPkgEntryCellContentView:(id)view;
-(void)createUnReadMsgCellContentView:(id)view;
-(id)createOtherCityCardHaederView;
-(id)createLocalCityCardHeaderView;
-(id)createMyCardPkgHeaderView;
-(void)showNoMyCardAndNoShareCardView;
-(void)makeShareCardEmptyTipsView;
-(float)calcLocalCityHeaderViewHeight;
-(id)getCardMsgTipWording;
-(id)genNewMessageTipView;
-(void)initTableView;
-(void)initNavigationBarItem;
-(void)initView;
-(void)initData;
-(void)viewWillBePoped:(BOOL)view;
-(void)viewDidDisappear:(BOOL)view;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(BOOL)useTransparentNavibar;
-(void)dealloc;
@end

