/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "WCNewYearSightPlayViewMaskDelegate.h"
#import "SightPlayerViewDelegate.h"
#import "IZCWScrollNumViewDelegate.h"

@class UILabel, UIView, ZCWScrollNumView, UIImageView, NSString, UIButton, MMWebImageView, UIScrollView, WCNewYearSightPlayView, WCNewYearHBDetailData, MMAVPlayerItemWrap;
@protocol IWCNewYearHBDetailViewDelegate;

@interface WCNewYearHBDetailView : XXUnknownSuperclass <WCNewYearSightPlayViewMaskDelegate, SightPlayerViewDelegate, IZCWScrollNumViewDelegate> {
	MMAVPlayerItemWrap* _playerWrap;
	WCNewYearHBDetailData* _detailData;
	XXStruct_pwHToB _sightDuration;
	BOOL _hasGetDuration;
	UIScrollView* _bgView;
	UIButton* _closeBtn;
	UIView* _coverFrameView;
	MMWebImageView* _coverImgView;
	WCNewYearSightPlayView* _sightView;
	UIImageView* _adFrameView;
	UIButton* _adLinkBtn;
	ZCWScrollNumView* _numView;
	UIImageView* _headImgView;
	UILabel* _nameLabel;
	UILabel* _moneyLabel;
	UILabel* _tipsLabel;
	id<IWCNewYearHBDetailViewDelegate> _delegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<IWCNewYearHBDetailViewDelegate> delegate;
-(void).cxx_destruct;
-(void)onSingleClicked;
-(void)onResume;
-(void)onStack;
-(void)onNumViewAnimationDidStop;
-(void)onLeftBarButtonClicked;
-(void)configNumView;
-(void)pauseSight;
-(void)playSight;
-(void)onClickAdBtn:(id)btn;
-(void)showCloseBtn;
-(void)showH5Entrance;
-(void)startPlaying;
-(void)stopForShake;
-(void)updateWithDetailData:(id)detailData;
-(void)setupNormalSubviews;
-(void)layoutSubviews;
-(CGRect)getFinalBoundsForDetailViewWithBoundSize:(CGSize)boundSize;
-(id)getHBDetailData;
-(void)dealloc;
-(id)init;
@end

