/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMUIView.h"
#import "IWCShareCardPkgExt.h"
#import "WCGroupTagViewControllerDelegate.h"

@class MMLoadingView, UIImageView, NSString, UIButton, WCShareCardData, NSArray, UIScrollView, MMUILabel, NSMutableArray;
@protocol WCNewShareCardConsumedViewDelegate;

@interface WCNewShareCardConsumedView : MMUIView <IWCShareCardPkgExt, WCGroupTagViewControllerDelegate> {
	BOOL _followCheckBoxSelected;
	BOOL _bIsStatusBarBlack;
	BOOL _isSelectTagGroup;
	id<WCNewShareCardConsumedViewDelegate> _delegate;
	NSArray* _shareCardTPInfoList;
	WCShareCardData* _curShareCardData;
	NSString* _consumedBoxId;
	NSString* _subAppUserName;
	NSString* _subAppWording;
	NSString* _retMsg;
	UIScrollView* _contentView;
	MMUIView* _topContainerView;
	MMUIView* _bottomContainerView;
	MMUIView* _whoCanSeeContainerView;
	MMUIView* _shareInfoContainerView;
	UIButton* _closeBtn;
	UIImageView* _line1ImageView;
	UIImageView* _line2ImageView;
	MMLoadingView* _loadingViewX;
	MMUILabel* _whoCanSeeResultLabel;
	NSMutableArray* _arrGroupUser;
	NSMutableArray* _arrBlackUser;
	NSMutableArray* _arrGroupUserLabelID;
	NSMutableArray* _arrBlackUserLabelID;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSMutableArray* arrBlackUserLabelID;
@property(retain, nonatomic) NSMutableArray* arrGroupUserLabelID;
@property(retain, nonatomic) NSMutableArray* arrBlackUser;
@property(retain, nonatomic) NSMutableArray* arrGroupUser;
@property(assign, nonatomic) BOOL isSelectTagGroup;
@property(assign, nonatomic) BOOL bIsStatusBarBlack;
@property(assign, nonatomic) BOOL followCheckBoxSelected;
@property(retain, nonatomic) MMUILabel* whoCanSeeResultLabel;
@property(retain, nonatomic) MMLoadingView* loadingViewX;
@property(retain, nonatomic) UIImageView* line2ImageView;
@property(retain, nonatomic) UIImageView* line1ImageView;
@property(retain, nonatomic) UIButton* closeBtn;
@property(retain, nonatomic) MMUIView* shareInfoContainerView;
@property(retain, nonatomic) MMUIView* whoCanSeeContainerView;
@property(retain, nonatomic) MMUIView* bottomContainerView;
@property(retain, nonatomic) MMUIView* topContainerView;
@property(retain, nonatomic) UIScrollView* contentView;
@property(retain, nonatomic) NSString* retMsg;
@property(retain, nonatomic) NSString* subAppWording;
@property(retain, nonatomic) NSString* subAppUserName;
@property(retain, nonatomic) NSString* consumedBoxId;
@property(retain, nonatomic) WCShareCardData* curShareCardData;
@property(retain, nonatomic) NSArray* shareCardTPInfoList;
@property(assign, nonatomic) __weak id<WCNewShareCardConsumedViewDelegate> delegate;
-(void).cxx_destruct;
-(void)GroupTagViewControllerWillDissappear;
-(void)onShareCard:(id)card TpID:(id)anId andCardInfo:(id)info;
-(void)stopLoadingWithFailText:(id)failText;
-(void)stopLoadingWithOKText:(id)oktext;
-(void)startLoadingWithText:(id)text;
-(void)stopLoading;
-(void)startLoadingNonBlock;
-(void)startLoadingBlocked;
-(void)clickWhoCanSeeBtn:(id)btn;
-(void)onAttentionBtnClicked:(id)clicked;
-(void)onShareBtnClicked:(id)clicked;
-(void)onCloseBtnClicked:(id)clicked;
-(void)initWhoCanSeeEntranceView;
-(void)initShareInfoContainerView;
-(void)initBottomContainerView;
-(void)initTopContainerViewWithError:(BOOL)error;
-(void)initNormalView;
-(void)initView;
-(void)layoutSubviews;
-(void)closeConsumedView;
-(void)showConsumedViewWithAnimation:(BOOL)animation isStatusBarBlack:(BOOL)black;
-(id)initWithFrame:(CGRect)frame withConsumedInfo:(id)consumedInfo consumedCardID:(id)anId consumedBoxId:(id)anId4 subscribeAppUserName:(id)name subscribeWording:(id)wording retMsg:(id)msg;
-(void)dealloc;
@end

