/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "SightIconViewDelegate.h"
#import "SightPlayerView.h"

@class SightIconView, UIView, NSString, UIImageView;
@protocol WCNewYearSightPlayViewMaskDelegate;

@interface WCNewYearSightPlayView : SightPlayerView <SightIconViewDelegate> {
	UIImageView* m_thumbImg;
	SightIconView* m_progressView;
	UIView* m_coverMask;
	int m_currMaskType;
	id<WCNewYearSightPlayViewMaskDelegate> _maskDelegate;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) __weak id<WCNewYearSightPlayViewMaskDelegate> maskDelegate;
-(void).cxx_destruct;
-(void)onDoubleClickWCSight:(id)sight;
-(void)onClickWCSight:(id)sight;
-(void)LongPressEvents:(id)events;
-(void)onProgressEnd;
-(void)showCoverMask:(int)mask;
-(void)initCoverMask;
-(void)setProgressStep:(float)step;
-(void)updateProgress:(float)progress;
-(XXStruct_pwHToB)getSightDuration;
-(id)init;
@end

