/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"

@class WCSocialInfluenceInfo;

@interface WCObjectOperation : XXUnknownSuperclass <NSCoding> {
	int snsOperateFlag;
	WCSocialInfluenceInfo* socialInfluenceInfo;
}
@property(retain, nonatomic) WCSocialInfluenceInfo* socialInfluenceInfo;
@property(assign, nonatomic) int snsOperateFlag;
-(void).cxx_destruct;
-(id)description;
-(id)copyWithZone:(NSZone*)zone;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
-(id)init;
@end

