/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMUIView.h"

@class NSArray;

@interface WCOrderKeyValueView : MMUIView {
	NSArray* _items;
	id _target;
}
@property(assign, nonatomic) __weak id target;
@property(retain, nonatomic) NSArray* items;
-(void).cxx_destruct;
-(id)copyableTextView;
-(id)detailLabel;
-(id)nameLabel;
-(id)lineView;
-(void)setupViews;
-(id)init;
-(void)dealloc;
@end

