/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "PBMessageObserverDelegate.h"

@protocol WCOutGetProductListCgiDelegate;

@interface WCOutGetProductListCgi : XXUnknownSuperclass <PBMessageObserverDelegate> {
	unsigned long _eventID;
	id<WCOutGetProductListCgiDelegate> _delegate;
}
@property(assign, nonatomic) __weak id<WCOutGetProductListCgiDelegate> delegate;
@property(assign, nonatomic) unsigned long eventID;
+(id)cgiWithDelegate:(id)delegate;
-(void).cxx_destruct;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(void)fail;
-(void)start:(id)start reqCurrency:(id)currency;
-(void)dealloc;
@end

