/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCOutCountryCodeDelegate.h"
#import "MMUIViewController.h"
#import "UIGestureRecognizerDelegate.h"
#import "WCOutDialPadDelegate.h"

@class UIImageView, UILabel, NSMutableString, WCOutDialPad, NSString, UIButton;

@interface WCOutDialViewController : MMUIViewController <WCOutDialPadDelegate, UIGestureRecognizerDelegate, WCOutCountryCodeDelegate> {
	UIButton* m_deleteBtn;
	UIButton* m_countryCodeBtn;
	UIButton* m_countryCodeBtn_Hide_ForArrowAdjust;
	UILabel* m_phoneNumLabel;
	UILabel* m_contactNameLabel;
	WCOutDialPad* m_dialPad;
	UIImageView* downarrow;
	BOOL m_isEditingCountryCode;
	NSString* m_countryCodeChosen;
	NSMutableString* m_editingCountryCodeText;
	NSMutableString* m_editingPhoneText;
	NSString* m_defaultInput;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)CountryCodePickerDidPickCountryCode:(id)countryCodePicker;
-(void)chooseCountryCode;
-(void)OnPressedDialPadFunctionBtnWithType:(unsigned)type;
-(void)OnPressedDialPadKeyWithText:(id)text andKeyCode:(int)code;
-(void)updatePhoneNumLabel;
-(void)updateCountryCodeAndNeedSave:(BOOL)save;
-(void)removeLastTextFromPhoneNumText;
-(void)removeLastTextFromCountryCodeText;
-(void)removeLastTextFromInput;
-(void)appendToPhoneNumTextWithNextChar:(id)nextChar;
-(void)beginToEditCountryCode;
-(BOOL)checkIsEditingCountryCode:(BOOL)code;
-(void)appendToCountryCodeTextWithNextChar:(id)nextChar;
-(void)appendToInputWithNextChar:(id)nextChar;
-(void)appendToInputWithText:(id)text;
-(BOOL)canPerformAction:(SEL)action withSender:(id)sender;
-(BOOL)canBecomeFirstResponder;
-(void)onPasteToInputLabel;
-(void)onCopyInputLabel;
-(void)onShowOperationMenu:(id)menu;
-(void)didLongPressDeleteBtn:(id)btn;
-(void)didPressedButton:(id)button;
-(void)showLogWithLongPressed:(id)longPressed;
-(void)openKitchen;
-(void)initView;
-(void)viewWillAppear:(BOOL)view;
-(void)didReceiveMemoryWarning;
-(void)viewDidLayoutSubviews;
-(void)viewDidLoad;
-(id)initWithInput:(id)input;
@end

