/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSDictionary, NSString;

@interface WCOutPhoneContact : XXUnknownSuperclass {
	BOOL isWeChatFriend;
	NSString* nickname;
	NSString* nicknamePinYin;
	NSString* nicknamePinYinShort;
	NSDictionary* phoneWithLabels;
	NSDictionary* phoneToMd5Dic;
	NSString* mmNickname;
	NSString* mmUsername;
	NSString* bigHeadImgUrl;
	NSString* smallHeadImgUrl;
	NSString* mainCountryCode;
	NSString* mainPurePhoneNum;
}
@property(retain, nonatomic) NSString* mainPurePhoneNum;
@property(retain, nonatomic) NSString* mainCountryCode;
@property(assign, nonatomic) BOOL isWeChatFriend;
@property(readonly, assign, nonatomic) BOOL isWeChatUser;
@property(readonly, assign, nonatomic) BOOL isAdressBookContact;
@property(retain, nonatomic) NSString* smallHeadImgUrl;
@property(retain, nonatomic) NSString* bigHeadImgUrl;
@property(retain, nonatomic) NSString* mmUsername;
@property(retain, nonatomic) NSString* mmNickname;
@property(retain, nonatomic) NSDictionary* phoneToMd5Dic;
@property(retain, nonatomic) NSDictionary* phoneWithLabels;
@property(retain, nonatomic) NSString* nicknamePinYinShort;
@property(retain, nonatomic) NSString* nicknamePinYin;
@property(retain, nonatomic) NSString* nickname;
-(void).cxx_destruct;
-(id)initWithWCOutPhoneContact:(id)wcoutPhoneContact;
-(id)initWithWCOutRecentCallItem:(id)wcoutRecentCallItem;
-(id)initWithMMPhoneContact:(id)mmphoneContact;
@end

