/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSArray, NSString;

@interface WCPayFetchInfo : XXUnknownSuperclass <NSCoding> {
	BOOL _m_bShowCharge;
	BOOL _m_bCalcCharge;
	BOOL _m_bISFullFetchDirect;
	NSString* _m_nsFetchChargeTitle;
	NSString* _m_nsFetchChargeRemark;
	NSArray* _m_arrAlertContent;
	NSArray* _m_arrKey;
	NSArray* _m_arrValue;
	unsigned long _m_uiRemainFee;
	unsigned long _m_uiMinChargeFee;
}
@property(assign, nonatomic) BOOL m_bISFullFetchDirect;
@property(assign, nonatomic) unsigned long m_uiMinChargeFee;
@property(assign, nonatomic) unsigned long m_uiRemainFee;
@property(assign, nonatomic) BOOL m_bCalcCharge;
@property(assign, nonatomic) BOOL m_bShowCharge;
@property(retain, nonatomic) NSArray* m_arrValue;
@property(retain, nonatomic) NSArray* m_arrKey;
@property(retain, nonatomic) NSArray* m_arrAlertContent;
@property(retain, nonatomic) NSString* m_nsFetchChargeRemark;
@property(retain, nonatomic) NSString* m_nsFetchChargeTitle;
+(id)fetchInfoOfJSONDic:(id)jsondic;
-(void).cxx_destruct;
-(void)encodeWithCoder:(id)coder;
-(id)initWithCoder:(id)coder;
@end

