/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface WCPayCheckPayPwdByTokenResponse : XXUnknownSuperclass {
	NSString* m_nsCheckPwdToken;
	BOOL m_bIsFreeSMS;
	NSString* m_nsMobileNo;
	NSString* m_nsRelationKey;
}
@property(retain, nonatomic) NSString* m_nsRelationKey;
@property(retain, nonatomic) NSString* m_nsMobileNo;
@property(assign, nonatomic) BOOL m_bIsFreeSMS;
@property(retain, nonatomic) NSString* m_nsCheckPwdToken;
-(void).cxx_destruct;
-(void)dealloc;
@end

