/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "WCBaseTextFieldItem.h"

@class TPIDKeyboardView;

@interface WCPayInputTextInfoCtrlItem : WCBaseTextFieldItem {
	TPIDKeyboardView* keyboardView;
}
-(void).cxx_destruct;
-(void)autoRemarkKeyBoradType;
-(BOOL)textField:(id)field shouldChangeCharactersInRange:(NSRange)range replacementString:(id)string;
-(void)dealloc;
-(id)initWithTitle:(id)title tip:(id)tip key:(id)key;
@end

