/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSNumber, NSString;

@interface WCPayLoanEntryInfo : XXUnknownSuperclass <NSCoding> {
	BOOL _m_isShowEntry;
	unsigned long _m_index;
	NSString* _m_loanJumpUrl;
	NSString* _m_title;
	NSString* _m_tips;
	NSNumber* _m_availableOtb;
	NSNumber* _m_isOverdue;
}
@property(retain, nonatomic) NSNumber* m_isOverdue;
@property(retain, nonatomic) NSNumber* m_availableOtb;
@property(retain, nonatomic) NSString* m_tips;
@property(retain, nonatomic) NSString* m_title;
@property(retain, nonatomic) NSString* m_loanJumpUrl;
@property(assign, nonatomic) unsigned long m_index;
@property(assign, nonatomic) BOOL m_isShowEntry;
-(void).cxx_destruct;
-(void)dealloc;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
@end

