/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "WCPayBaseViewController.h"
#import "WCBizTipViewDelegate.h"
#import "ILinkEventExt.h"

@class WCBaseTextFieldItem, UILabel, WCPayValidDateItem, NSString, UIButton, WCBizInfoGroup, WCPayCVVItem, RichTextView, WCBizTipView, WCPayPhoneTextItem;
@protocol WCPayResetBalanceTelephoneViewControllerDelegate;

@interface WCPayResetBalanceTelephoneViewController : WCPayBaseViewController <ILinkEventExt, WCBizTipViewDelegate> {
	UIButton* m_footerButton;
	WCBizInfoGroup* m_group;
	WCPayPhoneTextItem* m_textFieldItem;
	WCPayValidDateItem* m_pikerValidDateItem;
	WCPayCVVItem* m_textFieldCVVItem;
	WCBaseTextFieldItem* m_textAutoFilledCardNumberItem;
	RichTextView* richTextView;
	id<WCPayResetBalanceTelephoneViewControllerDelegate> m_delegate;
	WCBizTipView* introView;
	BOOL m_bAutoFilledCardNumber;
	BOOL m_bShowedFavorInfo;
	NSString* m_headerTitle;
	UILabel* autoFilledNumberLabel;
	NSString* m_viewTitle;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(readonly, assign, nonatomic) BOOL m_bAutoFilledCardNumber;
-(void).cxx_destruct;
-(void)footerTipAction:(id)action;
-(void)setAutoFilledCardNumber;
-(void)OnWCBizTipViewClosed;
-(void)showDetailTip;
-(void)onPhoneClicked:(id)clicked withRect:(CGRect)rect;
-(void)onLinkClicked:(id)clicked withRect:(CGRect)rect;
-(void)stopLogicLoading;
-(void)startLogicLoading;
-(void)setDelegate:(id)delegate;
-(void)didReceiveMemoryWarning;
-(void)WCBaseInfoItemEndEdit:(id)edit;
-(void)WCBaseInfoItemEditChanged:(id)changed;
-(void)OnClearAutoFilledCardNumber;
-(void)CheckData;
-(void)onNext;
-(void)scanAction:(id)action;
-(void)refreshViewWithData:(id)data;
-(void)viewDidLoad;
-(void)viewWillLayoutSubviews;
-(void)makeInfoCell:(id)cell cellInfo:(id)info;
-(void)reloadTableView;
-(void)initNavigationBar;
-(void)FillCardNumberCancel;
-(void)setShowedFavorInfo;
-(void)initFooterView;
-(void)dealloc;
-(void)setTitle:(id)title;
-(void)setHeaderTip:(id)tip;
-(id)init;
@end

