/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class UIView, WCProductActionItemInfo;

@interface WCProductActionItemCacheInfo : XXUnknownSuperclass {
	WCProductActionItemInfo* _itemInfo;
	UIView* _pushView;
	UIView* _popView;
}
@property(retain, nonatomic) UIView* popView;
@property(retain, nonatomic) UIView* pushView;
@property(retain, nonatomic) WCProductActionItemInfo* itemInfo;
-(void).cxx_destruct;
@end

