/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSCoding.h"
#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface WCRedEnvelopesInfo : XXUnknownSuperclass <NSCoding> {
	NSString* sendId;
	BOOL hasReward;
	BOOL bFree;
}
@property(assign, nonatomic) BOOL bFree;
@property(assign, nonatomic) BOOL hasReward;
@property(retain, nonatomic) NSString* sendId;
-(void).cxx_destruct;
-(id)initWithCoder:(id)coder;
-(void)encodeWithCoder:(id)coder;
-(id)init;
@end

