/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class NSString;

@interface WCRedEnvelopesSendedRedEnvelopesInfo : XXUnknownSuperclass {
	int m_enWCRedEnvelopesType;
	int m_enWCRedEnvelopesKind;
	NSString* m_nsSendTitle;
	unsigned long m_uiSendTime;
	NSString* m_nsSendTime;
	long m_lTotalAmount;
	long m_lTotalNum;
	long m_lRecNum;
	int m_enWCRedEnvelopesStatus;
	unsigned long m_uiThxCount;
	NSString* m_nsSendID;
}
@property(retain, nonatomic) NSString* m_nsSendID;
@property(assign, nonatomic) unsigned long m_uiThxCount;
@property(assign, nonatomic) int m_enWCRedEnvelopesStatus;
@property(assign, nonatomic) long m_lRecNum;
@property(assign, nonatomic) long m_lTotalNum;
@property(assign, nonatomic) long m_lTotalAmount;
@property(retain, nonatomic) NSString* m_nsSendTime;
@property(assign, nonatomic) unsigned long m_uiSendTime;
@property(retain, nonatomic) NSString* m_nsSendTitle;
@property(assign, nonatomic) int m_enWCRedEnvelopesKind;
@property(assign, nonatomic) int m_enWCRedEnvelopesType;
-(void).cxx_destruct;
@end

