/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "NSObject.h"


@protocol WCShareCardBatchGetMgrDelegate <NSObject>
@optional
-(void)onBatchGetEnd:(unsigned long)end;
-(void)onBatchGetShareCardList:(id)list ErrCode:(int)code;
@end

