/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"

@class WCShareCardLayoutCacheItem;

@interface WCShareCardLayoutCache : MMObject {
	WCShareCardLayoutCacheItem* _cacheItem;
}
@property(retain, nonatomic) WCShareCardLayoutCacheItem* cacheItem;
-(void).cxx_destruct;
-(void)saveLayoutCache;
-(void)initForSave;
-(void)loadLayoutCache;
-(void)dealloc;
-(id)init;
@end

