/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library

@class WCSnsABTestTipData, NSString, ABTestItem, NSMutableDictionary;

@interface WCSnsABTestInfo : XXUnknownSuperclass {
	ABTestItem* abtestItem;
	NSString* language;
	unsigned experType;
	NSMutableDictionary* dicTipData;
	WCSnsABTestTipData* firstTipData;
}
@property(retain, nonatomic) WCSnsABTestTipData* firstTipData;
@property(retain, nonatomic) NSMutableDictionary* dicTipData;
@property(assign, nonatomic) unsigned experType;
@property(retain, nonatomic) NSString* language;
@property(retain, nonatomic) ABTestItem* abtestItem;
-(void).cxx_destruct;
-(id)init;
@end

