/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "EGORefreshTableHeaderView.h"

@class MMActivityIndicator, UIImageView;

@interface WCTimeLineHeaderView : EGORefreshTableHeaderView {
	MMActivityIndicator* m_reflashImageView;
	UIImageView* m_tipBkg;
}
-(void).cxx_destruct;
-(void)egoRefreshScrollViewDidScroll:(id)egoRefreshScrollView;
-(void)onStateOfLoading;
-(void)onStateOfNormal;
-(void)onStateOfPulling;
-(id)initWithFrame:(CGRect)frame;
@end

