/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMUIView.h"

@protocol WCTimelineTipViewDelegate;

@interface WCTimelineTipView : MMUIView {
	id<WCTimelineTipViewDelegate> _delegate;
	BOOL _showTipNow;
	BOOL _closeTipNow;
	BOOL _hidingTip;
}
@property(assign, nonatomic) BOOL showTipNow;
@property(assign, nonatomic) __weak id<WCTimelineTipViewDelegate> delegate;
+(id)showTipWithDelegate:(id)delegate parentView:(id)view content:(id)content;
-(void).cxx_destruct;
-(void)showTipView:(float)view withAnimationTimes:(id)animationTimes AnimationValues:(id)values;
-(void)closeTipView:(BOOL)view;
-(void)showTipView:(BOOL)view;
-(void)hideTipView:(BOOL)view;
-(void)animationDidStop:(id)animation finished:(BOOL)finished;
-(id)getAnimationLayer;
-(void)performBgAction;
-(void)initView;
-(id)init;
@end

