/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMUIView.h"

@class WCDataItem, WCSnsABTestTipData;

@interface WCTimelineCellABTestBaseTip : MMUIView {
	WCSnsABTestTipData* tipData;
	WCDataItem* dataItem;
}
@property(readonly, assign, nonatomic) WCDataItem* dataItem;
@property(readonly, assign, nonatomic) WCSnsABTestTipData* tipData;
+(float)heightForTipView:(id)tipView;
-(void).cxx_destruct;
-(void)resetStatus;
-(void)resetView:(id)view;
-(void)initView;
-(id)initWithTipData:(id)tipData dataItem:(id)item frame:(CGRect)frame;
-(id)initWithTipData:(id)tipData dataItem:(id)item;
@end

