/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "UIAlertViewDelegate.h"
#import "MMUIViewController.h"
#import "WCBaseInfoItemDelegate.h"
#import "ILocationMgrExt.h"
#import "WCAddressLogicMgrExt.h"
#import "MMTableViewInfoDelegate.h"
#import "POICategoryDelegate.h"
#import "ICreatePOIMgrExt.h"

@class WCBaseTextFieldItem, NSString, WCPOIAddressPickerItem, MMUIButton, MMTableViewInfo, NSMutableArray, CLLocation;
@protocol POICreateDelegate;

@interface WCTimelinePOICreateViewController : MMUIViewController <MMTableViewInfoDelegate, WCBaseInfoItemDelegate, ICreatePOIMgrExt, POICategoryDelegate, WCAddressLogicMgrExt, ILocationMgrExt, UIAlertViewDelegate> {
	NSString* _poiName;
	CLLocation* _location;
	id<POICreateDelegate> _delegate;
	MMTableViewInfo* _tableViewInfo;
	NSMutableArray* _infoItems;
	WCBaseTextFieldItem* _poiNameTextFieldItem;
	WCPOIAddressPickerItem* _districtPickerItem;
	WCBaseTextFieldItem* _addressTextFieldItem;
	WCBaseTextFieldItem* _categoryPickerItem;
	WCBaseTextFieldItem* _telephoneTextFieldItem;
	MMUIButton* _seeMoreButton;
	unsigned long _geoTag;
	BOOL _lockSelection;
	BOOL _isLiteView;
	unsigned _createPOICellIndex;
	NSString* _currentSearchID;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* currentSearchID;
@property(assign, nonatomic) unsigned createPOICellIndex;
-(void).cxx_destruct;
-(void)WCBaseInfoItemBeginEdit:(id)edit;
-(void)onDidFindAddress:(id)on forTag:(unsigned long)tag;
-(void)OnGetGetAllAddressStageData:(id)data Error:(id)error;
-(void)onSelectedCategory:(id)category;
-(void)OnCreatePOI:(id)poi ID:(id)anId Error:(int)error;
-(void)clickInfoCell:(id)cell index:(id)index;
-(void)makeInfoCell:(id)cell cellInfo:(id)info;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(BOOL)validateData;
-(void)onDone;
-(void)onReturn;
-(void)onSeeMore;
-(void)hideKeyboard;
-(void)selectAddress:(id)address;
-(void)willRotateToInterfaceOrientation:(int)interfaceOrientation duration:(double)duration;
-(void)initDistrict;
-(void)initOptionalData;
-(void)initRequiredData;
-(void)initTableView;
-(void)initView;
-(void)viewDidLoad;
-(void)dealloc;
-(id)initWithPOIName:(id)poiname Location:(id)location Delegate:(id)delegate;
@end

