/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WCActionSheet.h"
#import "WeChat-Structs.h"

@class WCUIActionSheetLogic;

@interface WCUIActionSheet : WCActionSheet {
	WCUIActionSheetLogic* logic;
	id m_userData;
}
@property(retain, nonatomic) id m_userData;
-(void).cxx_destruct;
-(void)addDestructiveButtonTitle:(id)title target:(id)target sel:(SEL)sel;
-(void)addCancelBtnTitle:(id)title target:(id)target sel:(SEL)sel;
-(void)addBtnTitle:(id)title target:(id)target sel:(SEL)sel;
-(id)initWithTitle:(id)title;
@end

