/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"

@class CContact, UIImageView;

@interface WCWatchChatRoomImageView : XXUnknownSuperclass {
	UIImageView* _imageView;
	CContact* _contact;
}
@property(retain, nonatomic) CContact* contact;
-(void).cxx_destruct;
-(id)initWithFrame:(CGRect)frame contact:(id)contact;
@end

