/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WeChat-Structs.h"
#import "MMObject.h"
#import "PBCoding.h"

@class NSString;

@interface WebviewLocalResItem : MMObject <PBCoding> {
	NSString* _localResId;
	NSString* _savePath;
	NSString* _svrId;
	NSString* _appId;
	NSString* _cdnUrl;
	NSString* _cdnAESKey;
	unsigned long _fileSize;
	NSString* _mediaType;
	NSString* _fileExt;
	NSString* localResId;
	NSString* savePath;
	NSString* svrId;
	NSString* appId;
	NSString* cdnUrl;
	NSString* cdnAESKey;
	unsigned long fileSize;
	NSString* mediaType;
	NSString* fileExt;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(retain, nonatomic) NSString* fileExt;
@property(retain, nonatomic) NSString* mediaType;
@property(assign, nonatomic) unsigned long fileSize;
@property(retain, nonatomic) NSString* cdnAESKey;
@property(retain, nonatomic) NSString* cdnUrl;
@property(retain, nonatomic) NSString* appId;
@property(retain, nonatomic) NSString* svrId;
@property(retain, nonatomic) NSString* savePath;
@property(retain, nonatomic) NSString* localResId;
+(void)initialize;
-(void).cxx_destruct;
-(const map<unsigned long, unsigned long, std::__1::less<unsigned long>, std::__1::allocator<std::__1::pair<const unsigned long, unsigned long> > >*)getValueTagIndexMap;
-(id)getValueTypeTable;
@end

