/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WebviewJSEventHandlerBase.h"
#import "ProductDetailViewControllerDelegate.h"

@class JSEvent, NSString;

@interface WebviewJSEventHandler_openProductViewWithPid : WebviewJSEventHandlerBase <ProductDetailViewControllerDelegate> {
	JSEvent* _jsEvent;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)productViewWillReturn;
-(void)handleJSEvent:(id)event HandlerFacade:(id)facade ExtraData:(id)data;
@end

