/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WebviewJSEventHandlerBase.h"
#import "IEnterpriseGroupMgrExt.h"

@class NSString;

@interface WebViewJSEventHandler_openEnterpriseChat : WebviewJSEventHandlerBase <IEnterpriseGroupMgrExt> {
	NSString* _enterpriseChatScene;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)dealloc;
-(void)onInitiateBizChat:(id)chat errorCode:(int)code extDic:(id)dic;
-(void)handleJSEvent:(id)event HandlerFacade:(id)facade ExtraData:(id)data;
@end

