/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "PBMessageObserverDelegate.h"
#import "WebviewJSEventHandlerBase.h"
#import "MMWebViewDelegate.h"

@class JSEvent, NSString;

@interface WebviewJSEventHandler_getH5PrepayRequest : WebviewJSEventHandlerBase <PBMessageObserverDelegate, MMWebViewDelegate> {
	NSString* _jsInjectCode;
	JSEvent* m_jsEvent;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)onWebViewDidFinishLoad:(id)onWebView;
-(void)MessageReturn:(id)aReturn Event:(unsigned long)event;
-(void)doInjectJS;
-(void)getJumpUrl:(id)url complete:(id)complete;
-(void)sendResult:(BOOL)result jsEvent:(id)event;
-(void)handleJSEvent:(id)event HandlerFacade:(id)facade ExtraData:(id)data;
@end

