/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMService.h"
#import "WebResourceUploadHelperDelegate.h"
#import "WebviewResourceDownloadHelperDelegate.h"
#import "WebResourceCDNUploadHelperDelegate.h"
#import "WebResourceCDNDownloadHelperDelegate.h"
#import "MMService.h"

@class WebResourceCDNUploadHelper, WebResourceUploadHelper, NSMutableArray, NSRecursiveLock, NSString, WebResourceCDNDownloadHelper, NSMutableDictionary, WebviewResourceDownloadHelper;

@interface WebviewResourceManager : MMService <MMService, WebResourceUploadHelperDelegate, WebviewResourceDownloadHelperDelegate, WebResourceCDNUploadHelperDelegate, WebResourceCDNDownloadHelperDelegate> {
	NSRecursiveLock* _lock;
	NSMutableArray* _resItemArray;
	WebResourceUploadHelper* _uploadHelper;
	WebviewResourceDownloadHelper* _downloadHelper;
	WebResourceCDNUploadHelper* _cdnUploadHelper;
	WebResourceCDNDownloadHelper* _cdnDownloadHelper;
	NSMutableDictionary* _recordPMSDic;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)onItemDownloadProgress:(int)progress Item:(id)item;
-(void)onItemCDNDownloadFinished:(int)finished Item:(id)item;
-(void)onItemUploadProgress:(int)progress Item:(id)item;
-(void)onItemUploadCDNFinished:(int)finished Item:(id)item;
-(void)onItemDownloadFinished:(int)finished Item:(id)item;
-(void)onItemUploadFinished:(int)finished Item:(id)item;
-(void)setRecordPermissionForUrl:(id)url;
-(BOOL)checkRecordPermission:(id)permission;
-(BOOL)uploadLocalImage:(id)image;
-(id)getResItemByLocalId:(id)anId;
-(void)saveLocalImageFinished:(id)finished;
-(BOOL)uploadVideo:(id)video;
-(BOOL)addVideoResource:(id)resource;
-(BOOL)downloadVoice:(id)voice AppId:(id)anId;
-(BOOL)uploadVoice:(id)voice;
-(void)addRecordResource:(id)resource;
-(BOOL)downloadImage:(id)image AppId:(id)anId;
-(void)asyncNotifyResourceDownloadFinish:(id)finish;
-(void)addItemToResArray:(id)resArray;
-(void)addLocalImagesWithOriginalSize:(id)originalSize;
-(void)addLocalImages:(id)images;
-(void)stopAllNetworkTask;
-(id)getLocalVideoPathByResourceId:(id)anId;
-(id)getLocalPathByResourceId:(id)anId;
-(id)getLocalResourceId;
-(void)saveRecordPermissionDic;
-(BOOL)loadRecordPermissionDic;
-(void)saveResItemArray;
-(BOOL)loadResItemArray;
-(id)getUserWebResourceRootDir;
-(void)addAutoCleanTask;
-(void)onServiceInit;
-(id)init;
@end

