/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "IPreEnterWechatLogicExt.h"
#import "UIAlertViewDelegate.h"

@class NSURL, NSString;

@interface WeChatHBHandler : XXUnknownSuperclass <IPreEnterWechatLogicExt, UIAlertViewDelegate> {
	NSString* m_nsAppID;
	NSURL* m_nsAppUrl;
	NSString* m_nsBundleID;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
-(void).cxx_destruct;
-(void)createWeChateHB;
-(id)parseURLParams:(id)params;
-(void)onPreEnterWechatDone;
-(void)cancelWeChatHB;
-(void)startWeChatHB:(id)hb BundleID:(id)anId payInfo:(id)info;
-(void)dealloc;
-(id)init;
@end

