/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WloginTlv.h"

@class NSString;

@interface WloginTlv_0x129 : WloginTlv {
	unsigned dwHoldTime;
	unsigned dwTimeout;
	NSString* phoneNo;
}
@property(copy) NSString* phoneNo;
@property(assign) unsigned dwTimeout;
@property(assign) unsigned dwHoldTime;
-(void)dealloc;
-(int)decode:(char**)decode andBuffLen:(int*)len;
@end

