/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WloginTlv.h"

@class NSData;

@interface WloginTlv_0x105 : WloginTlv {
	NSData* acSig;
	NSData* acPicData;
}
@property(retain) NSData* acPicData;
@property(retain) NSData* acSig;
-(void)dealloc;
-(int)decode:(char**)decode andBuffLen:(int*)len;
@end

