/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WNNoteItemUtilBase.h"


@interface WNNoteFileItemUtil : WNNoteItemUtilBase {
}
-(void)insertItem:(id)item isUpdate:(BOOL)update isConfigData:(BOOL)data;
-(void)onClickItem:(id)item;
-(void)onAddItemBegin:(id)begin;
-(void)dealloc;
-(id)init;
@end

