/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MMObject.h"


@interface WrapMemoryRecordData : MMObject {
	unsigned m_caseID;
	long m_curMemory;
}
@property(assign, nonatomic) long m_curMemory;
@property(assign, nonatomic) unsigned m_caseID;
+(id)recordDataWithMemory:(long)memory onCase:(unsigned)aCase;
-(id)initMemory:(long)memory onCase:(unsigned)aCase;
@end

