/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "MailReceiverEditViewDelegate.h"
#import "MailContactFilterViewDelegate.h"
#import "MMMailContactSelectViewDelegate.h"
#import "UIAlertViewDelegate.h"
#import "MailContentViewDelegate.h"
#import "MailAttachmentViewDelegate.h"
#import "MailAttachmentControlViewDelegate.h"
#import "WCActionSheetDelegate.h"
#import "UITextViewDelegate.h"
#import "WeChat-Structs.h"
#import "UINavigationControllerDelegate.h"
#import "MMUIViewController.h"
#import "IQQMailExt.h"
#import "UITableViewDelegate.h"
#import "UITableViewDataSource.h"

@class MailContentView, CMail, MailSubjectEditView, MMTimer, MailReceiverEditView, MailContactFilterView, MMTableView, NSString, MailAttachmentControlView, NSMutableArray, UIView;

@interface WriteMailViewController : MMUIViewController <UITableViewDelegate, UITableViewDataSource, UITextViewDelegate, WCActionSheetDelegate, UINavigationControllerDelegate, MailContactFilterViewDelegate, MailContentViewDelegate, MailAttachmentViewDelegate, UIAlertViewDelegate, IQQMailExt, MMMailContactSelectViewDelegate, MailReceiverEditViewDelegate, MailAttachmentControlViewDelegate> {
	MMTableView* m_tableView;
	MailContactFilterView* m_filterView;
	MailContentView* m_contentView;
	MailReceiverEditView* m_receiverView;
	MailReceiverEditView* m_ccView;
	MailReceiverEditView* m_bccView;
	MailSubjectEditView* m_topicView;
	UIView* m_ccBccView;
	NSMutableArray* m_arrShowViews;
	MailAttachmentControlView* m_attachmentControlView;
	int m_firstResponderStatus;
	int m_ccBccFlodStatus;
	CMail* m_mail;
	NSMutableArray* m_arrReceiver;
	NSMutableArray* m_arrCc;
	NSMutableArray* m_arrBcc;
	NSMutableArray* m_arrAttachment;
	unsigned long m_uiMailType;
	float m_fKeyboardHeight;
	MMTimer* m_autoSaveTimer;
	unsigned long m_firstResponderTag;
	NSMutableArray* m_arrAttachmentView;
	NSMutableArray* m_arrAllMailContacts;
	NSString* m_nsMailID;
	BOOL m_bFromReadMail;
	BOOL m_bFirstFixContectHeight;
	BOOL m_bPresentModal;
}
@property(readonly, copy) NSString* debugDescription;
@property(readonly, copy) NSString* description;
@property(readonly, assign) Class superclass;
@property(readonly, assign) unsigned hash;
@property(assign, nonatomic) BOOL m_bPresentModal;
@property(assign, nonatomic) BOOL m_bFromReadMail;
@property(retain, nonatomic) NSMutableArray* m_arrAllMailContacts;
-(void).cxx_destruct;
-(void)onMailContactSelectDone:(id)done userInfo:(id)info;
-(void)onMailContactChanged:(id)changed;
-(void)onTextFieldNextItem:(id)item;
-(void)onTextFieldFinishEdit:(id)edit;
-(void)onTextFieldChanged:(id)changed;
-(void)onMailReceiverEditViewHeightChanged:(id)changed;
-(void)onMailContactDoubleClicked:(id)clicked;
-(void)onAddMailContact:(id)contact;
-(int)indexForView:(id)view;
-(void)onFirstResponderResigned;
-(id)getViewController;
-(id)initWithMail:(id)mail mailID:(id)anId mailType:(unsigned long)type;
-(void)uploadAttachment:(id)attachment name:(id)name;
-(id)initWithMail:(id)mail mailType:(unsigned long)type;
-(id)initWithNewEmptyMail:(id)newEmptyMail;
-(id)initWithEmptyMail:(id)emptyMail;
-(id)init;
-(void)dealloc;
-(void)releaseAutoSaveTimer;
-(void)initAutoSaveTimer;
-(void)removeNotificationObservers;
-(void)initNotificationObservers;
-(void)keyboardWillHide:(id)keyboard;
-(void)keyboardDidShow:(id)keyboard;
-(void)keyboardWillShow:(id)keyboard;
-(void)ReleaseTextField;
-(void)viewDidUnload;
-(BOOL)isTextFirstResponder;
-(void)viewDidLayoutSubviews;
-(void)viewDidAppear:(BOOL)view;
-(void)viewWillAppear:(BOOL)view;
-(void)viewDidLoad;
-(void)alertView:(id)view clickedButtonAtIndex:(int)index;
-(void)OnUploadData:(id)data filename:(id)filename ErrNo:(int)no;
-(void)OnGetAllMailContact:(id)contact ErrNo:(int)no;
-(void)OnDeleteAttachment:(id)attachment;
-(void)doDeleteAttachment:(unsigned long)attachment;
-(void)OnResend:(id)resend;
-(void)OnUploadSuccess;
-(void)contentViewDidFinishEdit;
-(void)filterViewBeginDragging;
-(int)tableView:(id)view numberOfRowsInSection:(int)section;
-(int)numberOfSectionsInTableView:(id)tableView;
-(void)tableView:(id)view didSelectRowAtIndexPath:(id)indexPath;
-(float)tableView:(id)view heightForRowAtIndexPath:(id)indexPath;
-(id)tableView:(id)view cellForRowAtIndexPath:(id)indexPath;
-(void)actionSheet:(id)sheet clickedButtonAtIndex:(int)index;
-(void)contactReturn:(id)aReturn;
-(void)didStartWriteMailContent;
-(void)contentLengthChanged:(id)changed;
-(void)contentViewNeedSetContentOffset:(float)offset;
-(id)getFilterName:(id)name;
-(void)reloadTableView;
-(void)setContentResponderStatus;
-(void)onMainContentTap:(id)tap;
-(void)initView;
-(void)initTableItemViews;
-(void)updateRightBarButton;
-(void)OnReturn;
-(void)CheckCancel:(id)cancel;
-(void)initData;
-(BOOL)SendBtnEnable;
-(void)RealSend;
-(void)onSend;
-(void)OnComposeSend:(int)send;
-(void)doSearch:(id)search;
-(void)fixFilterView;
-(void)onAutoSaveTimer;
-(void)deleteDraft;
-(void)loadDraft;
-(void)saveDraft;
-(void)setccBccFlodStatus:(int)status;
-(void)setNextFirstRespondStatus:(int)status;
-(void)setNewFirstResponse;
-(void)setFirstRespondStatus:(int)status;
-(int)getFirstResponderStatusForRow:(int)row;
-(int)getNextResponderStautsForFirstResponderStatus:(int)firstResponderStatus;
-(id)getViewForFirstResponderStatus:(int)firstResponderStatus;
-(void)staticReloadTableView;
-(id)getSelfMailContact;
@end

