/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library


@interface WXCFileDefine : XXUnknownSuperclass {
}
+(id)sdkAccountInfoPath;
+(id)pathOfUserFileMobileNotify:(int)userFileMobileNotify;
+(id)pathOfUserFileRootDir:(int)userFileRootDir;
+(id)pathOfReservedGroupData:(int)reservedGroupData;
+(id)pathOfTogetherData:(int)togetherData;
+(id)pathOfTogetherRootDir:(int)togetherRootDir;
+(id)pathOfDizhuGameDataSave:(int)dizhuGameDataSave;
+(id)pathOfVoipStatiticsDb;
+(id)idcServerListCacheDir;
+(id)fileForPokeMsgCache:(int)pokeMsgCache;
+(id)reportPath;
+(id)networkLibFileDirPath;
+(id)sysConfigPath:(int)path;
+(id)fileForSyncServerKeys;
+(id)pathOfGlobalPhoneInfoDb;
+(id)pathOfGlobalEvilNumberDb;
+(id)pathOfLocalYellowDbWithOutHeader;
+(id)pathOfLocalYellowDb;
+(id)pathOfGlobalSubLocationDbWithOutHeader;
+(id)pathOfGlobalSubLocationDb;
+(id)pathOfGlobalLocationDbWithOutHeader;
+(id)pathOfGlobalLocationDb;
+(id)pathOfFeedBackMsgDb:(int)feedBackMsgDb;
+(id)pathOfGlobalConfigDb;
+(id)pathOfProfileDb:(int)profileDb;
+(id)pathOfTalkFriendInfoCache:(int)talkFriendInfoCache;
+(id)pathOfTalkInfoCacheDir:(int)talkInfoCacheDir;
+(id)pathOfRecommendFriendDb:(int)recommendFriendDb;
+(id)pathOfQcMsgDb:(int)qcMsgDb;
+(id)pathOfCrashReportDb;
+(id)pathFriendSynckey:(int)synckey;
+(id)pathOfFriendDb:(int)friendDb;
+(id)fileForCachePhoneAbility;
+(id)fileForContactsBackupV2DB;
+(id)fileForVoipContactsV2File;
+(id)fileForHasUploadPhonesV2File;
+(id)fileForContactsV2File;
+(id)pathOfFavoriteContactData:(int)favoriteContactData;
+(id)fileForContactsV2DB;
+(id)pathOfFriendListDb:(int)friendListDb;
+(id)pathOfCallLogDb:(int)callLogDb;
+(id)getVoiceMailSetTipsFullPath:(int)path path:(id)path2;
+(id)getVoiceMailFullPath:(id)path;
+(id)getVoiceMailFullPath:(int)path frienduuid:(int)frienduuid time:(long long)time;
+(id)getSysVoiceMailFullPath:(id)path;
+(id)getSysVoiceMailFullPath:(int)path frienduuid:(int)frienduuid time:(long long)time;
+(id)voiceTipsPathForUser:(int)user;
+(id)sysVoiceMailPathForUser:(int)user;
+(id)voiceMailPathForUser:(int)user;
+(id)coverImagePathForUser:(int)user;
+(id)thumbImagePathForUser:(int)user;
+(id)fullImagePathForUser:(int)user;
+(id)usrHeadImagePath:(int)path;
+(id)usrCoverImagePath:(int)path;
+(BOOL)deleteUsrDir:(int)dir;
+(BOOL)initUserDir:(int)dir;
+(BOOL)initAppDir;
+(id)pathOfUser:(int)user;
+(id)sysConfigPath;
+(id)appPublicThumbImagePath;
+(id)publicDbPath;
+(id)appInfoPath;
+(id)pathOfGameDataRootDir:(int)gameDataRootDir;
+(id)usrProfile:(int)profile;
+(id)usrSound:(int)sound;
+(id)usrImage:(int)image;
+(id)usrDbPath:(int)path;
+(id)strangersThumbCoverImagePath;
+(id)strangersThumbImagePath;
+(id)strangersFullImagePath;
+(id)strangersImagePath;
+(id)strangersDbPath;
+(id)strangersPath;
+(id)usrOtherFilePath:(int)path;
+(BOOL)createDir:(id)dir;
+(id)docPath;
@end

