/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */



@protocol WXCMultiTalkApiDelegate
-(void)onMultiTalkRedirectOk;
-(void)onMultiTalkAudioDeviceUnPlugin;
-(void)onMultiTalkAudioDevicePlugin;
-(void)onReceiveVideoMemberChangeMsg:(id)msg extArray:(id)array;
-(void)onReceiveReawakeOrPokerMsg:(id)msg extData:(id)data;
-(void)onReawakeFriendOrSendPokerToFriendResult:(BOOL)friendResult;
-(void)onRespActiveGroupBriefInfoList:(id)list isSuccess:(BOOL)success;
-(void)onReceiveMutilTalkPokerMsg;
-(void)OnSysCallNotifyInterrupt:(int)interrupt;
-(void)onAddMultiTalkMemberResult:(BOOL)result groupInfo:(id)info;
-(void)onErr:(int)err;
-(void)onSpeakerStateChange:(BOOL)change;
-(void)onVideoData:(unsigned long)data Bgra:(char*)bgra Width:(unsigned long)width Height:(unsigned long)height frontCamera:(BOOL)camera;
-(void)OnVideoStateChange:(BOOL)change VideoOn:(BOOL)on;
-(void)onMuteStateChange:(BOOL)change;
-(void)onMultiTalkDeviceLauchSuccess;
-(void)onMultiTalkReady;
-(void)onMemberChange:(id)change;
-(void)onReceiveMissMultiTalk:(id)talk;
-(void)onEnterMultiTalk:(id)talk;
-(void)onCancelCreateMultiTalk:(id)talk;
-(void)onCreateMultiTalk:(id)talk;
-(void)onInviteMultiTalk:(id)talk;
@end

