/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NSData, WXCPbVoipRelayData, NSString;

@interface WXCPbCSVoiceAckReq : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSData* mailAuthBuf;
@property(assign, nonatomic) unsigned userAbility;
@property(retain, nonatomic) WXCPbVoipRelayData* capInfo;
@property(assign, nonatomic) long long roomkey;
@property(assign, nonatomic) int roomid;
@property(retain, nonatomic) NSString* groupId;
+(void)initialize;
@end

