/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"


@interface WXCPbVoiceConf : WXPBGeneratedMessage {
}
@property(assign, nonatomic) int nVcodecType;
@property(assign, nonatomic) int nDispRate;
@property(assign, nonatomic) int nCpuflag;
@property(assign, nonatomic) int nMtusize;
@property(assign, nonatomic) int nNetType;
@property(assign, nonatomic) int nNetKbps;
@property(assign, nonatomic) int nOstype;
@property(assign, nonatomic) int nOutFmt;
@property(assign, nonatomic) int nInFps;
@property(assign, nonatomic) int nHeight;
@property(assign, nonatomic) int nWidth;
@property(assign, nonatomic) int nDisableVideo;
+(void)initialize;
@end

