/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import "WXPBGeneratedMessage.h"

@class NSMutableArray, NSData, NSString;

@interface WXCPbCSVoiceMemberWhisperReq : WXPBGeneratedMessage {
}
@property(retain, nonatomic) NSData* whisperBuf;
@property(retain, nonatomic) NSMutableArray* whisperToUsernames;
@property(retain, nonatomic) NSString* groupId;
+(void)initialize;
@end

