/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: (null)
 */

#import <XXUnknownSuperclass.h> // Unknown library
#import "WeChat-Structs.h"


@interface WXTalkieComponent : XXUnknownSuperclass {
	WXTalkieEngineAdapter* _engineAdapter;
	ILiveConEngine* _wxTalkEngine;
}
@property(assign, nonatomic) ILiveConEngine* wxTalkEngine;
@property(assign, nonatomic) WXTalkieEngineAdapter* engineAdapter;
-(void)dealloc;
-(id)init;
@end

